### ISSUE TITLE
CodeGen is not considering the typescript interface from Graphql  schema

### ISSUE THREAD

**Issue by venkatg2** [apollographql/apollo-ios#1055]
Hi Team,

 I have schema which has set of items and each item is having similar properties. So in schema design those common properties are typed as interface and  each item implements this interface. 

it works fine in server side. But in client side, when i try to generate to model in iOS side using codegen, 
The interface is not helping to model more generic way. 

What i am expecting that in swift side. 

That interface in graphql typescript would be converted as protocol or base class which will have common properties and the types which are confirming to this could be an associatedType. 

I am not sure whether it is already available. Please tell me if there is any other way to do that. 

Thanks,
Venkat

**Comment by designatednerd** [comment]
Hi! So with type-safe languages like Swift, there's some issues with trying to model a class or a protocol based on the full definition of a GraphQL object. The most obvious example is that properties that are required by the schema could be absent since they weren't requested. At that point, should that be an optional or a non-optional property? It's really hard to tell.

This is why we use nested types - because the properties represented in the nested types are the ones we can guarantee we'll have information about with that particular operation. If we can't guarantee we'll have information about a property, then we don't even allow you to access that property at all when using the result of that operation. 

If you have pieces that you are reusing, the best way to represent this is via [fragments](https://graphql.org/learn/queries/#fragments) - that allows you to say "Here is a common set of properties on this object that I will be repeatedly referencing.", and a fragment struct gets generated for you. 

Does that make more sense?

**Comment by sneakyness** [comment]
It feels like a smell to me, but I've ended up doing something like this:

```
fragment UserDetails on User {
  userId
  username
  firstName
  lastName
  email
}
```

and the actual queries end up looking like this

```
query fetchUser(
                $userId: ID
                $email: String
                ) {
  fetchUser(userId: $userId, email: $email) {
    ...UserDetails
  }
}
```

so that when you have other queries that return users, you can initalize your User object with the fragment `result.data.user.fragments.userDetails`

**Comment by venkatg2** [comment]
I am not still convinced with Fragment, although it creates separate structure. 
I was expecting that i would have some protocol or base collection for all the common type in schema. 
And i am new to grpahl in server side. May be if something can be improved in schema design. 
Hopefully the second item(Start generating code with Swift instead of Typescript) in the roadmap will be giving more flexibility or standard in swift code.  https://github.com/apollographql/apollo-ios/blob/master/ROADMAP.md

**Comment by designatednerd** [comment]
Yep, one thing that will be happening in the Swift codegen is representation of fragments as protocols rather than separate structs. Really just at the beginning of that project though. 

> I was expecting that i would have some protocol or base collection for all the common type in schema.

Can you elaborate a little bit about what you mean by this? Do you mean a protocol for each type you could get back from the server, or something else?

**Comment by venkatg2** [comment]
may be i can put some example
i have schema something like this

interface XXX {
value1: String
value2: CustomType 
}

type Type1 implements XXX {
value1: String
value2: CustomType 
}

when i generate the swift model for this case i would expect protocol or sort of base class.. 
Although i am getting separate struct for fragments, which is not giving that much flexibility with big nested queries.

**Comment by designatednerd** [comment]
Yeah this is where what I was talking about around **available** fields vs **included** fields comes in: 

`value1` and `value2` are **available** to be requested on `Type1`. This example is slightly different since both properties are optional, but if `value1` was a required `String!` instead, the problem is clearer: When you generated a protocol or type for `Type1`, should `value1` be represented as non-optional in Swift since it's required to exist, or as optional in Swift, since it could be not present? 

This is why we have the nested queries: To only give you access to the fields you've *actually* requested on a particular type. You can use fragments at any point in that nesting, but in terms of our guarantee of end-to-end type safety, that's why this is done this way.

**Comment by designatednerd** [comment]
@venkatg2 @sneakyness Any further questions on this, or does this help explain why we're doing it the way we are?

**Comment by designatednerd** [comment]
Since I haven't heard anything back here in a couple weeks, I'm going to close this issue out - @venkatg2 if you're still having problems feel free to reopen. Anyone else experiencing similar problems, please open a new issue. Thank you!
