### ISSUE TITLE
Codegen ApolloCLI folder

### ISSUE THREAD

**Issue by crabman448** [apollographql/apollo-ios#1057]
Hi 👋 

I have couple questions regarding the new Codegen 🙂
1. Is it a good practice to add ApolloCLI folder to the `.gitignore`?
2. I ran into an issue when my build was failing because I didn't have an empty ApolloCLI folder inside SwiftScripts folder. After I created an empty ApolloCLI folder my build succeeded. I didn't have such folder because I added ApolloCLI to `.gitignore`. Do you have any ideas how to overcome this problem?

Thank you!

**Comment by designatednerd** [comment]
1. Yes, absolutely. Otherwise you wind up checking a ton of JS in to your repo that has nothing to do with your project
2. I got around this by force-adding an empty `.keep` file within `ApolloCLI` to git just to preserve the folder structure, but we should probably just create the folder if it doesn't exist in the longer term.

**Comment by crabman448** [comment]
Thank you for the reply, I will use `.keep` file for now then 👍
