### ISSUE TITLE
Cache key by query parameter

### ISSUE THREAD

**Issue by Mangese** [apollographql/apollo-ios#1065]
I have two queries: 

`Articles.graphql` returns a list of articles
```
// typeDefs articles: [Article]

query Articles {
  articles {
    id
    status
  }
}
```
 
`Article.graphql` returns an article with specified id
```
// typeDefs article: Article

query Article($id: ID!) {
  article(id: $id) {
    id
    status
  }
}
```

Assume that I made the first query `Articles` and got 3 articles with id = 1, 2, 3 from the server. I'm generating cacheKey using the formula below: 

> cacheKeyForObject = __typename:id

then watch query Article with id = 1

Current Behavior
Apollo Client will send the watch query to the server once because cacheKey 

> QUERY_ROOT:article(id: 1)

 does not exist even there already has a cacheKey 

> article:1.*

 in the cache from the Articles query

so I think it would be good if we can create a cacheKey from query + parameter to see if there already has a data so apollo client doesn't need to send the request to server.

**Comment by designatednerd** [comment]
Yeah I've been finally wrapping my head around this recently - it's a little annoying because the `article` in each case represents different things. 

If you're creating a `cacheKeyForObject` with `__typename` and `id`, it's difficult, because you don't automatically know that the type of `article` is, in fact, `article`, until that field comes back from the server. At that point, `article` still just the name of the query you're making. 

That's why we're pre-pending that `QUERY_ROOT` at the beginning: Because fundamentally the type of what's being cached there is a query, not a typed object, and that's why hitting that query is fundamentally different from hitting the cached object. 

It's definitely a completely different way of thinking about cache keys than I was used to before I started thinking about it in terms of the graph, but once you think of it from that perspective, it does start to make marginally more sense. 

Does that help?

**Comment by Mangese** [comment]
I'm already trying to use default cacheKeyForObject or cacheKeyForObject = id but the result is the same

assume that I have a  TableView that contains articles as a cell (You can think that it look like a Facebook feed). 
First, I need to query for articles to display as a cell then I need to know if currentuser click likes some articles to change the state of like button. But instead of watching a whole articles query, I choose to watch for each cell instead. Which is good in the case that feed has duplicated article. But if we assume that feed always contain unique article, then watch query always need to request to the server once because cache cannot access object

any suggestions?

**Comment by Mangese** [comment]
I has an idea that apollo already knows the query's return type from Schema.
Ex. article: Article, articles: [Article]
can we assume the result of the query before made an actual request.
Ex. from schema we already knows that article query always returns Article or null. So if the query parameter contain id or something related to cacheKeyForObject, search the return type with given id first. if it already in cache return it, if not send a request to the server

**Comment by designatednerd** [comment]
It knows the return type, but the return type and the `__typename` are not always identical, so we can't make that assumption when hitting the cache before going to the network.

Unfortunately there's an awful lot of real weird things that are perfectly legal to do in GraphQL that make seemingly obvious assumptions invalid.

**Comment by Mangese** [comment]
thanks for the answer. I'll try others way to implement cache on my app
