### ISSUE TITLE
same model for multiple queries ios

### ISSUE THREAD

**Issue by venkatg2** [apollographql/apollo-ios#1068]
i have a root query which  has two sub queries  and when i generate model  in iOS it has root struct with these properties (alias of those sub queries).

And i like to call the sub query directly not through root query.. and model should be same the model which is already created in first step. 

is that possible to do like this?..

so fat my understanding is that  each query generates in own class,

**Comment by designatednerd** [comment]
Generally each query generates its own class, yes. You can use fragments to handle the parts of the data that have the same fields when things are returned.

**Comment by venkatg2** [comment]
ok.. how this can be done 
i have a query 

query xxx {
attribute1
attribute2
}

and i generate the class in swift

it generates as

class xxxQuery {
}

now i want to get the updated data  of attribute2 only.  in graphql that is one of the cool thing, we can query only what we need.
how ios client supports this with existing generated class ?

**Comment by venkatg2** [comment]
and i see.. operationDefinition is constant queryDocument is computed property.. if we can make it dynamic property. then single class can support single query with dynamic attributes. 
i m saying as per the understanding.

**Comment by designatednerd** [comment]
Hey @venkatg2, apologies for the slow response on this one. That is definitely theoretically possible, but that breaks one of the core philosophies of this implementation: Type-safe handling. 

If you can swap out the `queryDocument`, then the types being returned at runtime can potentially be different than the types which were defined at compile time, which is going to cause all the parsing to fail spectacularly. 

What's the advantage you see to having a single class with subclasses rather than query-specific structs?

**Comment by designatednerd** [comment]
Since I haven't heard anything back here in a couple weeks, I'm going to close this issue out - @venkatg2 if you're still having problems feel free to reopen. Anyone else experiencing similar problems, please open a new issue. Thank you!
