### ISSUE TITLE
Cannot return data from the SQLite cache if the query has "."

### ISSUE THREAD

**Issue by evanzhou89** [apollographql/apollo-ios#1071]
For example here is the query: 

> QUERY_ROOT.repository(name:apollo-ios,owner:apollographql).object(expression:master:Package.swift)

Apollo-ios version: 0.23.1

**Comment by designatednerd** [comment]
This is likely related to #991, which was working around a bug around periods in cache key names. 

@giantramen any thoughts on this?

**Comment by giantramen** [comment]
No easy fix here like there was for my issue, “.” is used to split the query path so there’s no way to tell your “.” shouldn’t be used to split as is. 
Any way you could strip the “.swift” on your end?

**Comment by designatednerd** [comment]
Woof, that's going to be somewhere between a pain in the ass and impossible because of the way that `QUERY_ROOT` cache key is generated. Using the `cacheKeyForObject` won't really help much in terms of preventing refetches, because that's used more for notifiying watchers of a changed result. 

This is definitely a bug. The long-term solution is probably to use something other than `.` as the cache key separator on our end when I update our cache as part of Phase 2 of the Swift Codegen project.

**Comment by kyum1n** [comment]
Is there any update on this case? We seem to run into this aswell because we send params like app version or access tokens which can contain a `.`. Getting rid of all dots on the backend side is not feasable for us. For now we have to use a fork with the previously mentioned workaround from [#329](https://github.com/apollographql/apollo-ios/issues/329#issuecomment-524451777). It works so far but I'm not sure I fully understand the scope of that workaround and if it brings its own problems.

**Comment by designatednerd** [comment]
Nope, not yet, this phase is still a ways out, unfortunately.
