### ISSUE TITLE
Apollo couldNotConvert (getting Dictionary expecting Int)

### ISSUE THREAD

**Issue by tushar666** [apollographql/apollo-ios#1075]
**Schema as below-:**
{
            "name": "price",
            "description": null,
            "args": [],
            "type": {
              "kind": "SCALAR",
              "name": "Int",
              "ofType": null
            },
            "isDeprecated": false,
            "deprecationReason": null
          },

**API.swift-:**
GraphQLField("price", type: .scalar(Int.self)),

**Response Error-:**
path "query_name.0.price)": couldNotConvert(value: {
    price = 112;
}, to: Swift.Int)

How to solve this with custom scalar please help with an example

**Comment by designatednerd** [comment]
If your schema says it expects an `Int`, a custom scalar's not going to help you, since those are also defined at the schema level. 

It sounds like your backend is breaking the contract of the schema by sending back a dictionary when it's specified an `Int` - I would first recommend checking in with that team to find out why that change was made and whether they have an updated schema you should be using.

**Comment by designatednerd** [comment]
hey @tushar666, were you able to follow up with your backend team?

**Comment by designatednerd** [comment]
Since I haven't heard anything back here in a couple weeks, I'm going to close this issue out - @tushar666 if you're still having problems feel free to reopen. Anyone else experiencing similar problems, please open a new issue. Thank you!
