### ISSUE TITLE
SQLiteNormalizedCache encryption

### ISSUE THREAD

**Issue by pgawlowski** [apollographql/apollo-ios#1117]
I've got pretty fragile data to cache in a persitant way via grapqhl SQLiteNormalizedCache.

What are the security measures of SQLiteNormalizedCache? Is there any kind of encryption or possibility to inject middleware for ecryption/decryption? 
I was thinking about integrating iOS SQLCipher in between however can not find any information how to handle or how it is being handled right now?

**Comment by designatednerd** [comment]
Anything that would be provided is provided through the [SQLite.swift](https://github.com/stephencelis/SQLite.swift) dependency, which it looks like it has [the ability to integrate with SQLCipher](https://github.com/stephencelis/SQLite.swift/blob/master/Documentation/Index.md#using-sqliteswift-with-sqlcipher).

**Comment by designatednerd** [comment]
Since I haven't heard back here in 2 weeks and this functionality is covered by `SQLite.swift`, I'm going to go ahead and close this out. Please let me know if you have further questions. Thank you!

**Comment by pgawlowski** [comment]
I was messing around with SQLCipher however I failed with integration.
Are there any additional suggestions how to handle? 
Is for example `withinReadWriteTransaction` and `withinReadTransaction` valid place to encrypt/decrypt data?

**Comment by designatednerd** [comment]
Unfortunately we don't have any recommendations around this - generally this kind of security is handled at the database level rather than what we're dealing with, which is once stuff has come out of the database (or before it's gone in). 

If you were to do it the way you suggest, you'd have to manually do that in every single read/write transaction, and it would most likely break a bunch of stuff like query watchers. It *could* work if you're OK with those other trade-offs, but I would strongly recommend finding something at the level of the database itself that handles this for you.

**Comment by pgawlowski** [comment]
OK I've figured out sth. 
Integration actually is possible. It requires small dependency modification in podspec - SQLCipher instead of pure SQLite.
I was thinking how we could possibly integrate this in a painless way with current Apollo/SQLite implementation. 

One idea is to introduce additional way of initialization directly with DB instead of filePath.
>public init(db: Connection shouldVacuumOnClear: Bool = false)

Do you think this kind of changes might be possible? I can prepare podspec + SQLiteNormalizedCache changes. 

We can also introduce SQLiteEncryptedNormalizedCache implementation however this will be exactly the same as current implementation with 2 additional lines.
`try db.rekey(secret)`
to set passphrase and 
`try db.key(secret)`
to unlock it :) 

Any thoughts?

**Comment by designatednerd** [comment]
Thoughts shared in the PR - basically it looks like SQLCipher requires an overly complicated integration story which we really don't have the bandwidth to support, so the recommendation would be to create your own `NormalizedCache` implementation that uses an encrypted database rather than trying to glue encryption onto what we've already got.

**Comment by ArunVicky001** [comment]
is that encryption was added in the `SQLiteNormalizedCache` in the latest library?

**Comment by ArunVicky001** [comment]
will CryptoSwift help to achieve this? https://github.com/krzyzanowskim/CryptoSwift
