### ISSUE TITLE
error: SWIFT_VERSION '3.0' is unsupported, supported versions are: 4.0, 4.2, 5.0. (in target 'Apollo macOS' from project 'Apollo')

### ISSUE THREAD

**Issue by misbell** [apollographql/apollo-ios#1125]
error: SWIFT_VERSION '3.0' is unsupported, supported versions are: 4.0, 4.2, 5.0. (in target 'Apollo macOS' from project 'Apollo')

getting this error when I try to do a carthage build with latest tag

**Comment by designatednerd** [comment]
Hi, that's correct, we don't support Swift 3. What version of Carthage and Xcode are you using?

**Comment by designatednerd** [comment]
Since I haven't heard anything back in a week and we only support Swift 5 and up, I'm going to close this out. I would recommend checking what version of swift your project is using. @misbell  you're using Swift 5 and still running into this problem, you should reopen this. Anyone else, please file a new issue. Thank you!
