### ISSUE TITLE
generated API.swift change alias name of subField

### ISSUE THREAD

**Issue by Mangese** [apollographql/apollo-ios#1133]
Apollo's auto generate class from .graphql file will change a field name of fragment

Assume that I have graphql schema as below

```
fragment ArticleAuth on Article {
    authAs: v1_auth {
         read
    }
}
```

when compile done. API.swift has generated 

`public struct AuthA: GraphQLSelectionSet`

instead of `AuthAs`. this happend to all alias name that in camel-case with Pattern xxxxXs Ex. authAs, authBs. but other pattern like xxxXxs work correctly Ex. authBus, authAus, authBusiness

**Comment by designatednerd** [comment]
I think this is some of our over-aggressive pluralization/de-pluralization at work here - it thinks it's  the plural of `AuthA` rather than `Auth As`. Unfortunately, there's not a great way to work around this in current codegen. 

Gonna leave this open as a bug - I want to add a way to allow workarounds to some of the pluralization/depluralization issues we're seeing in current codegen to the Swift codegen.
