### ISSUE TITLE
How to generate objects without using them inside queries or mutations

### ISSUE THREAD

**Issue by yuzushioh** [apollographql/apollo-ios#1197]
I want to generate an `ErrorCode` object defined in my schema.json. Is there any way to achieve this? ErrorCode definition is like this.

```
{
        "kind": "ENUM",
        "name": "ErrorCode",
        "description": null,
        "fields": null,
        "inputFields": null,
        "interfaces": null,
        "enumValues": [
          {
            "name": "INVALID_ID",
            "description": null,
            "isDeprecated": false,
            "deprecationReason": null
          },
          ...
        ],
        "possibleTypes": null
}
```

**Comment by designatednerd** [comment]
TL;DR: No, not if you're not using it anywhere. 

The problem is that our code generation takes a combination of what's in the schema and what's in your queries to generate code, and we specifically avoid generating code for unused types to avoid generating a potentially enormous amount of code which would never be used. 

The format of the intermediate representation used to generate the code is also different from the schema, so it's not like there's something you can just feed it into. Unfortunately generating this without a usage is just not something you're going to be able to do.
