### ISSUE TITLE
Build failed issue 

### ISSUE THREAD

**Issue by prabhatVinsol** [apollographql/apollo-ios#1200]
Checking if CLI needs to be downloaded...
Downloading zip file with the CLI...
curl: (22) The requested URL returned error: 404 Not Found
Command PhaseScriptExecution failed with a nonzero exit code

**Comment by designatednerd** [comment]
@prabhatVinsol Hi looks like there was a brief burp in service and it is back up now, can you please retry? Thank you.

**Comment by designatednerd** [comment]
@aantonello You will need to update to the most recent patch version of whatever version of Apollo you're using - we had a change in service that required a new download URL, and new patch versions have been released for `0.18.x`-`0.25.x` (see #1177 for details). 

@prabhatVinsol if you are not on `0.26.0` or higher, you will also want to try updating to the most recent patch version of the library.

**Comment by aantonello** [comment]
@designatednerd, thanks.

That works. I had to `pod repo update` because the last version I could see was 0.25.0. After updating CocoaPods brought me the version 0.27.1 and that solved the issue.

**Comment by designatednerd** [comment]
I'm going to go ahead and close this out - #1177 is still pinned to help people see that they need to update to a newer patch version if they're having problems, and there's no (active) issue with Github at this time. 

Also, for what it's worth, we're looking at an alternative to using Github for artifact hosting given the issues we've seen in the last couple weeks. The good news is because this is now behind a CDN, that will not require any further changes to the SDK. 🎉

**Comment by XiaoxiaYao** [comment]
For these who are still using 0.21. My solution is to put the zip(I have it locally :)) which is 404 looking for to the script folder. Hit the build. Then it will work.
![Snip20200522_2](https://user-images.githubusercontent.com/22899096/82626064-63297c00-9c19-11ea-8547-97973472c329.png)
[apollo.tar.gz](https://github.com/apollographql/apollo-ios/files/4665812/apollo.tar.gz)

**Comment by designatednerd** [comment]
That will also work (you can also download the zip from the apollo-tooling release), but it would probably be a lot easier to upgrade to 0.21.1, which has a new CDN-powered link.
