### ISSUE TITLE
How to subclass URLSessionClient to have a custom URLSession

### ISSUE THREAD

**Issue by dchohfi** [apollographql/apollo-ios#1201]
Hey, on the recently update was introduced a new type called `URLSessionClient` that has the `URLSession` used to fetch data as a `private(set)` attribute.

I use on my project a custom instance of `URLSession` to be able to switch between real and fake data.
I use [Vinyl](https://github.com/Velhotes/Vinyl) to be able to replay recorded https sessions on my functional tests.

Thank you!

**Comment by designatednerd** [comment]
Unfortunately, because you can only set a `URLSession`'s delegate in the initializer, we have to initialize the `URLSession` within the `URLSessionClient`. There's no way to pass a `URLSession` *into* `URLSessionClient` and still have it fundamentally work.  

However, the `URLSession` is available as a property - could you use [the `Turntable` initializer which takes a `URLSession`](https://github.com/Velhotes/Vinyl/blob/ebcec23c80087dc6539b8fb262316b4cfd8e772d/Vinyl/Turntable.swift#L29) and pass in the session from `URLSessionClient`?

**Comment by dchohfi** [comment]
@designatednerd thx for the answer, yah that makes sense, going to give it a try using the initializer.

Nevertheless, congrats and thank you for all the effort on this library, one of the best documented and well implements libs I've used, so easy to extend. 👏👏👏

**Comment by designatednerd** [comment]
Thanks! Big props to @martijnwalraven for getting it all up and running. 

Do you mind if we close out this issue?

**Comment by designatednerd** [comment]
I'm gonna go ahead and close this one out - @dchohfi please feel free to reopen if you're still running into problems. If someone else has got a similar problem, please open a new issue. Thank you!
