### ISSUE TITLE
Realm Mobile Database Integration

### ISSUE THREAD

**Issue by jeffreyhanna** [apollographql/apollo-ios#121]
Realm provides a free, open source, cross-platform, mobile database. Seems like it would be a great candidate for integration (I don't work there, just a fan).

Realm uses your native class definitions as the schema and has convenient features for serialization and JSON. It handles persistence very easily and has a great API for queries, notifications, etc.

There's very little overhead to using Realm. I think you would just have to generate the model class definitions which should look almost identical to what you're already generating. The model classes just have to inherit from Realm. Seems like it could save you a lot of work compared to duplicating all of that functionality with something like SQLite.

**Comment by martijnwalraven** [comment]
A fundamental difference between data layers like Core Data or Realm and Apollo iOS is that the generated types here are specific to GraphQL queries, not the schema. They are basically views on the same underlying data.

If you take these queries:

```graphql
  query AllPosts {
    allPosts {
      id
      title
    }
  }
```

```graphql
  query PostDetails($id: ID!) {
    post(id: $id) {
      id
      title
      author {
        id
        firstName
        lastName
      }
      body
    }
  }
```

Both queries refer to the `Post` type, but the generated `AllPosts.Data.Post` and `PostDetails.Data.Post` structs are separate types and only contain a subset of the fields. So it wouldn't make sense to use either of these as a model in the Realm sense. The cache in Apollo iOS is normalized, to make sure that different responses still update the same underlying data and changes are reflected in all queries.

**Comment by jeffreyhanna** [comment]
@martijnwalraven thanks for the clarification! That makes sense, and I understand the value of query-based types rather than schema-based types as far as safety, but it seems like a lot to give up.

If the Realm model properties were optional then the queries could return the "full" model with nil values for the properties not included in the query, and then you'd get all the features of Realm as a persistent store without having to reimplement them yourself.

Looking at your last snippet, that's the protocol I would have to implement with Realm to create the integration?

**Comment by martijnwalraven** [comment]
Yes, that is the protocol you would have to implement. If you wanted to integrate with Realm, I think your best bet would be to build directly on the [core database](https://github.com/realm/realm-core) instead of going through the model layer. I don't want to sound too negative, but I'm afraid mapping to model classes isn't a very good match for GraphQL.

You'd have to generate Realm models with 'merged' properties from all queries, and change these whenever a new query adds a field (and like you said, all properties would have to be optional). 

That in itself is not necessarily an issue, but one complication is that fields in GraphQL are like functions and can take arguments. So a field like `greeting(name: string)` is perfectly valid. What should the corresponding property in the Realm model be?

In the generated structs, we use the response name (field name or alias). When normalizing, we construct a cache key that also includes the argument value ('greeting_Jeffrey`) basically.

So these cache keys are dynamic and can't be used to generate code. The way this works with other caches is that a `NormalizedCache` implementation only has to deal with flat, untyped `Record`s (basically just a map with string keys and primitive values). You may be able to integrate with the Realm core database at this level, but I'm not sure if that would be worth it.

**Comment by KieranLafferty** [comment]
Not sure if it's useful at all but I've created a codegen for realm using `apollo-codegen`. The codebase has changed quite a bit since I created if someone can modernize it then this repo should serve as a good starting point.

It works nearly exactly as @martijnwalraven described above and generates a models by aggregating their properties. 

https://github.com/KieranLafferty/apollo-codegen

**Comment by designatednerd** [comment]
@KieranLafferty Thanks for your work on that!

At this point we do not plan to integrate first-party support for Realm into the Apollo iOS SDK, although I've got some long-term plans to make it easier to choose what persistence you want to use at the user level without the Apollo framework having to know or care what you plug in. Watch this space, but it'll likely take a while to get up and running.

I'm going to close this out in the meantime since Realm is definitely not going to be something we'll support directly. Please feel free to reach out to me with any questions. Thank you!
