### ISSUE TITLE
Receive failed with error "Software caused connection abort" 

### ISSUE THREAD

**Issue by DiwakarThapa** [apollographql/apollo-ios#1218]
I have been seeing **error Receive failed with error "Software caused connection abort"  along with Connection7: received failure notification, nw_flow_add_write_request cannot accept write requests from socket**. This error appears when app is in background and receives silent notification because socket get disconnected when app enter in background. So my **question** is it possible  to **update app in the background through socket immediately after silent notification wakes the app** ?

**Comment by designatednerd** [comment]
Web sockets aren't really intended to work in the background - they're designed to be permanently open if the app is in the foreground. Having a permanently open connection in the background would be a huge battery suck. There's not an initializer available through us that allows this. 

You can use `URLSessionClient` by passing in a background session configuration you receive from the system to instantiate it in order to perform regular HTTP requests.

**Comment by DiwakarThapa** [comment]
got it! thank you @designatednerd

**Comment by designatednerd** [comment]
Great! Mind if we close this out?

**Comment by designatednerd** [comment]
Going ahead and closing out since I haven't heard back in almost three weeks. If you're having similar problems, please open a new issue. Thanks!
