### ISSUE TITLE
Does this package integrate with SwiftUI?

### ISSUE THREAD

**Issue by joshuarobs** [apollographql/apollo-ios#1221]
I'm wondering how this package works within an iOS project, since I am new to iOS development. Does this package have some sort of way we can incorporate it easily within our SwiftUI views?

**Comment by designatednerd** [comment]
Yeah, you can definitely use it with SwiftUI - for anything which has an `id` property that's a `GraphQLID`, you should be able to make it identifiable by adding an extension, which will then pick up on `id` automatically like so: 

```swift
extension MyWhateverQuery.Data.ReturnType: Identifiable {}
```

**Comment by joshuarobs** [comment]
@designatednerd Are there any existing tutorials that link up this package with SwiftUI or any plans to make them?

For someone thats new to iOS development and has only been playing around with SwiftUI, namely just putting Views together in VStacks, Hstacks, etc. I am completely clueless as to how this Swift code would integrate within a View that can be easily used.

Also regarding Paul Hudson's 100 days of Swift UI primer, do you know which lessons (days) would cover making this extension and identifiable stuff work with SwiftUI?

**Comment by designatednerd** [comment]
I do eventually plan to migrate the tutorial to using SwiftUI - the problem is that we support alllll the way back to iOS 9 and Swift UI is iOS 13 only, so I wanted to wait a bit to convert the tutorial until a) More developers who want to use this are using SwiftUI and b) the 2nd version is out with iOS 14. 

Looks like if you want to take a shortcut in the 100 days, a place to start is "Project 5", which introduces working with lists. Honestly, I would really recommend working through the whole thing - I've been doing Swift stuff since it started and I still learned a ton, and I bet it would be a big, big help if you're just getting into Swift and iOS development.

**Comment by Dreamystify** [comment]
where do you add the extension? total noob here...

I have a swiftUI project  and my id field is agent_id, how do i make that identifiable?

**Comment by designatednerd** [comment]
Hi @Dreamystify please see my response on #1547. Thanks!
