### ISSUE TITLE
Does the codegen need a .graphql file that contains ALL of your queries, mutations, subscriptions, etc?

### ISSUE THREAD

**Issue by joshuarobs** [apollographql/apollo-ios#1235]
I'm following the instructions from here: https://www.apollographql.com/docs/ios/swift-scripting/ I believe I also tried the original instructions in the tutorial that made use of the soon to be deprecated bash script.

Basically I run the new swift script and it creates the `API.swift`, `schema.json` and `operationID.json` files, however when I check inside it only contains information for one query, and not all of my queries that exist on the Apollo server.

Is this meant to happen like this? I followed the tutorial and it said to make a `.graphql` file with just one function. So I'm guessing that this codegen used all the `.graphql` files in the project, and not the `schema.json` it downloaded? 

If this is the case, is there a way to automatically get all functions exposed on the server to be downloaded in a `.graphql` file individually or together in one file? So that the codegen can work with all queries and mutations?

Or do we have to manually just create an individual `.graphql` file for each of the queries that we can call on the server?

(Note: when im talking about the server, im talking about an Apollo Server that has resolvers, type-defs, data sources, etc.)

**Comment by designatednerd** [comment]
Yes, it is meant to be like this. We only generate code for the queries you're actually going to execute, and for the properties you actually request when you execute them. Otherwise you would wind up with tons and tons of generated code you never use. 

I talk conceptually about how the schema and queries are combined to generate code [in the instructions for beta Swift Scripting](https://www.apollographql.com/docs/ios/swift-scripting/#using-codegen-to-create-a-graphql-file-with-an-operation) - let me know if that description helps.

You can either put your queries in individual `.graphql` files or one giant one, whatever works for you. Personally, I find individual files a lot clearer. The glob pattern passed into the script by default searches all child directories of the directory where it's called for files ending in `graphql`.

**Comment by joshuarobs** [comment]
Would the `.graphql` file downloaded from the `Schema` button in GraphQL Playground be sufficient to use as part of the code gen?

Or do we have to manually write out the queries that we are going to use?

**Comment by designatednerd** [comment]
So the schema and the queries are two different things. 

As I said in the link above, the schema outlines what it is **possible** to ask for. An operation (a query, a mutation, or a subscription) is what you are **actually** asking for. The code generation takes what you are actually asking for, validates it against what it's possible to ask for, and then generates code to allow automatic request setup and parsing of responses. 

They are both files that end in `graphql` (or at least can, in the case of the schema - it's also possible to have a `json` schema), but only the `graphql` files that contain operations will actually cause code to get generated.

**Comment by joshuarobs** [comment]
Thanks for clarifying that! I like the idea that it's between what's possible versus what is actually being asked for, which for actual, I'd assume would be a subset of what's possible
