### ISSUE TITLE
Subscription Failure Error WSError(type: Starscream.ErrorType.upgradeError message: \“Invalid HTTP upgrade\”, code: 400)?

### ISSUE THREAD

**Issue by PritishSawant** [apollographql/apollo-ios#1250]
Sorry to create this issue as I couldn't find any answer to my query. I tried stack overflow but unfortunately got no answer there

https://stackoverflow.com/questions/62241942/subscription-failure-error-wserrortype-starscream-errortype-upgradeerror-messa

I need to integrate subscription in my iOS app. The subscription works fine on localhost in graphiql. I have deployed my backend on Heroku. I am using apollo-server and not hasura. My subscriptions are not working for the url given by Heroku but it works fine on localhost. Queries and mutations work fine for both localhost and Heroku url. So I am trying to access my subscription from my iOS client. I have kept the base url as my local host. The queries and mutations part works for my iOS client but my subscription part is not working.

I have configured my Apollo client for subscription by adding this

```
let httpNetworkTransport = HTTPNetworkTransport(url: URL(string: "http://localhost:5000")!)
        httpNetworkTransport.delegate = self

        let webSocketTransport = WebSocketTransport(request: URLRequest(url: URL(string: "http://localhost:5000")!))


         let splitNetworkTransport = SplitNetworkTransport(
          httpNetworkTransport: httpNetworkTransport,
          webSocketNetworkTransport: webSocketTransport
        )

        return ApolloClient(networkTransport: splitNetworkTransport)
```
I also tried replacing http with ws as follows

`let webSocketTransport = WebSocketTransport(request: URLRequest(url: URL(string: "ws://localhost:5000")!))`

Subscription code is as follows

```
subscription = Network.shared.apollo.subscribe(subscription: GetHealthConsultationSubscriptionSubscription()){
            [weak self] result in
            guard let self = self else {
                return
            }
            switch result {
            case .success(let result):
                debugPrint(result.data?.healthConsultation.chiefComplaint)

            case .failure(let error):
                debugPrint(" Subscription Failure Error \(error)")
            }
        }
```

But I am getting error from my iOS client as follows

Subscription Failure Error WSError(type: Starscream.ErrorType.upgradeError, message: \"Invalid HTTP upgrade\", code: 400)

Also when I use Graphiql for my subscription and replace localhost with the Heroku url for my subscription , I get following error.

![IT2Io](https://user-images.githubusercontent.com/24708929/84044391-23a6b200-a9c5-11ea-96d1-80b7241aacdd.png)

**Comment by designatednerd** [comment]
So that error shows the websocket endpoint being reached with `ws` - in the iOS app, have you tried using `ws` as the prefix rather than `http` for the endpoint when setting up the `WebSocketTransport`? Some cursory googling indicates that [some servers don't support upgrading from http to ws and you need to connect directly with ws](https://stackoverflow.com/a/58120218/681493).

**Comment by PritishSawant** [comment]
Yeah I tried replacing http with ws. I am not a backend engineer but does localhost supports ws?

**Comment by designatednerd** [comment]
Ah! Sorry I missed that in your original post, I see it now. 

I'm also not a backend eng - in theory whether `ws` vs `http` upgrades are supported depends on what server software you're using, not about whether the server is running on `localhost` or not. However, [some posts in this thread](https://github.com/daltoniam/Starscream/issues/123#issuecomment-232326641) indicate you might be able to get it to work if you use an IP address rather than `localhost`. I'd say that's probably your next thing to try - it does seem like this is something that you might want to look through issues in Starscream about, there's a fair few of them.

**Comment by PritishSawant** [comment]
Thanks a lot Ellen. Closing this issue
