### ISSUE TITLE
Polling

### ISSUE THREAD

**Issue by quinnvaughn** [apollographql/apollo-ios#1251]
Is there no way to add a pollInterval option? I'd rather not add subscriptions to an alpha/beta if I didn't have to when down to the second updating is not mission-critical. It's on the JS client, so I would have assumed this would have it as well.

**Comment by designatednerd** [comment]
Subscriptions are implemented through WebSockets on iOS, so polling shouldn't be necessary. Can you clarify a bit what you're trying to do?

**Comment by quinnvaughn** [comment]
Users are submitting a video, although currently, it's not timed. Think about a Jackbox game where you are submitting something, and then users vote on that. Eventually, it will probably be timed, as well as use subscriptions, but that seems like unnecessary overhead for the purpose of an alpha, as opposed to just polling every 5 seconds or something.

**Comment by designatednerd** [comment]
I get not wanting to futz with subscriptions for an alpha, but we have generally made a point to tell people who need to poll to use subscriptions since it's generally far more efficient in the long term, particularly on iOS where there's substantial network and battery overhead to opening a new connection. 

Because of that, I don't think it's a great idea to add polling directly to the library - you should be able to add some kind of mechanism to do that in your own code, though.

**Comment by designatednerd** [comment]
Since I haven't heard back on this in three weeks and we don't intend to add polling capability to the library, I'm going to go ahead and close this out. If you are interested in discussing this further please stop on by the [Apollo iOS Spectrum chat](https://spectrum.chat/apollo/apollo-ios). Thanks!
