### ISSUE TITLE
How to use the --passthrough-custom-scalar flag

### ISSUE THREAD

**Issue by ijl0322** [apollographql/apollo-ios#1318]
Hi, 

I'm trying to use the --passthrough-custom-scalar flag:

`"${SCRIPT_PATH}"/run-bundled-codegen.sh codegen:generate --target=swift --includes=./**/*.graphql --passthrough-custom-scalar --localSchemaFile="schema.json" API.swift`

And getting this error `Error: Unexpected argument: API.swift`

I'm using Apollo 0.29.1 and Xcode 11.5. Any help would be appreciated, Thanks!

**Comment by designatednerd** [comment]
It's `--passthroughCustomScalars`, Pascal case instead of kebab case and plural instead of singular. I think that may be causing the parsing to fail.

If fixing that doesn't fix it, I'd switch it to after `--localSchemaFile` - that might be looking for multiple arguments but I can't remember off the top of my head. 

Let me know which one (or both) works!

**Comment by ijl0322** [comment]
The Pascal case works !! Thank you so much for your help!

**Comment by viktoricaloniapoplar** [comment]
Do we have this flag support for the Apollo 1.0.6?

**Comment by calvincestari** [comment]
@viktoricaloniapoplar - no, custom scalars have changed in 1.0. There is a [section](https://www.apollographql.com/docs/ios/migrations/1.0#custom-scalars) of the [migration guide](https://www.apollographql.com/docs/ios/migrations/1.0) dedicated to it.
