### ISSUE TITLE
长连接手动断开和重连

### ISSUE THREAD

**Issue by tanchendong1992** [apollographql/apollo-ios#1337]
你好
如何在 APP 进入后台时,手动断开长连接,从新打卡 APP 时再重新连接长连接?

**Comment by designatednerd** [comment]
Via Google Translate since I don't speak Chinese: 

> Hello there
> How to manually disconnect the long connection when the APP enters the background, and then reconnect the long connection when the APP is newly clocked in?

Are you asking about subscriptions or some other kind of long connection?

**Comment by tanchendong1992** [comment]
你好.订阅消息. WebSocketTransport
<img width="1369" alt="WeChat67a3558698ad0ab1125ec3110a335a58" src="https://user-images.githubusercontent.com/10558372/88997935-7a749c00-d323-11ea-83d6-68476be784db.png">
如果使用方法.我想在 APP 进入后台时,断开.在 APP重新打开的时候重新连接?
初学者请多见谅!

**Comment by designatednerd** [comment]
> Hello. Subscribe to news. WebSocketTransport

[Here's Apple's documentation on handling lifecycle changes](https://developer.apple.com/documentation/uikit/app_and_environment/managing_your_app_s_life_cycle) - The short answer is that you will probably want to call `closeConnection` on  the `webSocketTransport` in your App Delegate's `applicationWillResignActive` method and restart the susbcription in `applicationDidBecomeActive`. 

Note that names are different in the Scene delegate if you're using that, but I don't think you are since you're using a singleton rather than per-scene instances of `Network`. 

Let me know if that helps!

**Comment by tanchendong1992** [comment]
你好.我通过 调用 self.webSocketTransport.closeConnection() ,已经可以断开连接了. 在 UIApplicationDidBecomeActiveNotification 的时候怎么重新建立连接呢?

**Comment by designatednerd** [comment]
Google translated: 

> Hello. I can disconnect by calling self.webSocketTransport.closeConnection(). How to re-establish the connection when UIApplicationDidBecomeActiveNotification?

Ah, because `addSubscribe` won't work if the web socket isn't connected, and right now there's not a way to tell the websocket to reconnect non-automatically. 

The good news is #1335 will add the ability to reconnect more easily. Until then you'll probably need to hack it by using either `updateHeaderValues` or `updateConnectingPayload` to force a reconnection.

**Comment by designatednerd** [comment]
#1335 is merged to `main` if you want to use it immediately, it'll come out probably sometime later this week in an official release. I'm going to close this out.
