### ISSUE TITLE
No such file or directory: run-bundled-codegen.sh

### ISSUE THREAD

**Issue by angelu25** [apollographql/apollo-ios#1413]
I imported via cocoa pods the Apollo, actually it installed 0.30. 

I added exactly the same script as here:
https://www.apollographql.com/docs/ios/installation/#troubleshooting 
schema.json is under project folder, under the target folder name.
But I keep receiving:
![image](https://user-images.githubusercontent.com/6308120/94440933-75588f80-01a2-11eb-8095-c1d6862880b1.png)
Actually there is no data on SourcePackages folder about Apollo scripts.

Could you help me?

**Comment by designatednerd** [comment]
Hi, it looks like you're using the Swift Package Manager run script rather than the CocoaPods run script [outlined in this step of the setup instructions](https://www.apollographql.com/docs/ios/installation/#adding-a-code-generation-build-step), because the CocoaPods script should be looking in `Pods/apollo-ios/scripts` rather than doing the weird dance of diving through derived data that the SPM script has to do.

**Comment by angelu25** [comment]
OMG!!! True. Wee can close the ticket!!!!
