### ISSUE TITLE
spectrum.chat/apollo link is unavailable, Heroku error shown

### ISSUE THREAD

**Issue by gemmakbarlow** [apollographql/apollo-ios#1487]
## Bug report

Morning folks ! 

Not technically an Apollo bug, but I wanted to flag that https://spectrum.chat/apollo, linked from [CONTRIBUTING.md](https://github.com/apollographql/apollo-ios/blob/main/CONTRIBUTING.md), is currently returning a Heroku error.

<img width="1773" alt="Screen Shot 2020-10-30 at 9 15 04 AM" src="https://user-images.githubusercontent.com/337963/97709951-7d516b00-1a91-11eb-91a8-e323abe037af.png">

## Versions

Please fill in the versions you're currently using: 

-  N / A

## Steps to reproduce

-  N / A

## Further details

Please feel free to close this if it isn't something you are in control of / hosting yourselves. I wasn't able to find a status page for the tool / platform and am not familiar with it. Google results get mixed in with the ISP provider unfortunately. 😄

**Comment by designatednerd** [comment]
Haha, i have the same problem with the ISP, particularly since they are _my_ ISP. 

Spectrum is a chat platform that got bought out by GitHub about a year and a half ago - we'd been using them prior to that buyout and have been continuing to do so. Thanks for the heads up on this, but unfortunately there isn't much we can do about their deploys failing. Upside is it seems to be back up and running now, though!
