### ISSUE TITLE
How to parse enum using Apollo iOS sdk

### ISSUE THREAD

**Issue by poorvasingh04** [apollographql/apollo-ios#1499]
## Question
Our graphql server returns an enum value for a key in response. This enum is available in Types.graphql.swift.
After reading the response from apollo, we parse it using JSONSerialization.data()

let data = try JSONSerialization.data(withJSONObject: dict, options: [])

where dict is dictionary from response.

But in case there is a key with enum value, the parsing fails because JSOSerialization cannot map that enum value as a String.

Exception raised by Xcode - *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Invalid type in JSON write (__SwiftValue)' 

Please suggest how to resolve this issue.

**Comment by designatednerd** [comment]
That seems...fairly unusual, but let's see what we can figure out: 

- Where is this key in relation to `data` and `errors` - is it at the same level? 
- Are you implementing Apollo's `JSONDecodable` or `JSONEncodable` protocol on the enum? 
- Do you know why they're using it for a key rather than a value?

**Comment by designatednerd** [comment]
(migrating to discussions since this is more a question than an issue)
