### ISSUE TITLE
Apollo CLI step fails to locate SourcePackages directory 

### ISSUE THREAD

**Issue by alcamla** [apollographql/apollo-ios#1509]
## Bug report

I am following the steps on the tutorial for iOS. I added Apollo to the project using SPM. After adding the corresponding CLI script, and building the project, I get the following error: 
`error: Unable to locate SourcePackages directory from BUILD_ROOT: '/Users/myUser/Library/Developer/Xcode/DerivedData/Build/Products'`
I have noticed that BUILD_ROOT is set to that folder directly, so there is no chance that the while loop finds the SourcePackages folder. I am running on Xcode 12.1

## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: 0.36
- Xcode version: 12.1
- Swift version: 5.3
- Package manager: Swift package manager

## Steps to reproduce

1. Create project
2. Add Apollo dependency using SPM
3. Add new run script phase with the code generation build step for SPM
4. Modify the last line to download the schema on first run
5. Build the project

**Comment by designatednerd** [comment]
Ugh, I bet they changed the damned location of the source packages in 12.1 - it's definitely undocumented. 

I'll get a look at this tomorrow, but I think I'm going to recommend trying the [Swift Scripting Setup](https://www.apollographql.com/docs/ios/swift-scripting/) - that doesn't have any dependency on going diving through the derived data folder.

**Comment by designatednerd** [comment]
OK, so one thing that's helpful to understand is that `SourcePackages` should be in your `DerivedData` folder, in your application's folder.  at the same level as the `Build` folder, once your source packages have finished resolving. The loop is looking to find a folder which *contains* the `SourcePackages` folder for your app, rather than the source packages folder itself. Here's what that folder looks like for a sample app on my machine: 

<img width="589" alt="Screen Shot 2020-11-12 at 4 00 53 PM" src="https://user-images.githubusercontent.com/1976498/99001391-65053580-2500-11eb-94a0-ed69a8950a80.png">

So when I get the `BUILD_ROOT` it is: 

`/Users/ellen/Library/Developer/Xcode/DerivedData/SPM_Test-goryvntifjyridhfyzotpdxdwyhx/Build/Products`

It then goes one directory up, and then says, hey, does 

`/Users/ellen/Library/Developer/Xcode/DerivedData/SPM_Test-goryvntifjyridhfyzotpdxdwyhx/Build`

have a `SourcePackages` folder? When that doesn't, it goes to 

`/Users/ellen/Library/Developer/Xcode/DerivedData/SPM_Test-goryvntifjyridhfyzotpdxdwyhx/` 

and asks if it has a `SourcePackages` folder. And that one does, so it proceeds with the build. 

One thing I did notice comparing how this is working on my machine to what's happening on yours is that I'm not seeing a project-specific folder listed in that path. When you say: 

> I have noticed that BUILD_ROOT is set to that folder directly

Is this set manually, or where is this coming from?

**Comment by alcamla** [comment]
Hello @designatednerd, thanks for your reply. I haven't set this manually. Not sure if this is set per project, or is a global configuration that Xcode uses, but I have not modified it

**Comment by designatednerd** [comment]
I'm not sure what you mean by "A script to export your BUILD_ROOT variable" - in theory you should not need to export that for anything.

Are you able to replicate the issue in a fresh project? If you can't, that should at least give you a point of comparison in terms of how the BUILD_ROOT is getting set up. If you can, can you please either email it to me (ellen at apollographql dot com) or post it as a zip here? Thanks!

**Comment by alcamla** [comment]
> I'm not sure what you mean by "A script to export your BUILD_ROOT variable" - in theory you should not need to export that for anything.
Just wanted to confirm the value `BUILD_ROOT` is taking on my project

> Are you able to replicate the issue in a fresh project?
I was able to reproduce this issue on a fresh project, will email it to you

**Comment by alcamla** [comment]
I think I figured out what this issue is about. Seems that the BUILD_ROOT is set according to the configured build location. Under( Preferences -> Locations -> Derived Data, go to advance settings; the build location option should be set to `unique`. I had selected the `Custom` option, which was giving me the above mentioned issue. The whole lesson from this is that the [Swift Scripting Setup](https://www.apollographql.com/docs/ios/swift-scripting/) should be the way to go, since is less dependent on local configurations. Thanks @designatednerd  for your support.

**Comment by designatednerd** [comment]
Ahhhhh! Yeah that's a pretty significant footgun, I'll throw a quick note in the current instructions until I get a chance to rewrite everything

**Comment by harsh12312** [comment]
Hi @designatednerd I was trying to implement GraphQL using Swift Scripting Setup, one thing i wasn't able to understand is how can i send Authorization token in the main.swift file?

**Comment by calvincestari** [comment]
Hi @harsh12312, if I understand correctly what you're trying to do is to send an authorization token in the schema download request? If so then in `main.swift` you want to [alter the `ApolloSchemaDownloadConfiguration` instance](https://github.com/apollographql/iOSCodegenTemplate/blob/main/ApolloCodegen/Sources/ApolloCodegen/main.swift#L40) to [set the HTTP header](https://github.com/apollographql/apollo-ios/blob/main/Sources/ApolloCodegenLib/ApolloSchemaDownloadConfiguration.swift#L102) for "Authorization". The codegen engine will then include that in the request to download the schema.

It should end up looking something like this:
```
let schemaDownloadOptions = ApolloSchemaDownloadConfiguration(
  using: .introspection(endpointURL: endpoint),
  headers: [ ApolloSchemaDownloadConfiguration.HTTPHeader(key: "Authorization", value: "your token here") ],
  outputFolderURL: folderForDownloadedSchema
)
```

**Comment by harsh12312** [comment]
That solved it for me. Thanks! @calvincestari
