### ISSUE TITLE
Bigint support

### ISSUE THREAD

**Issue by joshuarobs** [apollographql/apollo-ios#1627]
## Feature request

Support for big integers (8 byte numbers)

## Motivation

Some tables in the database (e.g. postgres) may have bigints as the id type, instead of other common types such as strings, integers (4 bytes) and UUIDs. I'm not exactly sure if the iOS app will crash or not, if it somehow receives a bigint, which it won't know what to do with. Maybe if the app does somehow work, it may be buggy, and/or the offline caching functionality may also be buggy.

## Outstanding Questions

Maybe an external library can help implement this? e.g: https://github.com/attaswift/BigInt

**Comment by designatednerd** [comment]
So `BigInt` would have to be set up as a [custom scalar](https://www.apollographql.com/docs/ios/fetching-queries/#notes-on-working-with-custom-scalars), since it's not a base type of GraphQL. If you use the linked library and `passthroughCustomScalars`, you should be able to use a `typealias` to convert whatever you're calling your custom scalar to that library's `BigInt`. 

Because this setup varies from server to server, this is probably not something we can support within our library directly, but as you can see, it's not awful to set it up as the client.

**Comment by designatednerd** [comment]
@joshuarobs Any further thoughts here, or do you mind if I close this out?

**Comment by joshuarobs** [comment]
@designatednerd You can close this out
