### ISSUE TITLE
Frozen UI while fetching

### ISSUE THREAD

**Issue by zebganzo** [apollographql/apollo-ios#1651]
## Bug report

I'm working on the integration of the Apollo client in our app, migrating from a networking layer that was based on "old fashion" POST requests. I'm facing some issues because the app freezes while performing fetch operations via the Apollo SDK.

## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: 0.38.3
- Xcode version: 12.4
- Swift version: Swift 5
- Package manager: CocoaPods 

## Steps to reproduce

---

## Further details

Hi Apollo team!

I'm working on the integration of the Apollo client in our app, migrating from a networking layer that was based on "old fashion" POST requests. I'm facing some issues because the app freezes while performing fetch operations via the Apollo SDK.

.Context.

Our app has to fetch from the server a few thousand elements. For several reasons, we had to split requests in bulks of 300. Thus, if the app needs to download 1500 items, it will create 5 separated requests that, afterward, will be combined together with their output.

.Gist of the technical implementations.

It's based on ReactiveSwift. Hopefully, even with little familiarity with it, this should be digestible by anyone.

```
let fetchingSignalProducers: Array<SignalProducer<[Item], NoError>> = ...

SignalProducer<[Item], RequestError>
                .combineLatest(fetchingSignalProducers)
                .map { arrayOfarrayOfItems in
                	...
                }
```

Each one of the `fetchingSignalProducers` performs a `fetch` operation, running on a dedicated queue. The code above is running on a background, dedicated queue.

.Investigation.

Digging into it, I realized that the Apollo SDK was running on the main thread. My first clue was that, while the phone was frozen, I pressed pause and checked the stack trace of the main thread. Here is a screenshot of it.

<img width="698" alt="Screenshot 2021-02-05 at 15 33 43" src="https://user-images.githubusercontent.com/3023626/107048777-9c1a7880-67c9-11eb-89ab-51208fec95a4.png">

After noticing that, I tried to follow the run of the code, checking on which thread it was running every time. I didn't manage to go through all of it, but I noticed that this method below runs on the main thread. 

```
// Apollo/Core/URLSessionClient.swift
open func urlSession(_ session: URLSession,
                       task: URLSessionTask,
                       didCompleteWithError error: Error?)
```

From the debugging, I also noticed that the UI gets stuck from the end of the first request till the end of the last one.

.Conclusion.

The code, before the integration of the Apollo SDK, was running smoothly. The UI was not freezing. My doubt is that maybe there is an ObjC dynamic dispatch that changes the thread where the code is running.

**Comment by AnthonyMDev** [comment]
Thanks for the great explanation of your issue. Are you creating your own `NetworkTransport` object, or are you just initializing the `ApolloClient` with `.init(url:)`? If you have created your own `NetworkTransport` it could be a bug there, or there might be a bug in our default `NetworkTransport` object otherwise.

**Comment by zebganzo** [comment]
Nothing fancy over here:

```
let apolloStore = ApolloStore()
let apolloInterceptor = LegacyInterceptorProvider(store: apolloStore)
let apolloNormalTransport = RequestChainNetworkTransport(interceptorProvider: apolloInterceptor, endpointURL: apolloNodeURL, additionalHeaders: self.headers, autoPersistQueries: false, requestBodyCreator: ApolloRequestBodyCreator(), useGETForQueries: false, useGETForPersistedQueryRetry: false)
let apolloWebSockets = WebSocketTransport(request: apolloSubscriptionsRequests)
let apolloNetworkTransport = SplitNetworkTransport(uploadingNetworkTransport: apolloNormalTransport, webSocketNetworkTransport: apolloWebSockets)
self.apolloClient = ApolloClient(networkTransport: apolloNetworkTransport, store: apolloStore)
```

**Comment by AnthonyMDev** [comment]
Alright, thanks for the info. I'll look into this today, but @designatednerd knows better than I do how the networking layer works right now. She's out for a few more days, so if I don't figure it out then I'll get her to look at it later this week.

**Comment by AnthonyMDev** [comment]
Can you set up a breakpoint in the `RequestChainNetworkTransport.send()` function for me and verify if that function is being called on the main thread? If `send()` is being called on a background thread, then we must be dispatching back to main accidentally somewhere. Trying to track down exactly where it moves to the main thread, so if you could help trace that back for me, it would make it easier to fix the problem. Let me know if you can find any more info for me here!

**Comment by zebganzo** [comment]
Thanks for your time, unfortunately, the difference of timezones is not making this back and forth very smooth.
It's quite a blocker for us for the next release. At the same time, it sounds like a critical bug to me.

Here you are with the screenshot of the breakpoint:

<img width="996" alt="Screenshot 2021-02-09 at 12 55 27" src="https://user-images.githubusercontent.com/3023626/107360556-67166a80-6ad6-11eb-9c60-14d10b49ec6a.png">

**Comment by zebganzo** [comment]
I think the ~~issue~~ opportunity for improvement is in the `NetworkFetchInterceptor.interceptAsync` method, which is how a `RequestChain` is moved around from intercept to intercept (if I understood correctly). The completion handler of the `self.client.sendRequest(urlRequest)` is executed in the main thread.

Digging into the `URLSessionClient` class. The `session` is initialised in this way:
```
self.session = URLSession(configuration: sessionConfiguration,
                              delegate: self,
                              delegateQueue: callbackQueue)
```

The `callbackQueue` though is never set with anything different than the default value of the `init` of the `URLSessionClient`:

```
public init(sessionConfiguration: URLSessionConfiguration = .default,
              callbackQueue: OperationQueue? = .main)
```

[several minutes later]

I can actually change the queue through the `init` of the `LegacyInterceptorProvider` in this way and it solved it!

```
let apolloInterceptor = LegacyInterceptorProvider(client: URLSessionClient(sessionConfiguration: .default, callbackQueue: aBackgroundOperationQueue), shouldInvalidateClientOnDeinit: true, store: apolloStore)
```

I tried the app and now it works smoothly. I'd still flag that the `callbackQueue: OperationQueue? = .main` of the `URLSessionClient` can be dangerous. Hopefully not so many people need to implement complex logic as the one of my app.

**Comment by zebganzo** [comment]
On the other side, the app started crashing because of memory issues (it probably touched the 2GB of memory limit).

This is the graph of the app running with the change of the code above (1,65GB):

<img width="591" alt="Screenshot 2021-02-09 at 16 26 10" src="https://user-images.githubusercontent.com/3023626/107386028-bfa83080-6af3-11eb-9295-484c6e295c91.png">

The app without those couple of lines gets to a maximum of around ~500MB, while instead, without the Apollo client at all, it was around ~120MB.

**Comment by AnthonyMDev** [comment]
I'm glad you figured it out! Sorry about the timezone difference making it difficult to work on this.

I'd like to chat with @designatednerd this week about if we want to change the default here to be a background queue. 

As for your memory issues, that is definitely an odd problem. Are you fetching a massive amount of data all at once? I can't imagine what would cause Apollo to use 500 MB of memory otherwise.

**Comment by zebganzo** [comment]
Not really. It's quite some data, but it's all JSON. And the difference between Apollo and non-Apollo is massive. I'll keep digging into it and then, in case, I'll open another ticket.

**Comment by AnthonyMDev** [comment]
Okay, would definitely want to look into this with a different ticket. If you can post some memory analysis of what objects are being allocated and talking up all that space, we can start to dig!

**Comment by designatednerd** [comment]
@zebganzo Looks like you found the place where you can set this up to call back to a background queue. Do you mind if we close this issue out? We'll keep an eye out for your other ticket.

**Comment by zebganzo** [comment]
Hi @designatednerd, absolutely, fine for me. I would anyway consider changing that default main queue.

(Kate C from Berlin says hi!)

**Comment by designatednerd** [comment]
Hi back @kcastellano!

**Comment by giantramen** [comment]
I'd second @zebganzo's
"I'd still flag that the callbackQueue: OperationQueue? = .main of the URLSessionClient can be dangerous."
Unintuitive for network logic inside libraries to default to the main thread.

**Comment by filipealva** [comment]
https://github.com/apollographql/apollo-ios/issues/1651#issuecomment-776013342


The solution on the comment above didn't solve the issue for me. 

I'm running out of options to make `RequestChainNetworkTransport` work on a background thread. 

I'm wrapping the `fetch` of a query into a DispatchQueue in background to make it work, it's not elegant at all.

**Comment by calvincestari** [comment]
Hi @filipealva, sorry to hear that solution isn't working for you. We're focused on getting to a [1.0 GA release](https://github.com/apollographql/apollo-ios/blob/main/ROADMAP.md#10---in-beta-release-phase) but we'd be happy to work with you on any PR you submit to improve the networking.

_Also worth noting that 2.0 will focus on a vastly improved networking layer._

**Comment by filipealva** [comment]
Hi @calvincestari 

Thanks for the update.

**Comment by AnthonyMDev** [comment]
Yeah, I fully agree that defaulting networking operations and processing to the `main` queue was a bad idea. We are going to revisit that when we re-write the networking layer. This feedback is valuable. Thank you!

**Comment by designatednerd** [comment]
My recollection of the way I set it up was that the network operation takes place off the main queue but you're correct, processing takes place on the main queue by default (which kind of sucks if you have large amounts of data).

**Comment by petarbelokonski** [comment]
So coming to this as well myself. Just realised Apollo handles everything on the caller's thread. Wondering why was the API designed this way ? If I am to supply a queue on which the result to be returned that would usually mean that whatever execution is taking place in the called method it will be on a dedicated background thread. That's how usually APIs of the kind work. Now I see no point of really having this parameter since the execution of the fetch method will be handled on the whatever queue it was called from.

**Comment by calvincestari** [comment]
The queue used is configurable all the way from the client through to the `URLSession` delegate callbacks. Figuring out how to do that is not very well documented though. As you've seen you are able to [provide a queue to the `fetch` function](https://github.com/apollographql/apollo-ios/blob/main/Sources/Apollo/ApolloClient.swift#L83) but as you've also noted that is only used in the callback to your completion handler. The real culprit for having network data processing on the main queue is in [`URLSessionClient` where the default queue is specified to be `main`](https://github.com/apollographql/apollo-ios/blob/main/Sources/Apollo/URLSessionClient.swift#L65).

Below is sample code demonstrating how you can change that so network data processing happens on a background queue. Building the client this way will give you the same network transport and interceptor chain as the default implementation, if you have custom changes to those you will need to apply them as needed.
```
// Specifying `nil` for the `callbackQueue` is what allows `URLSession` to use it's default
// behaviour of a background queue for network delegate calls. Or specify any serial queue
// that you use for network data processing.
let sessionClient = URLSessionClient(sessionConfiguration: .default, callbackQueue: nil)
let apolloStore = ApolloStore(cache: InMemoryNormalizedCache())
let interceptorProvider = DefaultInterceptorProvider(client: sessionClient, store: apolloStore)
let url = URL(string: "http://localhost:4000/")!
let networkTransport = RequestChainNetworkTransport(interceptorProvider: interceptorProvider, endpointURL: url)
let client = ApolloClient(networkTransport: networkTransport, store: apolloStore)

client.fetch(query: ExampleQuery()) { result in
  ..
}
```

The network API design pre-dates any of us currently on the Apollo iOS team; I don't say that to disparage the prior work but to simply state that it is what it is. Six lines of code to specify a `nil` queue and get back default `URLSession` behaviour is absurd, we understand that. We've discussed changing the `URLSessionClient` initializer default to be `nil` instead of `main` but felt that it could have a major negative impact to apps that are unaware of the change and are unknowingly working with UI in callbacks that currently get called on the main thread. That is why we have major version 2.0 on our roadmap to address the entire networking layer/API in Apollo iOS; we're all quite passionate about making that a major improvement to meet modern expectations.

**Comment by petarbelokonski** [comment]
Thanks @calvincestari for the explanation. My comment was not correct where I said all is handled on the caller's thread but in fact called explicitly on the queue specified in the URLSessionClient's init which happens to be the main queue.
