### ISSUE TITLE
 graphQL response omits returning field causes missingValue error

### ISSUE THREAD

**Issue by qwkuah** [apollographql/apollo-ios#1668]
My graphql schema has a field which is nullable
transactionList: [Transaction!]

however when the graphql server omits "transactionList" field from the response, i get missingValue error.

From researching, it seems like omitting fields where fields are nullable is possible in graphql. Rightfully it should default to null. https://stackoverflow.com/questions/54977637/is-it-ok-to-omit-returning-fields-instead-of-null-for-nullable-fields-in-graphq

My question is, is Apollo unable to parse nullable fields which are not sent back in the response? Or is it a config issue on my end? Thanks.

Apollo version 0.38.0

**Comment by designatednerd** [comment]
Poking around a bit in the code, it looks like parsing for iOS is set up so that you do have to explicitly pass `null` back rather than just omitting the field. 

One thing to be aware of with using GraphQL with code generation into a type safe language in general is that there are a number of things that are perfectly legal GraphQL, but are very, very difficult to represent in a type-safe fashion. 

In theory this particular instance shouldn't be _that_ difficult, but if there's one thing I've found dealing with codegen is a lot of things which seem like they wouldn't be that difficult are, in fact, rather obnoxiously difficult.

**Comment by designatednerd** [comment]
@qwkuah Did that answer help you out? If it didn't, let me know - otherwise I'll probably close this out. Thank you!

**Comment by AnthonyMDev** [comment]
The answer to that StackOverflow question is incorrect.

As per [the spec](https://spec.graphql.org/June2018/#sec-Executing-Selection-Sets), during GraphQL execution each field is expected to have it's executed value added to the result map for the response key. If a field fails to resolve with an error, the field should be included with a `null` value. If the field executes to a `null` value, the field should be included with a `null` value. There is no valid response format in which a nullable field that is selected by the operation's selection set is allowed to be omitted. The behavior of Apollo iOS in returning a `missingValue` error is correct, as your server has provided an invalid (ie. non-spec compliant) GraphQL response.
