### ISSUE TITLE
Crash by parallel requests URLSessionClient.swift

### ISSUE THREAD

**Issue by IllyaKrit** [apollographql/apollo-ios#1739]
Hi, if I start more than one requests with Apollo version 0.42, I get the error:
Fatal error: No data found for task 1, cannot append received data: file Apollo/URLSessionClient.swift, line 263

by Version 0.40 the same error but on line 258.

It is working nice with one request. Looks like problem is by Atomic.swift  public func mutate(block: (inout T)

**Comment by designatednerd** [comment]
Hi Ilya, the error you're hitting is an `assertionFailure` rather than a `fatalError`, which should only ever happen in debug mode. It wouldn't be caused _by_ `mutate`, it's being caused _within_  the `mutate` closure, which is why you're seeing that in the stack trace. 

 Can you please share more detail about what's happening here? To start with: 

- Can you share the full stack trace? 
- Are these requests made in very close (less than a second) succession, or is this any time you do more than one task? 
- Is this manifesting both on sim and device, or on one or the other? 
- What is the `state` of the `dataTask` when the assertion failure is hit (only in v.0.42.0, since there we've added a gate to check if it's being cancelled so we know that's not the state)?
- Is there a specific version of iOS you're seeing this issue on?

**Comment by designatednerd** [comment]
Hi Ilya, were you able to figure out what the issue was or is there any way we can help? If I don't hear back by the end of next week, I'll close this out.

**Comment by IllyaKrit** [comment]
Hi Ellen, 
you can close the issue. I had a bug in my app. The app did send too many of the same apollo requests. 
So, I think it is not relevant as issue for the apollo framework. 
Thank you for fast response!
