### ISSUE TITLE
Open up `ApolloClient` for subclassing

### ISSUE THREAD

**Issue by antranapp** [apollographql/apollo-ios#1756]
## Feature request

Open up `ApolloClient` for subclassing

## Motivation

I want to create some stored properties for my custom internal logic inside `ApolloClient`. One way to do that is to create an Adapter 

```
class NewApolloClient: ApolloClientProtocol {
   let customProperty: SomeType
   let internalClient: ApolloClient
   .....
}
```

but if the `ApolloClient` is open, I can just subclass it 

```
class NewApolloClient: ApolloClient {
   let customProperty: SomeType
   .....
}
```

**Comment by designatednerd** [comment]
Hi! We generally suggest the first approach if you absolutely need to store things at the `ApolloClient` level.

`ApolloClient` may not always be the correct level to store pieces of information at, though - I would look at whether what you want to store can be stored at the `NetworkTransport` level instead in particular, since `RequestChainNetworkTransport` _is_ designed to be subclassed. 

Does that help?

**Comment by antranapp** [comment]
Oh, It's good to know that `RequestChainNetworkTransport` can be subclassed. I'll try to go this path then.
