### ISSUE TITLE
Watchers aren't triggered when updating an object after its cache key has changed

### ISSUE THREAD

**Issue by leevida** [apollographql/apollo-ios#1794]
## Versions

Please fill in the versions you're currently using:

- `apollo-ios` SDK version: `0.35.0`
- Xcode version: `12.4`
- Swift version: `5`
- Package manager: CocaPods

## Steps to reproduce
We have an object, `Foobar`
1. Define cache key for Foobar in `apollo.cacheKeyForObject`
2. Subscribe to a watcher for a query that includes Foobar: `apollo.watch()`
3. Make an update to Foobar in the cache that would change its calculated cache key: `store.withinReadWriteTransaction()`

The watcher correctly emits data with the updated Foobar

4. The cache still seems to reference Foobar with the original cache key. Using the old cache key, update Foobar again: `store.withinReadWriteTransaction()`

This time, the watcher doesn't emit data with the updated Foobar. Only if an update is made to other data that the watcher references does the watcher emit with the updated Foobar.

Expected outcome:
The watcher emits an event when the object updates, even if its cache key has changed

## Further details
I suppose ideally the cache key is stable and never changes, but, in the case that it does, it would be nice if the watcher still worked. It kind of works because it updates the object after a different object related to the query is updated.

**Comment by AnthonyMDev** [comment]
Sorry it took me some time to get to this one! 

Hmmm, I agree that cache keys should be stable and never change. I'm not sure if I'm understanding correctly, but it seems like this is working as intended.

If you change the cache key of an object, and then update the object using its old cache key, the watcher would now be watching the object with the _new_ cache key in the cache. It shouldn't receive updates for an object with the old cache key, since it's not watching that object anymore. Updating the object with the old cache key should create a new record for another object in the cache with that cache key now.

It sounds like you might be calculating the cache key using fields that change? That is not a supported behavior. The cache key should represent a unique identifier of some sort for an entity that is stable. A different cache key signifies that it is an entirely different entity, not a mutation of an existing entity.

Can you give some more information about your use case and how you are computing the cache key?

**Comment by designatednerd** [comment]
@leevida Can you share some more detail please?

**Comment by leevida** [comment]
@AnthonyMDev @designatednerd We're computing the cache key with a URN field, but we're updating that URN field when calling `store.withinReadWriteTransaction()`.
I can still update the object again using the old URN when calling `store.withinReadWriteTransaction()`, which is nice that it works. The problem is any watchers for changes to this object using `apollo.watch()` are not notified of the updated object.
Agreed that the cache keys should be stable, but unfortunately, with the APIs we're working with the cache keys are not. So hoping there's a little more support for this case. Like somehow if the watchers could keep using the old key.

**Comment by AnthonyMDev** [comment]
Cache keys should not be computed based on fields that are not stable. They are intended to be stable, and removing that assumption would cause a domino effect of other implications. For a normalized cache, normalized objects need a stable cache key.

I don't intend to add additional support for any assumptions of non-stable cache keys in the future. If the fields being used to compute your URN is not stable, I'd suggest you move to using something else for your cache keys. Maybe you could use a UUID, or you can add a canonical id field to your objects on the server side.
