### ISSUE TITLE
schema.json not updated when GraphQL server schema is changed

### ISSUE THREAD

**Issue by conradwt** [apollographql/apollo-ios#1814]
## Bug report

The `schema.json` isn't updated when changing GraphQL `schema` on the server.  Is `swift run ApolloCodegen downloadSchema` required as part of the **run script** definition for Xcode 12.5 because the schema.json file isn’t being updated?

## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: 0.42.0
- Xcode version: 12.5
- Swift version: 5.4
- Package manager: ??

## Steps to reproduce

1. setup and configure Swift code generation
2. add one or more fields to a GraphQL type on your server
3. In Xcode, update the GraphQL operations
3. In Xcode, Command + B

**Comment by AnthonyMDev** [comment]
When the schema changes on the server, you'll need to re-download it (and probably re-run code generation afterwards). You can do that in your run script, but since it usually isn't changing that frequently, I'd recommend you just run a schema download when you know you have updates you need to pull, or on some periodic basis.

**Comment by designatednerd** [comment]
@conradwt is there anything else we can help you with here? I'm going to be doing a pass through all the docs soon and I've got this noted as something to clarify.

**Comment by conradwt** [comment]
@designatednerd Yes, this issue has been resolved and this issue can be closed.
