### ISSUE TITLE
Doesn't support a fragment with the same name of its type

### ISSUE THREAD

**Issue by filipealva** [apollographql/apollo-ios#184]
As we've discovered discussing in Apollo Slack, If I create a fragment with the same name of its type as the following:

```graphql
fragment Center on Center {
  _id
  name
}
```

Everytime we call it from a query the query returns a `QueryName.Data.Center` type, even if we `map` and access it through the `.fragments.center` property of each result item.

![screen shot 2017-11-21 at 14 01 05](https://user-images.githubusercontent.com/6117280/33088961-63dc8eac-ced6-11e7-924f-56e5b9297324.png)

**Comment by filipealva** [comment]
@martijnwalraven any thoughts on where the cause of this issue can be? I mean, it is a `apollo-ios` issue or maybe the `apollo-codegen` is causing it?

I'm trying to figure out to see if I can contribute fixing it up, but I'm a little lost on the project :P if you can provide any info for me to track this bug it would be very helpful.

**Comment by martijnwalraven** [comment]
The problem is not actually the fragment name being the same as the name of the type it is defined on, but the name of the query field being the same. In the generated code, we expect `Center` to refer to the fragment struct, but because `AllCentersQuery.Data.Center` is in scope, our reference is interpreted as that type instead. 

So we need to disambiguate the fragments struct reference in the generated code. The relevant `apollo-codegen` code is [here](https://github.com/apollographql/apollo-codegen/blob/bb604db1531a50d5f55235e8a56e73ddf325b8a5/src/swift/codeGeneration.ts#L366-L390).

**Comment by zdesiree** [comment]
With migrating our project to Apollo 1.x, this topic of naming the fragment the same as it's type came up again, but with a different problem. It results in a duplicated file name because of the Schema/Objects contains the same file name as the Fragments folder.
Is there any option to work around this, e.g. defining a prefixing for the file names only? So I don't have to rename all my fragments.

**Comment by calvincestari** [comment]
@zdesiree - you can subscribe to https://github.com/apollographql/apollo-ios/issues/2598 for updates to the same issue that we're tracking in 1.0 releases.
