### ISSUE TITLE
Undefined symbol: __swift_FORCE_LOAD_$_XCTestSwiftSupport

### ISSUE THREAD

**Issue by neha275** [apollographql/apollo-ios#1952]
## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: 0.3.0
- Xcode version:  Xcode 13
- Swift version: 5.5.0
- Package manager: Swift Package manager

## Steps to reproduce

update the Xcode then error occurred

## Further details
![Screenshot 2021-09-22 at 10 35 48 AM](https://user-images.githubusercontent.com/26864742/134286409-d4a7e0ff-7707-4ba5-aa43-302bbcb4159e.png)

This issue fixed by the repository but we are not able to point that 
for reference check https://github.com/kylef/Spectre/releases

Apollo is using the dependance package called Stencil, is a root caused
.package(
      url: "https://github.com/stencilproject/Stencil.git",
      .upToNextMinor(from: "0.14.0")),

**Comment by calvincestari** [comment]
@neha275, I think this is [another Xcode 13 problem](https://github.com/apollographql/apollo-ios/issues/1951) caused by defaulting to use version `0.3.0` of apollo-ios. If you update the dependency versioning to use a base version of `0.49.0` the error should be resolved.

<img width="459" alt="Screen Shot 2021-09-22 at 1 31 23 PM" src="https://user-images.githubusercontent.com/146856/134422078-a6cbb715-f753-43f4-87dd-cc06f838686f.png">
