### ISSUE TITLE
Watch a record

### ISSUE THREAD

**Issue by oney** [apollographql/apollo-ios#196]
It seems that I can only watch a Query. Can I watch a record by cache key?
My scenario is I fetch a list of data by query, and I just want to watch one of records. When the record changes, watcher will be called.
Thanks!

**Comment by designatednerd** [comment]
This is a bit against the design of the `watch` feature, which is supposed to let you not care which records are updated, but just allow you to receive updates on all updated records on that query. 

I'm going to close this out since I'm trying to keep the GH issues to more behavior problems with the SDK, but please feel free to check in with our [Spectrum Chat](https://spectrum.chat/apollo/apollo-ios?tab=posts) if you have any further questions!
