### ISSUE TITLE
Unexpected cache fail.

### ISSUE THREAD

**Issue by Gerrel** [apollographql/apollo-ios#201]
I've the follow schema on my server:

```
type Company {
  id: Int!
  name: String
  votes: Int
  contacts: [String]
  color: String
}

# the schema allows the following query:
type Query {
  companies: [Company]
  company(id: Int!): Company
}

# this schema allows the following mutation:
type Mutation {
  upvoteCompany (
    companyId: Int!
  ): Company
}

type Subscription {
  companyUpvoted: Company
}

schema {
	query: Query
	mutation: Mutation
	subscription: Subscription
}
```

And the following queries in my iOS app using apollo-ios-client 0.7.0 and apollo-codegen 0.17.1:

```
query companies {
  companies {
     ...CompanyDetails
  }
}

fragment CompanyDetails on Company {
    id
    name
    votes
    contacts
    color
}

query company($id: Int!) {
    company(id: $id) {
        ...CompanyDetails
    }
}

mutation upvoteCompany($companyId: Int!) {
    upvoteCompany(companyId: $companyId) {
        ...CompanyDetails
    }
}
```

and set:
`apiClient.cacheKeyForObject = { $0["id"] }`

When I run the "companies" query I get the results and they are cached.
Then I turn off my internet and run the "company($id: Int!)" query after selecting the company in the tableview, but I'm not getting the cached result of the "companies" query.

How come?

**Comment by martijnwalraven** [comment]
That's actually expected behavior, but I can see how it is confusing, and I would like to improve it.

To understand what is going on, consider a field like `mostPopularCompany: Company`. There is no way for a GraphQL client to know what that will return without sending a query to the server. So even if the most popular company has already been cached, we can't run the query offline.

Similarly, looking purely at the schema, there is no way for the client to know what `company(id: Int!): Company` returns. It seems obvious for us that it will return a company with the passed in id and that we could load it from cache, but from the perspective of GraphQL `company(id: Int!)` is just another field that runs an arbitrary resolver on your server.

So we will need to give the client more information if we want to allow loading a query like this from cache. We have a few different solutions in mind (custom client-side resolvers or directives that guarantee the contract), but for now the best workaround would be to load the query directly from cache.

Something like:
```swift
let company = client.withinReadTransaction { transaction in
  transaction.readObject(ofType: CompanyDetails.self, withKey: id)
}
```

**Comment by Gerrel** [comment]
Makes sense, thanks for this great explanation and workaround!
