### ISSUE TITLE
Access control on `ApolloClient`'s `networkTransport` property

### ISSUE THREAD

**Issue by attheodo** [apollographql/apollo-ios#207]
Hey,

I am trying to put together a micro framework for easily stubbing Apollo operations. Ideally I'd like `GraphQLOperation`s to somehow carry semantics of their associated `URLRequest` but obviously this is way off Apollo's current architecture. As a fallback, I think the stub matcher method could get passed the whole `ApolloClient` object which carries the `networkTransport` object, but it is implicitly declared as `internal` so I cannot access it outside the module. Subsequently for the `url` and `session` properties of `HTTPNetworkTransport`.

I am wondering whether you can expose the network transport as `public` in a beta version any time soon? Or maybe you have some other suggestion on how to get the associated `URLRequest` of each operation?

Thanks!

**Comment by martijnwalraven** [comment]
Could you elaborate on what you are trying to accomplish? How would you want stubbing of operations to work?

I'm a little wary of exposing `networkTransport`, because we're in the process of changing the network stack to be more composable. I'm also wondering if that would help you. There is no guarantee there is a one to one correspondence with an HTTP request, and you may not even be using HTTP. So it feels like the wrong level of abstraction to build stubbing on.

**Comment by attheodo** [comment]
@martijnwalraven thanks for your reply, appreciate it. 

So at this point I am just looking to stub operations in the most "quick-n-dirty" way. I am evaluating the possibility of building a custom matching function for Mockingjay which pretty much works under the hood like [this](https://github.com/kylef/Mockingjay/blob/master/ARCHITECTURE.md). 

The way I am planning this right now is to have a stub matching function like this
`public func graphQLOperation<T: GraphQLOperation>(_ operation: T.Type, apolloClient: ApolloClient) -> (_ request: URLRequest) -> Bool` and have `Mockingjay` cross-check that apollo's url matches the underlying request's one and then use some sort of regex to check that the operation's `operationString` is present in the `httpBody`. Consequently if that matching function evaluates to `true`, I'll have a builder function for `Mockingjay` to relay the appropriate JSON fixture to Apollo to be deserialized.

Why are you mentioning?
> you may not be using HTTP

**Comment by martijnwalraven** [comment]
That seems a bit convoluted to me. I think the simplest way to mock GraphQL requests would be to use a mock network transport. We use [a very basic version](https://github.com/apollographql/apollo-ios/blob/master/Tests/ApolloTestSupport/MockNetworkTransport.swift) of that in the Apollo iOS tests. It only supports one mock response, but you could easily extend it to take a map of responses or load JSON fixtures.

**Comment by martijnwalraven** [comment]
> you may not be using HTTP

The GraphQL spec does not specify a network transport, which is why we don't want the API to depend on HTTP. We're in the process of adding support for the WebSocket transport for example, which supports subscriptions in addition to queries and mutations (although you may choose to split things up and continue to use HTTP for those).

**Comment by attheodo** [comment]
@martijnwalraven thanks for your response. I really liked the simplicity of passing over a mock network transport, but this by definition is not a stub. Ideally we'd like a way to stub the operations without configuring the Apollo client in any other way other than the production one. And just have the subsystem stub the requests and return the fixtures. I think we can deal with a mock solution for now.
