### ISSUE TITLE
Is it possible to generate multiple API files

### ISSUE THREAD

**Issue by hazzaldo** [apollographql/apollo-ios#215]
Hi,

I was wondering, from an architectural point of view, and especially for large scale apps, it's ideal to be able split the API.swift file into smaller Swift files, say based on different scenes or domain logics/business logics (such as with clean architecture). Otherwise you would have one gigantic API file. Is it possible to customise the creation of different API files?

Many thanks in advance,

**Comment by hazzaldo** [comment]
Apologies, this was meant to be submitted to the Apollo graphQL client.

**Comment by martijnwalraven** [comment]
@hazzaldo I'm a little confused now, because this is the repository for the Apollo GraphQL iOS client and that's what your questions seems to be about!

To answer your question, there is currently an experimental option to generate single files, but it is very clunky and still needs all files as input for every file it generates. It was meant to be integrated with Xcode but I never got that working (it was based on undocumented features of Xcode).

Is your reason for wanting a single file architectural or are you experiencing performance issues with the single `API.swift`?

**Comment by hazzaldo** [comment]
Hi @martijnwalraven , please ignore reason for closing the thread. I made a mistake and thought I was submitting the issue on GraphQL repo rather than Apollo (i.e. on the wrong repo). 

So my intention was, to split the one API file into smaller files according to different scenes or different business cases / business logic / domain logic. Especially having a large scale app, to have all APIs on one single gigantic file just doesn't seem conforming to good design architecture, such as Clean Architecture principles such as SOLID, among other patterns. What do you think?

**Comment by hazzaldo** [comment]
Hi, 
Just wondering if anyone has any suggestions for this? 

Many thanks
