### ISSUE TITLE
[CodeGen] Invalid redeclaration of 'data'

### ISSUE THREAD

**Issue by hmaks36** [apollographql/apollo-ios#2183]
Using 1.0.0alpha2 with ApolloCodeGen

Whenever my .graphql models contains à field named "data" there is a naming conflict in generated code for data of 
protocol conformance to InputObject or SelectionSet

How can i avoid that ?

**Comment by AnthonyMDev** [comment]
Thanks for the feedback! I had thought about this a while back. 

I'm going back and forth on how we should handle this. 
1. We can namespace all of our fields (eg. `_apollo_data`). 
2. Or we can say that certain keywords like `data`, `selections`, and `fragments` are reserved.

Option 1 makes our generated code a bit uglier, which isn't a huge deal. But more importantly, it doesn't solve the issue of `fragments`. Because that property is something public that the consumer is going to want to call into.

If we went with option 2, the solution is to require you to alias those fields in your operations. Not ideal, but easy and clean. We would just add to the codegen engine a check for a list of reserved words and give you an error telling you to alias fields with reserved names.

@calvincestari What are your thoughts on this? Any other approaches that seem viable? 

We could look into using `ApolloExtension`, but I'm not sure about the viability of that or the performance implications. I know that it won't work properly with anything using generics, not sure if that's an issue without trying it, but it likely would be, as `SelectionSet` is a protocol with an `associatedtype`.

@martinbonnin Have you encountered an issue like this with your codegen?

**Comment by calvincestari** [comment]
I think it would be OK to reserve some of those, such as "selections" and "fragments" but I think "data" might be too commonly used to be a reserved word.

I'm not against namespacing "data" but I think it should be something simpler like `_data` or `underlyingData`. Maybe we go back to `dataDict`?

**Comment by AnthonyMDev** [comment]
I think the best thing to do here is to rename `data` on `SelectionSet` and `InputObject` to `_data`. Going to get this done ASAP.

**Comment by AnthonyMDev** [comment]
`selections` and `fragments` should be reserved words that cause code generations to fail if used as field names.
