### ISSUE TITLE
SSL Pinning for WebSocketTransport

### ISSUE THREAD

**Issue by piemonte** [apollographql/apollo-ios#2222]
Hello, first off, amazing project and community. Have used it for a ton of projects.

So I'm currently handling SSL pinning for our requests using a `URLSessionClient` subclass that overrides

`override public func urlSession(_ session: URLSession,
                                    didReceive challenge: URLAuthenticationChallenge,
                                    completionHandler: ((URLSession.AuthChallengeDisposition, URLCredential?) -> Void)?)`

My question is... how can I also use pinning for socket connections?

My `URLSessionClient` above is a parameter to an `InterceptorProvider` used by the `RequestChainNetworkTransport` but how can I do this with a `WebSocketTransport`, is that even a possibility or is this a feature request?

**Comment by calvincestari** [comment]
Hi @piemonte 👋🏻 - I don't have a good answer for you because I've never tried to do this before. apollo-ios uses Starscream internally so it'd need to be something done via that library. I had a quick look on the Starscream repo and found [this issue](https://github.com/daltoniam/Starscream/issues/732); whether it helps you I'm not sure.

**Comment by piemonte** [comment]
Ah, nice. @calvincestari thanks for taking the time to find this and point me in the right direction. If I come up with a solution, will share it here and/or make a suggestion if there's something Apollo can add too.
