### ISSUE TITLE
Readme isn't loading in Xcode when installing swift package

### ISSUE THREAD

**Issue by jpvajda** [apollographql/apollo-ios#2252]
### Steps to reproduce

Follow the installation [iOS instructions found here](https://www.apollographql.com/docs/ios/installation) and chose the swift package manager install. when viewing the apollo-ios readme, notice it doesn't load.

### Screen shot

![Screen Shot 2022-04-18 at 6 37 43 PM](https://user-images.githubusercontent.com/1395158/164035605-3b153a1c-4204-4ab8-9fcc-9fccb3fedd91.png)

### Expected

Readme loads and is viewable.

**Comment by adil-hussain-84** [comment]
Why was this issue closed? I still see the "Unable to load the Read Me" text for this package in the "Add Package" window in Xcode.

**Comment by calvincestari** [comment]
What version of Xcode are you using and which version of apollo-ios are you targetting? I cannot replicate this issue, the README content displays as expected.

**Comment by calvincestari** [comment]
When you search for the apollo-ios repo to add what version does Xcode automatically target? I've seen that before the 1.0.0 release it would automatically select 0.9.0 instead of 0.53.0. I wonder if this is a similarly related Xcode bug?

**Comment by AnthonyMDev** [comment]
I'm just not sure what we can do to fix this, or even debug it... It's likely this is an Xcode bug.

**Comment by adil-hussain-84** [comment]
Thanks for the responses 👍 I was just curious as to whether somebody has found the root cause of this issue and a workaround because I'm experiencing it for a Swift package that I've published. I'm experiencing it for the `apollo-ios` package as well. See screenshot below. I'm experiencing this issue in Xcode versions 13.4.1 and 14.0.1.

<img width="1035" alt="Xcode Add Package Dependency Screenshot" src="https://user-images.githubusercontent.com/17025131/197069504-50e45a67-e147-4319-9d41-b85441d8d1e9.png">

[This](https://developer.apple.com/forums/thread/716672) Apple Developer Forums' thread describes the problem nicely. Sadly, that thread has plenty of upvotes but no answers.

**Comment by calvincestari** [comment]
I don't have any idea why this is happening unfortunately.

**Comment by kibotu** [comment]
```
It's really as simple and dumb as that.

While the package manager finds and loads your package just fine from private repos, the element displaying the repo operates under the assumption that the README can be read without authentication.
```

**Comment by calvincestari** [comment]
@kibotu that would be understandable if apollo-ios were a private repo, but it's not. You wouldn't be able to post a comment here if it were.
