### ISSUE TITLE
Case sensitive in enum 

### ISSUE THREAD

**Issue by Carlos-Barron** [apollographql/apollo-ios#2326]
## Bug report
When you have similar enum cases for lowercase and uppercase with the same name, it will turn it into lowercase and it will generate an error in the compiler. This only happens when you have an a enum to map with the same names but different cases.

## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: apollo/2.32.1
- Xcode version: 13.1 
- Swift version: 5
- Package manager: - 

## Steps to reproduce
You only need a schema that has similar enum cases with lowercase & uppercase. It will autogenerates code into lowercases & generating a compiler error.
<img width="1109" alt="Screen Shot 2022-06-22 at 13 29 30" src="https://user-images.githubusercontent.com/73896732/175110937-f948073d-457c-48ea-b07a-215ae3638293.png">

**Comment by calvincestari** [comment]
Hi @Carlos-Barron - this is on the current `main` version right, `0.52.1`? v1.0, which is currently in alpha releases, won't have this same bug; there is [specifically a test to cover this case](https://github.com/apollographql/apollo-ios/blob/release/1.0/Tests/ApolloCodegenTests/CodeGeneration/Templates/EnumTemplateTests.swift#L106). Unfortunately that means this won't be getting fixed in the `main` branch.

**Comment by Carlos-Barron** [comment]
Got it! 
Is there some workaround that I can use?
