### ISSUE TITLE
Only write modified files during codegen

### ISSUE THREAD

**Issue by hiltonc** [apollographql/apollo-ios#2347]
## Feature request

When doing codegen only modify files whose contents have changed.

## Motivation

This allows Xcode to skip compilation of unchanged generated code. This is quite noticeable in Xcode 14 beta with the build timeline.

## Proposed solution

1. Generate each file as a string
2. Load the contents of the existing file (or "" if it doesn't exist)
3. Compare and write the file only if it is different
4. Track all the files that are generated
5. At the end delete any files from the directory that should no longer be there

Could make doing this a configuration argument.

**Comment by calvincestari** [comment]
Hi @hiltonc we intend to solve this problem in a 1.x release - the existing behaviour won't be changed in the current 0.x releases though. We're about to enter the Beta release phase for 1.0, please check it out, we'd love to get your feedback on it.

A current workaround is to use Xcode's Input File List for custom build scripts, which lets Xcode determine when to run the custom build script, i.e.: when to run code generation. We understand this isn't a great solution which is why we intend to change this in the future.
