### ISSUE TITLE
Swift Codegen tool incorrectly generating optional field with optional Enum type

### ISSUE THREAD

**Issue by PatrickDanino** [apollographql/apollo-ios#2461]
## Bug report

When the Swift codegen tool is generating Swift code from a query which takes as input a type with optional fields of an Enum type, it appears to generate code that has double optionals - one for the field itself and one for the field's Enum type.

## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: 2.33.9
- Xcode version:  13.4.1
- Swift version: 5
- Package manager:

## Steps to reproduce

- Define an input type that has one or more optional enum fields
- Run the Swift codegen tool

EXPECTED: The Swift code generated should be a struct with an optional field that is of the Enum type
CURRENT: The Swift code generated has an optional field that is of an optional Enum type

## Further details

Schema example:

```
enum Age {
  AGE_UNDER_30
  AGE_30_OVER
}

type Demographic {
  age: Age
}

type DemographicData {
  population: Int!
  demographic: Demographic!
}

input DemographicInput {
  demographic: Demographic
} 

type Query {
  demographicData(filter: DemographicInput!): DemographicData
}
```

You would expect `DemographicInput.Demographic` to have fields that match `DemographicData.Demographic`, but they don't. The codegen tool generates an optional of an optional type for the former, which looks something like this:

```
public struct DemographicFilter: GraphQLMapConvertible {
  ...
  public var age: Swift.Optional<Age?> {
    ...
  }
}
```

Instead, it should generate something like this:

```
public struct DemographicFilter: GraphQLMapConvertible {
  ...
  public var age: Swift.Optional<Age> {
    ...
  }
}
```

**Comment by AnthonyMDev** [comment]
This is actually working as intended. The double optional thing is not very intuitive, but it is because there is a difference between omitting an input field and sending a `null` value in GraphQL. `age = nil` will omit the field from the request, `age = .none` (an empty optional) will send the field with a `null` value.

In the 1.0 version which is in beta and very near completion, we improve upon this with a type called `GraphQLNullable` to replace the double optional. I suggest you take a look at our 1.0 beta releases!
