### ISSUE TITLE
Warning: apollo update available from 2.33.9 to 2.34.0. 

### ISSUE THREAD

**Issue by sinkcup** [apollographql/apollo-ios#2471]
## Bug report

Xcode build Warning: apollo update available from 2.33.9 to 2.34.0. 

If I edit `ApolloCodegen/.build/checkouts/apollo-ios/Sources/ApolloCodegenLib/CLIDownloader.swift`, change `2.33.9` to `2.34.0`, it will error: 404 not found

<img width="922" alt="image" src="https://user-images.githubusercontent.com/4971414/187192831-bdbfbbd7-8c21-41f4-87d5-64be8dc5828d.png">

## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: 0.53.0
- Xcode version: 13.4.1
- Swift version: swift-driver version: 1.45.2 Apple Swift version 5.6.1 (swiftlang-5.6.0.323.66 clang-1316.0.20.12)
- Package manager: don't known

## Steps to reproduce

1. follow the 0.x docs https://www.apollographql.com/docs/ios/swift-scripting/
2. git clone https://github.com/apollographql/iOSCodegenTemplate
3. Xcode build

**Comment by calvincestari** [comment]
Hi @sinkcup - the warning about an updated version is not a bug. Looking at the [changelog for apollo-tooling](https://github.com/apollographql/apollo-tooling/blob/master/CHANGELOG.md), none of the updated versions are for bug fixes only dependencies.

The reason your script is failing is because of the error "Apollo does not support anonymous operations". Once you fix that your build phase should work as expected.
