### ISSUE TITLE
Can not write Fragment into ReadWriteTransaction#updateObject closure

### ISSUE THREAD

**Issue by bannzai** [apollographql/apollo-ios#2481]
## Bug report

I want to use [ReadWriteTransaction#updateObject](https://github.com/apollographql/apollo-ios/blob/release/1.0/Sources/Apollo/ApolloStore.swift#L267) and update cache data into transaction last argument closure named `body`. However, can not update `object` into closure whe I got compile error `Cannot assign to property: 'PROPERTY' is a get-only property`. So, generated `SelectionSet` implementation properties are all readonly property.

I guess to change access control and preparing setter to all property.

## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version:beta-3
- Xcode version: 13.4.1
- Swift version: 5.6
- Package manager: 5.

## Steps to reproduce
Exec codegen and confirm generated Swift `SelectionSet` implementation type. And call `ReadWriteTransaction#updateObject` and write updating code for `object` instance into body. After, you get error for `Cannot assign to property: 'PROPERTY' is a get-only property`.

## Further details

Please replace this line with any further details or context necessary to understand the problem. Delete this section if you don't have anything further to add.

**Comment by AnthonyMDev** [comment]
Good news, there is a way to do this! It's just not documented yet. We're in the process of writing all the documentation and usage guides for the 1.0 version still, so by the time we make it out of Beta, there will be better guidance on how to make this work.

Making the generated selection sets mutable was pretty complicated, and added a lot of generated code and negative performance impact. Since the large majority of operations and fields within them aren't going to be used with the local cache updates, we decided to make selection sets mutable in a tightly scoped and opt-in manner.

Adding the directive `@apollo_client_ios_localCacheMutation` to a GraphQL operation causes the code generation engine to generate it as a Local Cache Mutation instead of a regular Query operation. This makes it a `MutableSelectionSet` instead of `SelectionSet` (the `updateObject()` you linked above and related method require `MutableSelectionSet`). It also generates all the necessary getters and setters for you!

It's important to note that when using this directive, the operation is no longer a `GraphQLQueryOperation` that can be used with `apolloClient.fetch()`. **It is only able to be used for making updates in a local cache mutation.** The intention here was that you should define local cache mutations that only include the fields that you actually need to mutate. You should have separate queries from your local cache mutations.

This should allow you to achieve everything you are intending to here. If this API is not adequate for your use case, let us know why and we can discuss how to improve!

And as I said, we know this is not reasonable functionality to discover on your own right now. The documentation is going to be very clear and discoverable around this before the official release!
