### ISSUE TITLE
GraphQLNullable: Convenience initializer for optionals

### ISSUE THREAD

**Issue by cshadek** [apollographql/apollo-ios#2483]
## Feature request

It would be nice to have a convenience initializer for `GraphQLNullable` for optionals.

## Motivation

GraphQLNullable has the following cases:
```
  case none
  case null
  case some(Wrapped)
```
But if we have an optional variable (`String?`, etc) and want to just use it as an input parameter, it would be nice for either another case or convenience initializer.

## Proposed solution

I would propose the following convenience initializer for a more succinct way to use optional variables.  I figured that using a default nil value as `.none` may be more useful than `.null`.

```
public extension GraphQLNullable {
    init(_ wrapped: Wrapped?, as nullType: GraphQLNullable = .none) {
        if let wrapped = wrapped {
            self = .some(wrapped)
        } else {
            self = nullType
        }
    }
}
```

## Other Solutions

I considered other options like individual initializers for both `.null` and `.none`.  The approach above may be better because it gives more control to the developer. 

```
public extension GraphQLNullable {
    init(_ wrapped: Wrapped?) {
        if let wrapped = wrapped {
            self = .some(wrapped)
        } else {
            self = .none
        }
    }
}
```

The idea behind this request is to make code more succinct when using optionals.

**Comment by AnthonyMDev** [comment]
We've had a lot of conversations about this internally. We recognize that `GraphQLNullable` adds an additional usage barrier, but it's intentionally there to force users to make a decision about if they want to fall back on `null` or `nil`.

Providing an initializer that defaults to either one of these options creates a situation in which users don't have to make the decision and they may not even be aware of the default behavior we provide.

The best solution we've come up with is the `??` operator we've added, so you can do things like `myValue ?? .none`. Which would be equivalent to your proposed initializer called as `.init(myValue, as: .none)`.

But we think providing an initializer with a default value that you don't have to explicitly state could cause more issues than it solves.

Regardless, you are always welcome to create an extension like you've proposed and include it in your project. This allows you to have the convenience _and you are the one determining the default behavior_. Otherwise, the `??` operator is the best we've been able to come up with without potentially hiding this behavior behind a default value that may or may not be what you actually want.

Thank you for the suggestion though! We love getting feedback from the community!

**Comment by cshadek** [comment]
Thanks!  I was not aware of the added `??` behavior, but I actually like that better.

**Comment by AnthonyMDev** [comment]
Glad you like that! When we finish up the documentation, we'll be sure to highlight that ability in the usage examples better.
