### ISSUE TITLE
Why is has to be so complicated? (for beginner to setup Apollo iOS in a SwiftUI project)

### ISSUE THREAD

**Issue by 1c7** [apollographql/apollo-ios#2559]
## The SwiftUI is simple and elegant

<img width="1624" alt="image" src="https://user-images.githubusercontent.com/1804755/194892486-6d7a6ab7-8e51-45b1-b135-959c49eaf411.png">

## Apollo iOS, very complicated
<img width="1310" alt="image" src="https://user-images.githubusercontent.com/1804755/194892601-d69fbce9-03e7-4949-abfc-89a8433a0c00.png">

Step 1 is easy.
Step 2 Starting makes very little sense, why do I have to do this?

<img width="1312" alt="image" src="https://user-images.githubusercontent.com/1804755/194893193-10205c12-f6f9-42ff-b140-9dfe0934add1.png">

And I can't see the full code

<img width="1317" alt="image" src="https://user-images.githubusercontent.com/1804755/194892921-63cbf7c4-000d-4331-8a0c-216b7a650f40.png">

## And this 

<img width="1312" alt="image" src="https://user-images.githubusercontent.com/1804755/194893496-20a0fb09-c458-453e-83f9-878f4cc072f8.png">

doesn't make sense

# Suggestion: make it as simple as possible, less step is better.

**Comment by 1c7** [comment]
I know how GraphQL works, I know React.js and Ruby on Rails.
Our team has build a production web app using React.js + GraphQL `@apollo/client`.
I am beginner iOS developer trying to use SwiftUI to build our iOS app.

**Comment by 1c7** [comment]
Feel free to close this.
This is more of a useless complain (not constructive opinion)

**Comment by AnthonyMDev** [comment]
Thank you for the comments @1c7. For type-safe, compiled applications, generated models are one of the biggest benefits of Apollo iOS. In order to generate those, we need to understand the types in your schema. There really is no way for us to skip that step. 

However, 1.0 was just released and we are getting a lot of feedback that our documentation isn't entirely clear. We are working on addressing this and hope to clear up confusion and make this process easier very soon!
