### ISSUE TITLE
Getting No such module error

### ISSUE THREAD

**Issue by Spatel91111** [apollographql/apollo-ios#2594]
## Question
Create auto generate code using Cocoapods but getting error No such module 'CodeGen'

Here 'CodeGen' is custom schema in which all code generated.

Reference image
<img width="951" alt="Screenshot 2022-10-20 at 11 40 31 AM" src="https://user-images.githubusercontent.com/116056959/196869575-b0a8bc0e-ac22-406d-b942-8a224dff2f15.png">

**Comment by AnthonyMDev** [comment]
Hi @Spatel91111, we'll need to see your codegen configuration options to help out more.

**Comment by Spatel91111** [comment]
Here Codegen configuration json

<img width="623" alt="Screenshot 2022-10-21 at 9 45 42 AM" src="https://user-images.githubusercontent.com/116056959/197110476-76aef2c1-8505-4885-8620-dbccc4365d39.png">

**Comment by indama** [comment]
> ## Question
> Create auto generate code using Cocoapods but getting error No such module 'CodeGen'
> 
> Here 'CodeGen' is custom schema in which all code generated.
> 
> Reference image <img alt="Screenshot 2022-10-20 at 11 40 31 AM" width="951" src="https://user-images.githubusercontent.com/116056959/196869575-b0a8bc0e-ac22-406d-b942-8a224dff2f15.png">

I have the same issue. When I comment it out my code running. Temporarily I am customizing generated code

**Comment by calvincestari** [comment]
Hi @Spatel91111 👋🏻 - I believe your problem might be fixed by using `.inSchemaModule` for [`operations` output](https://www.apollographql.com/docs/ios/code-generation/codegen-configuration#operations).

The `import Codegen` statement is being generated because the codegen engine thinks the schema types will be in a different target, which could be the behaviour when using `.relative(subpath:)` or `.absolute(path:)`.

**Comment by calvincestari** [comment]
@indama you should try the same.
