### ISSUE TITLE
Multiple Schema support

### ISSUE THREAD

**Issue by sam961** [apollographql/apollo-ios#2597]
I have to server that I need to fetch data from
can we use multiple schema inside the new version 1.0?
example : append multiple url inside schemaDownloadConfiguration  key ?

**Comment by calvincestari** [comment]
Hi @sam961 👋🏻 - it sounds like you're wanting to use **two separate schemas** for code generation, is that correct?

The codegen engine can only handle one schema at a time. `schemaSearchPaths` in the configuration can accept more than one pattern because [schemas can be extended](https://spec.graphql.org/draft/#sec-Schema-Extension) but code generation will fail if you attempt to use two completely separate schemas.
