### ISSUE TITLE
Should the generated Package.swift depend on the current version of apollo-ios?

### ISSUE THREAD

**Issue by puls** [apollographql/apollo-ios#2617]
## Bug report

According to https://github.com/apollographql/apollo-ios/blob/main/Sources/ApolloCodegenLib/Templates/SwiftPackageManagerModuleTemplate.swift#L35, the generated Swift Package always depends on at least apollo-ios 1.0.0, even as the version that's generating the code increases.

I don't suppose this is a problem in practice, as (at least in my setup) if I use a newer version of apollo-ios to generate code then my whole Xcode project already has the newer version. But still, it seems kind of inconsistent, and one could install the CLI globally and versions could get out of sync.

## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: 1.0.2
- Xcode version: 14.1
- Swift version: 5.7
- Package manager: SPM

## Steps to reproduce

```sh
$ swift run --package-path "${APOLLO_PATH}" apollo-ios-cli generate
```

**Comment by calvincestari** [comment]
Hi @puls :wave - Yes, there needs to be stricter control of versioning between the CLI and dependency package. It will result in errors such as https://github.com/apollographql/apollo-ios/issues/2626 otherwise, and I'm sure many others too.

We're trying to figure out a way around this in https://github.com/apollographql/apollo-ios/issues/2562.

**Comment by calvincestari** [comment]
I'm going to close this and progress can be monitored in #2562 - PR #2659 is in progress to resolve the issue.
