### ISSUE TITLE
How to generate snake_case property name to camelCase in Apollo version 1.0.3 cli auto generate?

### ISSUE THREAD

**Issue by Spatel91111** [apollographql/apollo-ios#2641]
How to generate snake_case property name to camelCase in 1.0.3 cli auto generate?

Configuration in .json file as below:

<img width="550" alt="Screenshot 2022-11-04 at 4 43 00 PM" src="https://user-images.githubusercontent.com/116056959/199959664-78a885cd-35c3-4156-a70a-647df71a3c2c.png">

But generate property in mutation file as below

public var first_name: String { __data["first_name"] }

Need to generate property name like this

public var firstName: String { __data["first_name"] }

is it possible in Apollo 1.0.3 version?

**Comment by calvincestari** [comment]
Hi @Spatel91111 👋🏻 - currently the conversion strategy is only for enum cases. It does not work for all properties yet, that is one of the future features we're considering. I'll add this to a future milestone for now.

**Comment by calvincestari** [comment]
In the same area as https://github.com/apollographql/apollo-ios/issues/2570.

**Comment by Spatel91111** [comment]
Hello @calvincestari , is any update on this feature(convert snake_case property name to camelCase)?

**Comment by calvincestari** [comment]
No progress yet, it's scheduled for one of the upcoming releases. We're always happy to accept and review PRs though, thanks.

**Comment by Spatel91111** [comment]
Thank you @calvincestari !!!

Now one more question : is it possible to generate model with class instead of struct?

**Comment by AnthonyMDev** [comment]
@Spatel91111, no these models are immutable and intended to be used as value structs. It provides a lot of performance benefit to use structs here. What reasons do you have for wanting them to be classes?

**Comment by Spatel91111** [comment]
@AnthonyMDev thank you for reply.

There is one scenario that model object pass ahead 3-4 level screen and based on it first screen need to update due to struct object its pass by value and object value is not updated into first screen.

**Comment by AnthonyMDev** [comment]
The returned models are not updated in-place when your data is updated though. That's why they are immutable structs. When you get new data, you get completely new instances of your model objects, which you need to then pass to your views or some view model that can use the new data. Turning the models into classes would not change this.

Updating the models in-place would be a major change to the way Apollo works and is not something that is in scope for our current work. We do hope to provide better ways for you to receive updates to your data in a more fine grained way at some point, but I'm not sure what that will look like yet.
