### ISSUE TITLE
Apollo "Object" affected on RealmSwift Objects in project

### ISSUE THREAD

**Issue by alwacker** [apollographql/apollo-ios#2652]
## Bug report

Hi, I`ve started to migrate Apollo to 1.0.3 from 0.52. And huge problem is that latest update affected on all project, besides Apollo using in small part of my project. 

For example: 
RealmSwift has class "Object" which is NSObject, but Apollo's "Object" overrides Realms.

Same goes with optional func ??
![Screenshot 2022-11-09 at 2 47 22](https://user-images.githubusercontent.com/21243200/200716609-5d56594d-d677-44a0-9b96-2664ec3bf026.png)

## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: 1.0.3
- Xcode version:  14.0
- Swift version: 5.7
- Package manager: cocoapods

**Comment by calvincestari** [comment]
Hi @alwacker 👋🏻 

> Same goes with optional func ??

The nil coalescing operator error should be fixed with https://github.com/apollographql/apollo-ios/pull/2650, which is in `main` and will be included with the next release.

> RealmSwift has class "Object" which is NSObject, but Apollo's "Object" overrides Realms.

Is the build error happening in Apollo files or generated files? If it's in your own project source files and you're importing both libraries you'll probably need to use the full namespaced type name, eg: `RealmSwift.Object`.
