### ISSUE TITLE
Schema/Target/Module name with spaces in it breaks generated code

### ISSUE THREAD

**Issue by Narayane** [apollographql/apollo-ios#2653]
## Bug report

When a Xcode project name contains a space character, relative module name contains an `_` character instead.

In Test mocks files (Xxx+Mock.graphql.swift), for a project named `First Project`, imports are like:
```
// @generated
// This file was automatically generated and should not be edited.

import Apollo
import First Project

public class Xxx: MockObject {
```
but it should be
```
// @generated
// This file was automatically generated and should not be edited.

import Apollo
import First_Project

public class Xxx: MockObject {
```

## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: 1.0.3
- Xcode version: 13.4.1
- Swift version: 5.6.1
- CocoaPods: 1.11.3

## Steps to reproduce

Run `apollo-ios-cli generate` onto a Xcode project whose name contains a space.

**Comment by calvincestari** [comment]
Hi @Narayane 👋🏻 - thanks for reporting the issue.

This should be an easy fix, we'll get it into the next release. The workaround for now though is to use the Xcode-style of project name, i.e.: `First_Project` in the codegen configuration.

**Comment by calvincestari** [comment]
I dug into this issue a bit today and the fix is a bit more involved than I initially thought; I've updated the issue title to better reflect the scope of the problem.

* schema name with a space in it breaks the namespace enum for `embeddedInTarget` configuration
* target name with a space in it breaks import statements in test mocks. _The target name generally matches the Xcode project name, Xcode handles this by replacing the space with an underscore._

**Still to be tested:**
* CocoaPods schema module configuration
* Swift Package schema module configuration

**Comment by AnthonyMDev** [comment]
Can we just solve this by sanitizing the `schemaName` in `ApolloCodegenConfiguration.init`? If we need to use both the original name with spaces in it and the underscored one, let's add a `let schemaNamespaceName: String` to either `ApolloCodegenConfiguration` or `ApolloCodegen.ConfigurationContext`. That way we only need to do the conversion to the underscored name once and can use it where needed.

**Comment by calvincestari** [comment]
@Narayane - this is fixed, available on `main`, and will go out in the next release.
