### ISSUE TITLE
Generated Schema package using wrong import statements

### ISSUE THREAD

**Issue by StarLard** [apollographql/apollo-ios#2663]
## Bug report

When you specify `swiftPackageManager` module type to generate code, the generated Schema files will use `import Apollo` instead of `import ApolloAPI`, which generates the compiler error "No such module 'Apollo'"

## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: 1.0.3
- Xcode version: 14.0.1
- Swift version: 5.7
- Package manager: SPM

## Steps to reproduce

1. Generate code using the `swiftPackageManager` module type
2. Add generated Swift Package to target
3. Attempt to build project
4. Observe error

**Comment by StarLard** [comment]
After deleting everything and regenerating from scratch, it seems this is caused by using `swiftPackageManager` in conjunction with the `cocoapodsCompatibleImportStatements` option. So the bug is actually that the `cocoapodsCompatibleImportStatements` option is being propagated to the files generated for SPM, not just the generated operation files.

**Comment by calvincestari** [comment]
Hi @StarLard 👋🏻 - thanks for the bug report.

The combination of `cocoapodsCompatibleImportStatements` with a module type of `other` is the correct usage of those two properties. I think the bug is that we don't have a check to disallow `cocoapodsCompatibleImportStatements` when using `swiftPackageManager`.

Check in your config file what the value of `cocoapodsCompatibleImportStatements` is and set it to `false`; that will generate the correct import statements. I'll do some testing for `cocoapodsCompatibleImportStatements` + `swiftPackageManager` and get a fix in if needed.

**Comment by StarLard** [comment]
I was hoping to add my generated files to a target that has Apollo installed via cocoapods and bring in my schema types module via SPM, but I guess that would mean having two Apollo installations so yeah, it would be nice if this configuration wasn't available.

**Comment by calvincestari** [comment]
Yeah, that's not a configuration we support.

**Comment by calvincestari** [comment]
@StarLard, this is now fixed and will be included in the `1.0.4` release. An error will now be thrown if the config has conflicting values. Thanks for reporting this issue.
