### ISSUE TITLE
`pruneGeneratedFiles` is incorrectly deleting files

### ISSUE THREAD

**Issue by calvincestari** [apollographql/apollo-ios#2665]
Created from #2546 and comment https://github.com/apollographql/apollo-ios/issues/2546#issuecomment-1278024475.

**Comment by AnthonyMDev** [comment]
@SilverTab @pchmelar We have still been unable to reproduce the deletion of the files, as we spoke about in #2546. I'm wondering if other fixes we've made since than have inadvertently resolved this issue as well.

Could one of you try turning `pruneGeneratedFiles` back to `true` and see if it still deletes the wrong files with the latest version of the CLI?

**Comment by pchmelar** [comment]
Looks good in 1.0.6 🎉 Thank you!
https://github.com/MateeDevs/devstack-native-app/pull/55

**Comment by calvincestari** [comment]
Thanks for following up @pchmelar, I'm going to close out this issue now.

If it recurs please do come back to this issue and we'll take up the search again - thanks.

**Comment by calvincestari** [comment]
Here's some additional debugging from a customer recently:

I think I had found the potential root cause of the issue.
in configs file we were setting the following
```
"output" : {
    .
    .
    .
    "operations" : {
      "relative" : {
        "subpath" : "./GraphQLOperations"
      }
    }
  },
```
I think defining the `subpath` of relative mode for operations files starting with `./` was causing this issue (it was working fine t generate operations models at expected subpath, but on regeneration I think some unexpected behaviour happens and fails to match operation files to query files).
changing to `"subpath" : "GraphQLOperations"` fixing the issue without the need to disable `pruneGeneratedFiles`
