### ISSUE TITLE
Adding a prefix for autogenerated files

### ISSUE THREAD

**Issue by pavelmarchuk** [apollographql/apollo-ios#2666]
## Feature request

Would it be possible to add/specify a prefix for autogenerated files?

## Motivation

When an application uses 2 different graphql services with different schemas there may be conflicts related to the same generated filenames, which would prevent building the app when autogenerated files embedded into the app target directly (`moduleType` - `embeddedInTarget`).

## Proposed solution

I'm wondering whether it would be possible to add an option to `codegen` to specify a prefix for autogenerated files.

**Comment by sirajudheen53** [comment]
Having the same issue here.

**Comment by calvincestari** [comment]
Hi 👋🏻 - thanks for reporting this issue.

Is the filename prefix something that you would prefer or would it matter if the code generation engine simply detected the collisions and handled it automatically, i.e.: `file.graphql.swift` and `file_1.graphql.swift`?

**Comment by pavelmarchuk** [comment]
I believe it would be preferable to specify a prefix for a file name, so it would be more clear which service/schema is affected (`file_1.graphql.swift` doesn't tell much without looking into its path).

My thinking is that we have namespaces (or module names) for types and we have a way to specify that, so `codegen` could use prefixes (as kind of namespaces) on the project level to avoid name collisions.

**Comment by calvincestari** [comment]
> Also, my guess, it would be simpler and more bullet-proof than implementing automatic collision detection logic (like scanning the whole project as the issue is related to generating code for separate schemas -> separate codegen passes/invocations)?

No, we're not going to go down the route of trawling the whole project for potential collisions. Any solution to this is going to only affect Apollo code generated files, and be completely unaware of the rest of the project files

**Comment by ddanielczyk** [comment]
Same issue here. +1

**Comment by AnthonyMDev** [comment]
> When an application uses 2 different graphql services with different schemas there may be conflicts related to the same generated filenames, which would prevent building the app when autogenerated files embedded into the app target directly (moduleType - embeddedInTarget).

This seems to be a pretty narrow use case. Having to use 2 different GraphQL services is fine, but I don't see why you **need** to embed them all into the app target directly. If you are generating code for 2 GraphQL services, it makes sense to me that you would separate them into 2 different modules.

We actually made the decision to make the generated file paths end in `.graphql.swift` instead of just `.swift` specifically to deal with the generated files colliding with names of other files in your project. But trying to not collide with other generated files, generated by a separate execution of code generation on another schema is another story.

---

I'm not necessarily opposed to providing this option, but it certainly doesn't seem _necessary_ as the "workaround" I think actually results in a better project structure in most cases. In fact, I'd call it more of a recommended best practice than a workaround. 😄 

We're trying not to bog down the code generation engine with 100s of configuration options for every little thing that every person wants to do. We've had so many requests already for adding configuration options and most of them are to suit the specific preferences of a few people. If it's something that causes a serious blocker, or a large number of users are requesting it, I think it's something to consider. But this seems to be a pretty specific request for something that is going to serve very few people in a positive way.

What it actually serves to do is provide people an easier path to not modularize their projects, which I think is an anti-pattern. I don't think Apollo should be actively trying to force you into organizing your project the way we think is best, but this seems to cross the line into "actively take time to implement a feature that will only benefit people who don't want to follow best practices".

---

The code generation engine was written in Swift specifically so that Swift engineers can fork and alter the project to their exact needs. If this is something you want to do, I'm more inclined to say "Go ahead and fork the Codegen Lib and alter the file paths to do what you want." than I am to add a new configuration option in here.

If there is a large community response asking for this feature, or if there is a relatively common situation in which this is a blocker and modularization is a no-go for good reason, then I'm willing to reconsider. 
@calvincestari What is your opinion on this?

**Comment by calvincestari** [comment]
> What it actually serves to do is provide people an easier path to not modularize their projects, which I think is an anti-pattern. I don't think Apollo should be actively trying to force you into organizing your project the way we think is best, but this seems to cross the line into "actively take time to implement a feature that will only benefit people who don't want to follow best practices".

I pretty much agree with the above.

@pavelmarchuk, @ddanielczyk - is there a specific reason you need the generated files from both schemas in a single target?

**Comment by pavelmarchuk** [comment]
> @pavelmarchuk, @ddanielczyk - is there a specific reason you need the generated files from both schemas in a single target?

There is no specific reason to keep the generated files in the single target for me. I already solved the case by using separate pods containing generated files.

I don't want to make assumptions about the framework usage and practices and someone willingness to do the right thing, but it's nice to have control over auto-generated code to avoid collisions :)

Regards,
