### ISSUE TITLE
How to initialize GraphQLNullable with Swift.Optional

### ISSUE THREAD

**Issue by yasirmturk** [apollographql/apollo-ios#2702]
## Bug report

Documentation says this but there no initialiser provided like this;
<img width="664" alt="Screenshot 2022-12-06 at 16 34 44" src="https://user-images.githubusercontent.com/306691/205955444-3ab132d1-6fc7-47be-b9b5-58bf8f29f325.png">

## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: 1.0.5
- Xcode version: 14.1
- Swift version: 
- Package manager:

## Steps to reproduce

copy & paste the code provided in the docs
![Screenshot 2022-12-06 at 16 38 38](https://user-images.githubusercontent.com/306691/205956256-4af5088a-4093-4d0d-a961-06f8a45c1c8e.png)

## Further details

`No exact matches in call to initializer `

**Comment by AnthonyMDev** [comment]
Ah, maybe that documentation is not clear. That `.init(inputValue:)` is an example of an initializer for an object that takes a `GraphQLNullable` as a parameter. I'm not sure when you would want to initialize the `GraphQLNullable` directly, but you would need to do:
```swift
let optionalValue: String?
let none: GraphQLNullable<String>
if let value = optionalValue {
  none = .some(value)
} else {
  none = .none
}
```

There is no better API for this because I don't think it's something you should really need to/want to do. `GraphQLNullable` is really only relevant when you're passing the nullable into an input value. Up until that point, it's likely much easier to deal with your values as regular `Optional` values.

If you do have a good reason why this is something you want to do, we could consider adding an optional initializer directly to `GraphQLNullable`.

**Comment by calvincestari** [comment]
> the code generated by `apollo-ios-cli` for nullable string in Operation parameter always expects `GraphQLNullable<String>`
> 
> or may be that is a bug in code generation??

As long as the operation parameter is nullable the code generation engine will generate `GraphQLNullable`. This is correct and not a bug because it is valid GraphQL to send `null`, nothing (i.e.: `nil`), or a value. `GraphQLNullable` is how you can express one of those three possibilities using Apollo iOS.

> because input parameters do not need to converted to "NULL"??

If this is an implicit understanding of something within your schema, then change the operation parameter to be explicitly non-null. Apollo iOS cannot infer what is 'correct' for your code, it simply generates Swift code according to the GraphQL schema and operations.

**Comment by yasirmturk** [comment]
then please provide a way to convert `Optional<String>` to `GraphQLNullable<String>`

**Comment by AnthonyMDev** [comment]
Yes, we've discussed this before, but opted not to, because we can't provide the default value of `.none` or `.null`, you have to decide what that is. And if you have a sane default that always works for your schema, creating a convenience initializer in an extension is totally reasonable. 

Also, worth nothing that the `??` operator will work with an explicit type, so you should be able to do this:

```swift
let GraphQLNullable<String> = optionalValue ?? .none
```

**Comment by yasirmturk** [comment]
`let GraphQLNullable<String> = optionalValue ?? .none`
does not work 
`Cannot convert value of type 'String?' to expected argument type 'GraphQLNullable<String>'`

but this works fine 
```
public extension GraphQLNullable {
    init(optional: Wrapped?, defaultValue: Self = .none) {
        if let value = optional {
            self = .some(value)
        } else {
            self = defaultValue
        }
    }
}
```
