### ISSUE TITLE
Crashing when trying to unpack a Null value for a selection set

### ISSUE THREAD

**Issue by harry-lush** [apollographql/apollo-ios#2725]
### Summary

When a server returns null (represented as a NSNull) for a property of a SelectionSet it leads to the following crash in DataDict.swift:

<img width="921" alt="Screenshot 2022-12-08 at 23 02 13" src="https://user-images.githubusercontent.com/119686390/207016766-74541f76-7baf-4320-9ec5-4840acc5df98.png">

### Version

1.0.5

### Steps to reproduce the behavior

For me this is entirely reproducible on 1.0.5 and also on the current `main`, if the server returns an object that has a Null value as a property.

The test in this PR reproduces this issue: https://github.com/apollographql/apollo-ios/pull/2716.. you can reproduce the same error in test form by checking out the test here: https://github.com/apollographql/apollo-ios/pull/2716/commits/ef6436239af157fae2ff0558de30bcefb505181f without the subsequent fix.

### Logs

```shell
I've included an image above, as it avoids needing to redact logs.
```

### Anything else?

I've added a PR to fix this issue here: https://github.com/apollographql/apollo-ios/pull/2716

**Comment by AnthonyMDev** [comment]
@harry-lush, what situation are you running into that is actually causing this issue? The unit test is initializing a `SelectionSet` with JSON data directly, but this is unsafe and something you should not ever be doing in production code.

When you run a GraphQL operation through `ApolloClient`, the JSON response data is run through the `GraphQLExecutor`, which parses, validates, and runs type coercion on  the data to ensure that all required fields are present and valid. This is does using the `GraphQLSelectionSetMapper`. The completion block hands you an instance of your generated model that is guaranteed to be valid.

Part of what the `GraphQLSelectionSetMapper` does it remove all `null` fields from the data, converting them to `nil`. This is better for memory, as you don't have a bunch of `NSNull` objects and additional key value pairs in the data dictionary on your models.

We wish the `init(fieldData: variables:)` initializer could be `private`, but because it's part of generated objects that exist in your target but is called by the `Apollo` library, it has to be `public`. We still consider it to be a private API that should not be used by consumers.

If you need to initialize a model directly, understand that this is unsafe, and that you are now at the whim of implementation details of the Apollo iOS library (that are not guaranteed not to change). We don't have a problem with doing this in unit tests, but in production code it's not recommended. If you are going to do this, you should omit from your JSON any null fields.

**Comment by harry-lush** [comment]
Thanks @AnthonyMDev,
In the test I initialised the SelectionSet that way following the pattern in the other tests to verify that the change fixed the issue. In our code these are being called by normal graphQL requests which are working with 0.53.0 in the current app. 

Here's the (slightly anonymised) stack trace:
```
#0	0x000000018bfa78e0 in _swift_runtime_on_report ()
#1	0x000000018c034580 in _swift_stdlib_reportFatalErrorInFile ()
#2	0x000000018bce32a8 in closure #1 in closure #1 in _assertionFailure(_:_:file:line:flags:) ()
#3	0x000000018bce216c in _assertionFailure(_:_:file:line:flags:) ()
#4	0x0000000103bbe264 in AnySelectionSet.init(fieldData:variables:) at …/SourcePackages/checkouts/apollo-ios/Sources/ApolloAPI/DataDict.swift:54
#5	0x0000000103e2c708 in protocol witness for SelectionSetEntityValue.init(fieldData:variables:) in conformance ReferenceBlock.Content ()
#6	0x0000000103bbe530 in Optional<τ_0_0>.init(fieldData:variables:) at …/SourcePackages/checkouts/apollo-ios/Sources/ApolloAPI/DataDict.swift:68
#7	0x0000000103bbeaf8 in protocol witness for SelectionSetEntityValue.init(fieldData:variables:) in conformance <τ_0_0> τ_0_0? ()
#8	0x0000000103bbd0c0 in DataDict.subscript.getter at …/SourcePackages/checkouts/apollo-ios/Sources/ApolloAPI/DataDict.swift:26
#9	0x0000000103e26d08 in ReferenceBlock.content.getter at …Fragments/ReferenceBlock.graphql.swift:36
#10	0x0000000102da7018 in Repository.convertReference(_:) …/Repository/FeedRepository.swift:212
```

As I mentioned in the PR it might be patching an issue higher in the chain. Maybe the bug is earlier, in GraphQLSelectionSetMapper or somewhere? However it's happening, I can see that there is an NSNull getting through to `AnySelectionSet.init(fieldData:variables:)`. In this case it's trying to access the `content` property on ReferenceBlock which is auto-generated code representing fragment.

If I print out the ReferenceBlock's _data I can see that `content` is a NSNull (rather than nil):

```
▿ DataDict
  ▿ _data : 4 elements
    ▿ 0 : 2 elements
      - key : "content"
      ▿ value : AnyHashable(<null>)
        - value : <null>
       …
```

My current workaround is to test and avoid calling the problematic keys.

**Comment by calvincestari** [comment]
> In our code these are being called by normal graphQL requests which are working with 0.53.0 in the current app.

Have you noticed if there is any particular iOS versions for this crash? We're also working on https://github.com/apollographql/apollo-ios/issues/2668 which might be related but is limited to iOS 14.4 and below.

**Comment by harry-lush** [comment]
@calvincestari Sorry for the slow reply. We're targeting iOS 15.. All my testing has been on devices using iOS 16 and later.

**Comment by harry-lush** [comment]
I've found an issue in our code that I think was modifying some selection sets in an odd way. We've removed that and also switched to Sqlite caching.. and everything seems to work now. So I'm going to close it.. and will re-raise if it occurs again.
