### ISSUE TITLE
Add better default initializers for GraphQLNullable<Wrapped>

### ISSUE THREAD

**Issue by PatrickDanino** [apollographql/apollo-ios#2729]
### Use case

I recently completed the porting of our model and network layers from v0.x to v1.0. My general feedback is that this was a lot more painful than it needed to be.

Handling nullable types is now essentially broken by design. Even if you wanted to add the concept of `.none` versus `.null` (which is in itself confusing and poorly documented), not supporting nullable values out of the box (such as `String?`) will force every client of your SDK to either hack something together, write unnecessarily verbose code, potentially pick the wrong option between `.none` and `.nil`, or all of the above. It was also exceedingly difficult to get array types to work

Another big pain point was forcing every query parameter to specify a value, likely for the same reason. It seems like this should have been configurable from the code generator, where you could either pick one or the other as the default and handle the potentially few exceptions rather than require lots of boilerplate code for every query.

### Describe the solution you'd like

In case it helps others, I was able to at least simplify some of our code by writing an extension like this one:

```
extension GraphQLNullable {
    /// Initializes GraphQLNullable using a nullable value
    /// - Parameters:
    ///   - object: The value to use if not nil
    ///   - nilValue: The default to use if the value is nil.
    ///   See ``GraphQLNullable`` for more info.
    @inlinable public init(_ object: Wrapped?, nilValue: GraphQLNullable = .none) {
        if let object {
            self = .some(object)
        } else {
            self = nilValue
        }
    }
}
```

**Comment by Dimillian** [comment]
Yes please. Current implementation is a disaster for upgrading to 1.X. We do have a beautiful Swift API around everything, with you know, Swift optional. Why would we want `GraphQLNullable`?
It even make non optional retrieval .value optional.
I really don't understand the design process behind this. 

Please juste just use Swift optional and delete `GraphQLNullable`

Thanks.

**Comment by ZsoltMolnarrr** [comment]
Totally agree the current API might have been a good idea on paper, but in a sizeable project where enums and optionals are frequently nested this is painful to use.

**Comment by erneestoc** [comment]
+ 1 here 👍🏻

**Comment by tahirmt** [comment]
There is a very clear distinction between a `null` value and `nil` for Apollo. Sometimes the Apollo backend would require us to send a `null` value and sometimes not at all if the value doesn't exist. While I understand how the upgrade is painful, this change has been a very welcome change for us. This has also been a feature of the android side and was missing from iOS for a while.

**Comment by JoeFerrucci** [comment]
Before v1.0, we were able to initialize any generated model directly using the default initializer (e.g., from a struct).
Now, some models are SelectionSets and the properties have no setters and the provided initializers are verbose and ugly.; Unlike the InputObject type where it provides setters for each property, making it easy to manually construct the models.

How can we generate setters for every generated model?

**Comment by calvincestari** [comment]
> How can we generate setters for every generated model?

@JoeFerrucci, you can track the [release/1.1](https://github.com/apollographql/apollo-ios/tree/release/1.1) branch where work is being done to enable selection set initializers.

**Comment by dafurman** [comment]
+1 to this issue. The heavy use of `GraphQLNullable` is a real deterrent to using generated types throughout our codebase when we have no interest in making a between `nil` vs `null`, particularly when it comes to receiving data. In terms of consuming data on the client, we just care if it's there or not, which is could be idiomatically covered by Swift optionals.
It would be nice for this to be an option for those who want it, rather than forced with Apollo 1.0+.

**Comment by dafurman** [comment]
To those who it may help, I've created some extension properties to make working with `GraphQLNullable` a bit easier with property chaining, letting you quickly adjust pre Apollo 1.0 with syntax like `"myString".gqlNullable`, where you could have used a `String` directly before.
https://gist.github.com/dafurman/faf04069a8c5ed76354b9eab9c1b3328

**Comment by BrentMifsud** [comment]
I feel like a lot of the 1.0 release is like this. The new GraphQLEnum is just as clunky to work with. Swift has enums built in, why do we need a custom enum type?

Also the removal of initializers from fragments makes mocking and testing overly complicated.

We have been at it for about a week now trying to migrate from 0.53.0 and it's been extremely painful so far.

That being said, here is our extension on GraphQLNullable to make it a bit easier to use with optional types. It might help you:

```swift
import ApolloAPI

extension GraphQLNullable {
    init(optionalValue value: Wrapped?) {
        if let value {
            self = .some(value)
        } else {
            self = .null
        }
    }
}
```

**Comment by JoeFerrucci** [comment]
@BrentMifsud, you might like this thread: https://github.com/apollographql/apollo-ios/issues/2883

**Comment by BrentMifsud** [comment]
@JoeFerrucci unfortunately the new config option for generating initializers isn't working for me. There doesn't seem to be any difference in what gets generated regardless if I add that config option or not 🤷🏻‍♂️

Im currently on apollo 1.1.1

**Comment by JoeFerrucci** [comment]
lets see your config.

**Comment by BrentMifsud** [comment]
> lets see your config.

got it figured out. I needed to move that new config property under `options`.

**Comment by alessdiimperio** [comment]
Thought i'd throw in my take aswell as it allows for imo better readability.

```
extension GraphQLNullable {
static func optional(_ value: Wrapped?, defaultNil: GraphQLNullable = .none) -> GraphQLNullable {
        guard let value else { return defaultNil }
        return .some(value)
    }
    }

```    
Current example above yields:
Query(param: GraphQLNullable(someOptionalValue))
or
Query(param: .init(someOptionalValue)

My take imo allows for a slight readability improvement.

Query(param: .optional(someOptionalValue))

**Comment by Mordil** [comment]
In practice, I definitely haven't been seeing as much value in the `GraphQLEnum` vs the `GraphQLNullable` type for existing apps. I bet the value proposition is much higher for greenfield projects, or smaller projects with few enums.

If Swift had the ability to extend Enum literals like we could with `nil`, I'm sure this value would be highly alleviated and more seamless

This is because in existing apps, we were able to use the raw enum as a plain enum everywhere, with a "natural" default of `__unknown` for values, and when upgrading we either had to decide our own default based on the values provided, or convert all of our types to Optionals, which got cumbersome to propagate through our codebase

**Comment by AnthonyMDev** [comment]
This issue has been discussed exhaustively. We understand the cumbersome nature of `GraphQLNullable`, but in order to ensure fully correct code that behaves as the developer intends it, this has to exist as it is. You are free to implement your own convenience extensions in your projects, but because we can't know if you want to default to `null`, or `nil`, we can't add them to the core SDK.
