### ISSUE TITLE
issue in compiling code after integration apollo ios using cocoapods

### ISSUE THREAD

**Issue by arsh94deep** [apollographql/apollo-ios#2779]
### Summary

I integrated apollo iOS using cocoapods
I then generated the config files and imported them in my project directory and are facing multiple issues.
not able to compile the project.
Please help.

### Version

1.0.5

### Steps to reproduce the behavior

Steps to reproduce the behavior
i am using these latest docs from apollo
https://www.apollographql.com/docs/ios/get-started

I integrated apollo iOS using cocoapods

i downloaded the schema file and dropped it in my project directory (.graphqls)

I have created a Queries.graphql file.

I created a config file from terminal using the command -> ./Pods/Apollo/apollo-ios-cli init --schema-name EquilibertySchema.graphqls --module-type embeddedInTarget --target-name Equiliberty

I then tried to generate the  codegen files

and I am not able to compile the project.

Please help.

**Comment by calvincestari** [comment]
Hi @arsh94deep 👋🏻

> I created a config file from terminal using the command -> ./Pods/Apollo/apollo-ios-cli init --schema-name EquilibertySchema.graphqls --module-type embeddedInTarget --target-name Equiliberty

`--schema-name` is the namespace for the generated files, not the schema file name. See the [documentation](https://www.apollographql.com/docs/ios/code-generation/codegen-cli#initialize).

You will also probably need to use the `.other` module type due to the way that CocoaPods pulls the dependency into the project. See the guide on [Project configuration](https://www.apollographql.com/docs/ios/project-configuration).
