### ISSUE TITLE
Have generated types conform to Encodable

### ISSUE THREAD

**Issue by Tyler-Keith-Thompson** [apollographql/apollo-ios#2783]
### Use case

Because generated types are nested under a given query it can be difficult to unify them into a shared data model. Protocols can be used, but this results in a large amount of boilerplate code having to be written for every generated type. 

We'd like to build an abstraction layer that pulls responses from Apollo into the `Codable` ecosystem. This allows us to build powerful abstractions that can convert from a given selection set into app-defined models.

### Describe the solution you'd like

We can actually do this today already, but it requires us to use a public symbol that has an `_` and seems unsupported (like so)

```swift
public final class GraphQLDecoder: TopLevelDecoder {
    public typealias Input = AnySelectionSet
    
    private let jsonDecoder = JSONDecoder()
    
    public init() { }
    
    public func decode<T>(_ type: T.Type, from input: Input) throws -> T where T : Decodable {
        let json = try JSONSerialization.data(withJSONObject: input.__data._data)
        return try jsonDecoder.decode(T.self, from: json)
    }
}
```

I'd much rather encode it, do whatever we want, and decode it into a non-nested type.

**Comment by Tyler-Keith-Thompson** [comment]
I'd be happy to submit a PR, if this feature is agreeable.

**Comment by AnthonyMDev** [comment]
We do not intend on making the generated types conform to `Codable` currently. This conversation has been had many times already, and while we do see the arguments for it, we have decided not to support this directly.

There are too many edge cases that people will want to handle differently. The normalized cache is a direct solution to storing your generated models in a way that solves for all of the edge cases of GraphQL. For persistence, you are going to get better performance (and first-party support for new GraphQL features by using the normalized cache. Encoding your models and storing them to disk with `Codable` is a worse solution in almost every way.

If you still want to do it, you can use the `_data` properties. They are prefixed with the `_` because we want people to be aware that they are doing something that we don't recommend and we aren't going to provide support for (ie. if you cause other bugs in your code while using them, we aren't going to make changes to Apollo to support your use case). But they are there for you to use if you know what you are doing.

The `__data.data` is already a JSON object (with the caveat that your custom scalars are transformed from raw JSON into your custom scalar types if you provide them). If you have models you want to convert from JSON. You can do exactly what your are doing above just fine. If you want to turn it back to raw JSON, use the property `input.__data.data._jsonValue`. I guess you can use `Codable`, but it's actually far less performant than converting from the dictionary to your models manually.

---

However:

> This allows us to build powerful abstractions that can convert from a given selection set into app-defined models.

It sounds like what you really want is to [use fragments](https://www.apollographql.com/docs/ios/fetching/fragments). If you want generated models that are shareable across your application, fragments will do exactly that and can be used across multiple different operations.
