### ISSUE TITLE
Do I need to keep the schema and the operations in different files?

### ISSUE THREAD

**Issue by vegidio** [apollographql/apollo-ios#2796]
### Question

I followed the documentation on how to use GraphQL in my iOS project.

1. I already installed Apollo GraphQL using SPM.
2. I ran `./apollo-ios-cli init --schema-name ${MySchemaName} --module-type ${ModuleType}` to generate the `apollo-codegen-config.json` file.

but I'm stuck in the part to generate the Swift code from the schema.

I have the schema AND the operations in a single file in my project's root folder called `schema.graphqls`, but when I ran `./apollo-ios-cli generate` I get the error "Error: No GraphQL operations could be found. Please verify the operation search paths."

So I decided to duplicate my file, renamed it to `opreations.graphql` and I ran `./apollo-ios-cli generate` again but this time I get many errors like "The 'Mutation' definition is not executable."

I'm not sure if this happening because I have my schema and operations in the same file or if this is happening due to some other reason. In any case, I find odd that the code generation apparently looks for schema and operations in different files. I used Apollo code generation before in some backend projects for Java and Node.js they always seemed to generate the respective Java and Typescript files just fine if the schema and operations are in a single file.

Is there a reason why they must be placed in different files for the iOS code generation? And more important, is this really what is causing the error "The 'Mutation' definition is not executable."?

Thanks!

**Comment by calvincestari** [comment]
> I'm not sure if this happening because I have my schema and operations in the same file or if this is happening due to some other reason.

Yes the errors are being caused by your schema and operations being in the same file. They must be separate, which is indicated by the configuration having two separate `input` paths; `schemaSearchPaths` and `operationSearchPaths`.

> In any case, I find odd that the code generation apparently looks for schema and operations in different files. I used Apollo code generation before in some backend projects for Java and Node.js they always seemed to generate the respective Java and Typescript files just fine if the schema and operations are in a single file.

Different software, different implementation. It has always been this way for Apollo iOS. The legacy (0.x) code generation also required two separate files - [documentation](https://www.apollographql.com/docs/ios/v0-legacy/installation).

I'm interested to learn how you have them in a single file though. Schemas are typically fetched from a server through introspection unless you're handwriting a schema outside of a server. Operations are typically not stored on servers either. It seems that I would have to intentionally combine them into a single file rather than simply using them as given from the tooling?

> And more important, is this really what is causing the error "The 'Mutation' definition is not executable."?

Yes. I suspect the GraphQL validator is reading your 'operations' file and expecting to find GraphQL syntax for operations not a schema. GraphQL operations are 'executable' whereas a schema is not.

To get your configuration working and able to generate code you'll need to separate them into different files. Also note that you should use a different extension for each unless you're going to provide absolute paths for the `input` parameter. _This is the reason we give a default configuration value of `*.graphqls` for schema and `*.graphql` for operation files._
