### ISSUE TITLE
Generated Mock Classes with namespaces

### ISSUE THREAD

**Issue by marcosmko** [apollographql/apollo-ios#2797]
### Question

Hello guys!

I'm having some troubles while working with Apollo/ApolloTestSupport.

While on main target the generated schemas are created inside `{TargetName}Schema`, the generated mock objects are not contained inside a namespace, and this creates some conflicts with other classes that I have inside the project or are generated from other tools.

Is there a way to define a namespace to be used, on some renaming?

Thanks!

**Comment by calvincestari** [comment]
This really depends on how you've configured the code generation engine. Would you mind sharing your configuration file here so I can better understand how you're outputting the generated code?

**Comment by marcosmko** [comment]
here it is!

```json
{
  "schemaName" : "NowSchema",
  "options" : {
    "cocoapodsCompatibleImportStatements" : true
  },
  "input" : {
    "schemaSearchPaths" : [
      "./NewsNOW/Core/Networking/Schema/schema.graphqls"
    ],
    "operationSearchPaths" : [
      "./NewsNOW/Core/Networking/Schema/Mutations.graphql",
      "./NewsNOW/Core/Networking/Schema/Queries.graphql"
    ]
  },
  "output" : {
    "testMocks" : {
      "absolute" : {
        "path": "NewsNowTests/Mocks/Apollo"
      }
    },
    "schemaTypes" : {
      "path" : "./NewsNOW/Core/Networking/Generated",
      "moduleType" : {
        "embeddedInTarget" : {
          "name": "Now"
        }
      }
    },
    "operations" : {
      "relative" : {
        "subpath": "../Generated"
      }
    }
  }
}
```

**Comment by calvincestari** [comment]
Thanks for the config details.

Using `cocoapodsCompatibleImportStatements` set to `true` I assume you use CocoaPods as the dependency manager for Apollo iOS? _This changes the `import` statements for the Apollo module._

`embeddedInTarget(name:)` is the module type that provides the most freedom on how to structure your code, although we do namespace the schema types because there is a far higher chance of conflict. The test mocks will not be namespaced in this config.

The only way to have the test mocks in a namespace is to have them in their own module, or if you're using CocoaPods then putting them into their own pod. If you're going to go the route of defining modules for these things you should look into using the `other` module type.

**Comment by marcosmko** [comment]
I see, I'm trying to do the simpler way but cannot seem to find something that works.

I played a bit with the SPM distribution, but I'm having troubles with automating some of my steps, because it seems the binary is not distributed and instead, it needs to be compiled via the `Install CLI` plugin via Xcode. Do you know if I can invoke this plugin using CLI? (using Package.swift does not seem to be an option). Or maybe installing some cli tool using homebrew?

Thanks!

**Comment by marcosmko** [comment]
Hey guys, for anyone interested on how I solved this and some discoveries that I made.

The best option is to put generated schema inside a target. Could be a framework, could be a SPM package or a pod. I created a pod by putting generated code inside a generated folder together with cocapods specs so I could add them via Podfile.

Here is my apollo configuration:
```
{
  "schemaName" : "MySchema",
  "options" : {
    "cocoapodsCompatibleImportStatements" : true
  },
  "input" : {
    [...]
  },
  "output" : {
    "schemaTypes" : {
      "path" : "./generated/schema/Sources",
      "moduleType" : {
        "other" : {}
      }
    },
    "testMocks" : {
      "absolute" : {
        "path": "./generated/schema/TestMocks"
      }
    },
    "operations" : {
      [...]
    }
  }
}
```

Here is my podspec for generated schema, that stays on `generated` folder:
```
Pod::Spec.new do |s|
  s.name = 'MySchema'
  s.version = '1.0.0'
  s.author = 'My Team'
  s.homepage = 'My Homepage
  s.license = { :type => 'UNLICENSED' }
  s.summary = "Generated source for apollo client."
  s.source = { :git => '' }
  s.source_files = 'schema/Sources/**/*.swift'
  s.swift_version = '5.7'
  s.ios.deployment_target = '15.0'
  s.dependency 'Apollo/Core'
end
```

And podspec for generated test mocks, that also stays on `generated` folder:
```
Pod::Spec.new do |s|
  s.name = 'MySchemaTestSupport'
  s.version = '1.0.0'
  s.author = 'My Team'
  s.homepage = 'My Homepage'
  s.license = { :type => 'UNLICENSED' }
  s.summary = "Generated source for apollo client."
  s.source = { :git => '' }
  s.source_files = 'schema/TestMocks/**/*.swift'
  s.swift_version = '5.7'
  s.ios.deployment_target = '15.0'
  s.dependency 'MySchema'
end
```

After that, I just need to add pods to my Podfile:
```
pod 'MySchema', :path => 'generated'
pod 'MySchemaTestSupport', :path => 'generated'
```


From my findings, cocoapods works best, because:
- I can use the apollo generator binary by invoking `./Pods/Apollo/apollo-ios-cli generate`. With SPM, you need to use the `Install CLI` plugin inside Xcode to generate the tool, which is located on `DerivedData`. If I delete this folder, I need to use the plugin again. Creating scripts for automation works better too.
- I tried creating a framework only for the mock objects, but that doesn't work because those files need access to generated schema, so it would need the generated schema to also be inside a framework.
- I think that creating a custom framework will just pollute our workspace and number of targets.

**Comment by calvincestari** [comment]
Hey @marcosmko, apologies for not replying to your earlier comment a couple days ago. _I must have had an answer in my mind but never actually commented with it._

> I played a bit with the SPM distribution, but I'm having troubles with automating some of my steps, because it seems the binary is not distributed and instead, it needs to be compiled via the Install CLI plugin via Xcode. Do you know if I can invoke this plugin using CLI? (using Package.swift does not seem to be an option).

Both CocoaPods and SPM dependencies come with the same state of non-compiled binary. CocoaPods however offers the [`prepare_command`](https://github.com/apollographql/apollo-ios/blob/main/Apollo.podspec#L19) on Pods which allows us to build the CLI once it's been downloaded, so it appears to be part of the distribution. SPM unfortunately does not yet have that kind of capability which is why we needed to build the "Install CLI" plugin. Note that you can execute the 'Install CLI' plugin both through Xcode and from the command line (if you use a Package.swift file). As a last resort you can always pull a pre-built binary from the latest tagged release - _[this command](https://github.com/apollographql/apollo-ios/releases/latest/download/apollo-ios-cli.tar.gz) will always fetch the latest CLI and there are checks in the CLI to prevent version mismatches with the Apollo library your project is using._

> Or maybe installing some cli tool using homebrew?

No, we don't distribute the CLI through Homebrew.

> The best option is to put generated schema inside a target. Could be a framework, could be a SPM package or a pod.

Yes, this is our recommended best-practice approach.

> I can use the apollo generator binary by invoking ./Pods/Apollo/apollo-ios-cli generate. With SPM, you need to use the Install CLI plugin inside Xcode to generate the tool, which is located on DerivedData. If I delete this folder, I need to use the plugin again.

Both the CocoaPods/SPM CLI build functions should create a symbolically linked file in the root of where your project is. You shouldn't need to use a command that targets the Pods/Apollo folder specifically.

> I tried creating a framework only for the mock objects, but that doesn't work because those files need access to generated schema, so it would need the generated schema to also be inside a framework.

I recommend familiarizing yourself with the configurable options for test mocks as to what structures they can support - [docs](https://www.apollographql.com/docs/ios/code-generation/codegen-configuration#test-mocks).
