### ISSUE TITLE
 Error with generated module on new M1 Mac

### ISSUE THREAD

**Issue by sirajudheen53** [apollographql/apollo-ios#2814]
### Summary

Hello,

I am using the Apollo iOS library for my GraphQL integration in my iOS app. I have added the Apollo framework using the Swift Package Manager and I have two separate GraphQL spaces with corresponding schema and GraphQL files. I followed the Apollo iOS Code Generation tutorial to generate the required dependency files using apollo-ios-cli. The generated packages were loaded into my project using SPM local packages. This was done on an Intel Mac machine.

However, when I run my project on a new M1 Mac, I am encountering the following error:

"Could not find module '{generated module}' for target 'x86_64-apple-ios-simulator'; found: arm64, arm64-apple-ios-simulator on macbook m1".

This error only occurs when running the app in the simulator and the app runs without issue on real devices. I would greatly appreciate any assistance in resolving this issue.

Thank you!

### Version

1.0.5

### Steps to reproduce the behavior

1. Create an iOS app with two different GraphQL spaces.
2. Add the Apollo library to the app using Swift Package Manager (SPM).
3. Generate the required Apollo files/modules using the Apollo CLI.
4. Add the generated modules to the project using local SPM packages.
5. Run the code in a silicon-based Mac and in the simulator.
6. Xcode will throw the error message "Could not find module '{generated module}' for target 'x86_64-apple-ios-simulator'; found: arm64, arm64-apple-ios-simulator on macbook m1".

**Comment by calvincestari** [comment]
Hi @sirajudheen53, I'm very doubtful this has anything to do with Apollo iOS. All the code within Apollo iOS and all the codegen generated code is Swift source code, there are no precompiled libraries, which means all the code can be compiled on any architecture. It won't make any difference whether the schema package was generated on an Intel or Apple Silicon mac.

This problem is going to be related to an Xcode setting for your iOS project about building/including architectures. I suggest doing a [search for the error message](https://www.google.com/search?q=Could+not+find+module+for+target+%27x86_64-apple-ios-simulator) and taking a look at how others have fixed the build error before. There is nothing we can do in Apollo iOS to solve this for you unfortunately.
