### ISSUE TITLE
GraphQLQueryWatcher captures itself

### ISSUE THREAD

**Issue by RolandasRazma** [apollographql/apollo-ios#282]
I think `[weak self]` is missing here (getting some leaks)

https://github.com/apollographql/apollo-ios/blob/dd1fbe87d4591635ba9c5065c23f72b7b088b478/Sources/Apollo/GraphQLQueryWatcher.swift#L31

**Comment by vandadnp** [comment]
Wouldn't putting `[unowned self]` there crash the app if self disappears before the result block is called?

**Comment by RolandasRazma** [comment]
I'm running currently with unowned and so far no crashes, but hadn't done extensive testing

**Comment by vandadnp** [comment]
`[unowned self]` I would say makes sense in a view controller where the button is owned by the view controller and you are using RxSwift and listening for tap events on the button.

If the button is tapped and Rx catches that, then you can take your view controller as `[unowned self]` in the button's tap even since you know if the button is tapped, then the view controller must be present in the memory for without the view controller there would be no button.

But in this case, if the client fetches something and that takes 3 seconds, since your client is a weak variable, it is not owned by your query watcher, hence the disappearance of the watcher doesn't mean the disappearance of the client, and vice versa.
