### ISSUE TITLE
What is the feature parity between 0.x versions and 1.x?

### ISSUE THREAD

**Issue by Mordil** [apollographql/apollo-ios#2822]
### Question

**As of today, what is the state of the library's feature parity between the old engine and the new one?**

Are models cached automatically in the SQLite database (per cache policies), with the ability to mutate the cache outside of operations?

## Context

My team has a fork of the Apollo project at https://github.com/peek-travel/apollo-ios that we split off around 2 years ago, due to [lack of caching features](https://github.com/apollographql/apollo-ios/pulls?q=is%3Apr+author%3Amordil+is%3Aclosed) that we needed to support features in our iOS app

Our fork was based off of `0.36.0` and we never updated, due to time constraints or real necessity.

This quarter we prioritized updating our fork to the latest version, with our extensions, as we were lead to believe from release notes that the latest release still supported the original codegen library and the _new_ Swift-based codegen engine was still _opt-in_.

This doesn't appear to be the case.

Part of the reason why we are hesitant to update to the latest codegen is primarily all through development of the new engine, we were lead to believe that caching was not going to be supported for models generated by the new engine, at least as part of the initial release.

And we're not sure just how drastically different the new engine's models are from the old engine's. Our GraphQL types are referenced and used directly in a significant portion of the codebase.

**Comment by calvincestari** [comment]
Hi @Mordil 

> As of today, what is the state of the library's feature parity between the old engine and the new one?

Feature parity should be the same; if you are aware that something is missing please let us know. In our view `1.0` has been a successful release and our public [roadmap](https://github.com/apollographql/apollo-ios/blob/main/ROADMAP.md#1xx-patch-releases) for `1.1`, `1.2` and `1.3` details some of the continued work we're putting into the new code generation engine.

> Are models cached automatically in the SQLite database (per cache policies), with the ability to mutate the cache outside of operations?

Responses are still normalized and cached as was available in 0.x. Local cache mutations are still available too. Both of the mechanisms for these features has changed slightly from 0.x and I recommend reading their respective sections in the [1.0 migration guide](https://www.apollographql.com/docs/ios/migrations/1.0); [Cache key configuration](https://www.apollographql.com/docs/ios/migrations/1.0#cache-key-configuration) and [Local cache mutations](https://www.apollographql.com/docs/ios/migrations/1.0#local-cache-mutations).

> due to [lack of caching features](https://github.com/apollographql/apollo-ios/pulls?q=is%3Apr+author%3Amordil+is%3Aclosed) that we needed to support features in our iOS app

Can you share a bit more details of the features you added to your fork? Without any substantive changes to the cache layer in 1.0, it will likely still have the same cache feature limitations you found in 0.x

> This quarter we prioritized updating our fork to the latest version, with our extensions, as we were lead to believe from release notes that the latest release still supported the original codegen library and the new Swift-based codegen engine was still opt-in.

There was a change in [`0.46.0`](https://github.com/apollographql/apollo-ios/blob/main/CHANGELOG.md#v0460) that removed the experimental Swift codegen engine as an option and changed to making it available in a 1.0 specific branch instead. The changes to the generated models were substantive enough that it was no longer feasible to support both in a single release version.

We have a [1.0 migration guide](https://www.apollographql.com/docs/ios/migrations/1.0) which documents all the required steps to get from a 0.x version to 1.0. There have been many successful migrations so I don't expect anything that would be a blocker for you but I urge you to read the migration guide and let us know if there is anything that you believe would prevent you from adopting 1.0.

If that's not the change you're referring to please point me in the direction of release notes re. opt-in for codegen; if there is misleading information out there I would like the opportunity to correct it.

> Part of the reason why we are hesitant to update to the latest codegen is primarily all through development of the new engine, we were lead to believe that caching was not going to be supported for models generated by the new engine, at least as part of the initial release.

I don't know where this information came from but a normalized cache is one of the core features of Apollo iOS. It might be acceptable in an alpha version to not have full support for caching but I do not recall any intention to drop it from a major release.

> And we're not sure just how drastically different the new engine's models are from the old engine's. Our GraphQL types are referenced and used directly in a significant portion of the codebase.

Migrating from 0.x to 1.0 is a breaking change. You must regenerate the models with the new codegen engine in order to use 1.0. I recommend reading the migration guide as a start. Then try regenerate your models, or at least one, that you can assess the extent of the differences.

**Comment by Mordil** [comment]
> Can you share a bit more details of the features you added to your fork? Without any substantive changes to the cache layer in 1.0, it will likely still have the same cache feature limitations you found in 0.x

1. New Cache policy
2. Ability to clean the cache
3. A `receivedAt` on data that allows us to have a pseudo "age" of data

1 should be solved by us instead modeling the policy as an interceptor behavior, and 2 was solved when y'all added the same capability back around the 0.4x.x days

3 is the part that still hasn't been implemented as far as I can tell - you can see the original PR here in #1498

We use that data to show to our users when they lack network connection the relative age of the data since they last communicated with the backend

![IMG_2DA98FD5A16C-1](https://user-images.githubusercontent.com/3506776/217985661-fdbd33de-0aa3-403c-983c-2a2894ebee43.jpeg)

We spent the time re-applying our changes to the latest release (as of 2 weeks ago), but when we went to go ingest the changes that's when we were caught off guard of the dropped support for the typescript-based engine.

> There was a change in [0.46.0](https://github.com/apollographql/apollo-ios/blob/main/CHANGELOG.md#v0460) that removed the experimental Swift codegen engine as an option and changed to making it available in a 1.0 specific branch instead. The changes to the generated models were substantive enough that it was no longer feasible to support both in a single release version.

It was not explicitly stated anywhere obvious that the `0.46.0`, or even the 1.0 release was going to drop support for typescript codegen engine and be entirely replaced by the new Swift-based engine.

> I don't know where this information came from but a normalized cache is one of the core features of Apollo iOS. It might be acceptable in an alpha version to not have full support for caching but I do not recall any intention to drop it from a major release.

We clearly were operating off of very out of date information. We kept referring to issue #939 as the only source of a roadmap.

Given that we had to fork, we partially ignored the development of this repository aside from releases, and release notes were not giving an indication of where that roadmap was headed.

We were not sure if 1.0 would mean just the new engine being "generally ready" and then the later cache support (as outlined in the issue linked above) would come as 1.x releases.

---

Thanks for talking through this.

This definitely means good & bad things. Good in that we can 100% adopt the latest codegen engine, but bad in the sense that we have more work than we initially thought as part of our upgrade.

**Comment by calvincestari** [comment]
> Thanks for talking through this.
> 
> This definitely means good & bad things. Good in that we can 100% adopt the latest codegen engine, but bad in the sense that we have more work than we initially thought as part of our upgrade.

Hopefully you'll derive plenty of future-good from the investment in adopting the latest release. If you have any issues please do let us know.

`1.0.7` was just released, which fixed a bunch of smaller issues, and `1.1` should not be too far off either. The [roadmap](https://github.com/apollographql/apollo-ios/blob/main/ROADMAP.md) is updated frequently so I'd keep an eye on that for confirmation of direction and future releases.
