### ISSUE TITLE
How to remove @exported in CLI generated graphQL.swift file?

### ISSUE THREAD

**Issue by pankajK-Vinsol** [apollographql/apollo-ios#2824]
### Question

**@exported** keyword is coming in front of **import Apollo** statement while using CLI generated graphQL.swift file.
Attaching screenshot with the code.
Command used for file generation is: 
`./Pods/Apollo/apollo-ios-cli generate`

<img width="703" alt="Screenshot 2023-02-09 at 4 27 37 PM" src="https://user-images.githubusercontent.com/49402116/217794123-01fe7666-d946-40c1-9e64-c03ba1c7cdf1.png">

**Comment by calvincestari** [comment]
Hi @pankajK-Vinsol - is the use of `@_exported` causing problems, why do you need to remove it?

**Comment by pankajK-Vinsol** [comment]
Hi, I'm getting compiler errors because of that, generated files are not compiling. 
And is working fine after removing those **@exported** keyword. It is a task considering there are many graphQL mutations in project.
Let me know, if there's something which can be done on my end for this?

Attached is the current structure of GraphQL files in project.
API -> Contains queries/ mutations
ScemaGraphQL -> Contains all generated files
<img width="300" alt="Screenshot 2023-02-10 at 4 22 10 PM" src="https://user-images.githubusercontent.com/49402116/218074340-16f85585-daf5-4527-83df-a6d142263996.png">

**Comment by calvincestari** [comment]
> Hi, I'm getting compiler errors because of that, generated files are not compiling.
> And is working fine after removing those @exported keyword.

Can you share the compiler errors here please. We haven't had any previous reports of this and instead of you simply removing them we should figure out what the root issue is rather.

> It is a task considering there are many graphQL mutations in project.
> Let me know, if there's something which can be done on my end for this?

You can remove them manually but since those are generated files the next time you generate the files they will be back again. There is no option to remove `@_exported`.

**Comment by HimalayaRajput0211** [comment]
Hi, please find the attached SS of error
<img width="325" alt="Screenshot 2023-01-31 at 4 07 21 PM" src="https://user-images.githubusercontent.com/60002785/218665998-c897df58-8cb5-439f-842d-8668196597e1.png">

**Comment by prat14k** [comment]
@calvincestari we are receiving such compilation issues. On debugging more, we found that it is having some issues with the Realm classes we have in the project (those who inherit `RealmSwift`'s `Object` class).

**Comment by calvincestari** [comment]
That error `Command SwiftEmitModule failed with a nonzero exit code` isn't telling you that @_exported is a problem, there must be some other error/warning message. `@_exported` simply forwards the import so that where the generated files are being imported the Apollo namespace types will be available too.

> On debugging more, we found that it is having some issues with the Realm classes we have in the project (those who inherit RealmSwift's Object class).

OK, so the problem is a type conflict between `Object` within Realm and `Object` within Apollo iOS. If you're importing both libraries into the same file then you'll need to use a fully qualified namespace for `Object`, like `Realm.Object` or `ApolloAPI.Object`.
