### ISSUE TITLE
Finding Apollo.framework with static libraries

### ISSUE THREAD

**Issue by rnystrom** [apollographql/apollo-ios#283]
I'm testing out CocoaPods 1.5 and building my app with static libraries to see if it noticeably improves launch times. When I build, I hit the `exit 1` in the codegen build phase b/c it can't find Apollo.framework.

Is there a tweak I need to make to the codegen script to find the framework? Some other setup/config I need to do?

**Comment by martijnwalraven** [comment]
If you're building with static libraries, there won't be a framework :) That's not necessarily an issue, but you'll have to adapt the build phase script to invoke `apollo-codegen` directly instead of trying to find (check-and-run-apollo-codegen.sh)[https://github.com/apollographql/apollo-ios/blob/master/scripts/check-and-run-apollo-codegen.sh] in the framework bundle. That means you'll lose the version compatibility checking and automatic installation of `apollo-codegen`, so you'll have to be careful to install a compatible version.

**Comment by rnystrom** [comment]
Ah! Duh. Ok I’ll play around with it.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
