### ISSUE TITLE
Constant sessionInvalidated error

### ISSUE THREAD

**Issue by pshowell23** [apollographql/apollo-ios#2875]
### Question

I posted my issue on [Stackoverflow](https://stackoverflow.com/questions/75726078/constant-sessioninvalidated-on-apollo-ios) yesterday. 

My issue is that no matter what I do, I get a sessionInvalidated error when querying data from our iOS app. Some of this may be that I am new to iOS development, but I do not understand what is causing this issue. I have the authorization headers going in as I need, but I am still getting this error. I've gone through the documentation, but that doesn't seem to be helpful.

If I could get any assistance, that would be helpful.

**Comment by calvincestari** [comment]
Hi @pshowell23 - the cause of this that I've seen in the past is due to the ApolloClient instance being released somewhere.

Specifically, the error message for an invalidated session:
* can be found at https://github.com/apollographql/apollo-ios/blob/main/Sources/Apollo/URLSessionClient.swift#L31
* it is generated at https://github.com/apollographql/apollo-ios/blob/main/Sources/Apollo/URLSessionClient.swift#L118
* and caused by the session being invalidated at https://github.com/apollographql/apollo-ios/blob/main/Sources/Apollo/URLSessionClient.swift#L70
* which in turn is called from https://github.com/apollographql/apollo-ios/blob/main/Sources/Apollo/DefaultInterceptorProvider.swift#L28
* the fact that the call to invalidate is in a de-initializer (deinit) means that the object holding on to it is being released from memory. De-initializers are not manually called so this behaviour is more of a side-effect of something else going on.

I would add a breakpoint to the deinitializer and see if you can trace what is causing the object to be released.
