### ISSUE TITLE
typename failures

### ISSUE THREAD

**Issue by yonaskolb** [apollographql/apollo-ios#2916]
### Question

We have a bunch of test fixtures checked into our repo as json files that we use for tests and previews. They used to decode ok, but moving to the new `RootSelectionSet.init(data: JSONObject)` init they fail with the error of missing `__typename`, which seems reasonable. I understand the new init does a bunch of graph validation. 
I don't know why some both top level definitions and nested definitions are missing them as they were recorded before I was on the project, but they used to work before.
I understand if we have to update these to have typenames but just trying to understand if it's a hard requirement? It seems using `SetSelection.init(_dataDict: DataDict)` does still work, presumably because it doesn't check the values.

**Comment by AnthonyMDev** [comment]
The `__typename` field is necessary because it is used to determine what type cases the generated models can be converted into.

If you have a schema like this:
```graphql
type Query {
  allAnimals: [Animal!]
}

interface Animal {
  string: String!
  int: Int!
}

type Bird implements Animal {
  string: String!
  int: Int!
}
```

And a query of:

```graphql
allAnimals {
    ... on Bird {
      string
    }
}
```

In order to access the `string` field on the generated model, you would write `data.allAnimals[0].asBird?.string`

The `asBird` property needs to check the `__typename` field of the json data to determine if the underlying Animal is a Bird or not before converting it. If the `__typename` is not `"Bird"` then it returns `nil`.

Using `SetSelection.init(_dataDict: DataDict)` will not do any validation or parsing, but as soon as you try to use that object, you're going to get nil returned from type conversion properties, and you may get crashes when accessing properties.
