### ISSUE TITLE
`makefile` improvement - CLI

### ISSUE THREAD

**Issue by asbhat** [apollographql/apollo-ios#2919]
### Summary

After upgrading to Xcode v14.3 the `InstallCLI` Command Plugin seems to be missing.

I created a new project and installed `apollo-ios` but the plugin is still missing. Am I doing something wrong?

<img width="394" alt="image" src="https://user-images.githubusercontent.com/3885798/229012643-b0a6441a-2ae8-433a-974e-3c48eaf78920.png">

### Version

v1.0.7

### Steps to reproduce the behavior

1. Install Xcode v14.3
2. Create a new project
3. Add package `apollo-ios`
4. Right click on the project in the navigator
5. The command plugin is missing

**Comment by calvincestari** [comment]
Hi @asbhat - we've taken a look and don't have a clear idea on what could be causing it to be missing; [our implementation of `XcodeCommandPlugin`](https://github.com/apollographql/apollo-ios/blob/main/Plugins/InstallCLI/InstallCLIPluginCommand.swift) hasn't changed. We're also concerned it could be a regression in Xcode 14.3 support for SPM plugins since the plugin is visible when opening a `package.swift` based project (vs. an Xcode project that uses SPM dependencies).

I realize it is inconvenient not having it in the menu and until we can figure out the root cause the workaround would be to grab the pre-built CLI binary we attach to each [GitHub release](https://github.com/apollographql/apollo-ios/releases) and place that in the root of your project directory; the effect will be the same and the CLI has a version checker so if you ever update the dependency but forget to manually download the pre-built CLI it will warn you.

**Comment by asbhat** [comment]
Thanks for the response Calvin!

I did end up just grabbing the pre-built CLI binary ([docs here](https://www.apollographql.com/docs/ios/code-generation/codegen-cli#installation)) that works just fine.

I took a quick look at the plugin too and couldn't figure it out :(
but it does seem other projects are having similar issues (e.g., https://github.com/nicklockwood/SwiftFormat/issues/1404), so you're probably right that it's a regression and something for Apple to fix.

Should I close the issue?

**Comment by calvincestari** [comment]
I think leave it open for a bit longer and let's monitor if it's showing up in other libraries too.

**Comment by PawanSinghatia** [comment]
Hi @calvincestari , @asbhat  please provide the exact steps for the pre-built CLI binary solution for this issue

**Comment by PawanSinghatia** [comment]
> Thanks for the response Calvin!
> 
> I did end up just grabbing the pre-built CLI binary ([docs here](https://www.apollographql.com/docs/ios/code-generation/codegen-cli#installation)) that works just fine.
> 
> I took a quick look at the plugin too and couldn't figure it out :( but it does seem other projects are having similar issues (e.g., [nicklockwood/SwiftFormat#1404](https://github.com/nicklockwood/SwiftFormat/issues/1404)), so you're probably right that it's a regression and something for Apple to fix.
> 
> Should I close the issue?

Ho w to grab the pre-built binary ?

**Comment by BrentMifsud** [comment]
I'm experiencing this as well. Looks like its probably an Xcode bug.

**Comment by calvincestari** [comment]
I've confirmed this is happening in the [Sourcery](https://github.com/krzysztofzablocki/Sourcery) framework too. I haven't seen any sign of a new Xcode beta though, nor a quick release of `14.3.1` - I'm really not sure what's taking them so long to react to this.

**Comment by BrentMifsud** [comment]
It's happening with swiftgen as well.

Definitely a bug with Xcode

**Comment by e-001** [comment]
Perhaps this was just a change by Apple rather than a bug. The menu item is still available in our GQL package itself, just not the root context menu.

<img width="362" alt="Screenshot 2023-04-26 at 1 23 47 AM" src="https://user-images.githubusercontent.com/82472766/234477366-544fdb42-75f4-445e-b817-a4f167ec2b1c.png">

**Comment by dadouf** [comment]
> Perhaps this was just a change by Apple rather than a bug. The menu item is still available in our GQL package itself, just not the root context menu.
> 
> <img alt="Screenshot 2023-04-26 at 1 23 47 AM" width="362" src="https://user-images.githubusercontent.com/82472766/234477366-544fdb42-75f4-445e-b817-a4f167ec2b1c.png">

This is an interesting workaround for people, and should work for most people who had generated the Apollo Swift code into a Swift package before the bug appeared. It just installs the apollo-ios-cli shortcut in the package's folder instead of the project's one. But then it can be moved.

**Comment by calvincestari** [comment]
It's an interesting workaround. I've only managed to get it to work when adding Apollo iOS as a _local_ package though, if I add it a remote github-based package it's still missing from the menu.

[Local package dependency](https://user-images.githubusercontent.com/146856/234649279-ba9f901f-9db2-46a0-aa71-835f91e5edaf.png) vs. [Remove package dependency](https://user-images.githubusercontent.com/146856/234649487-fccc7c22-6e5a-4666-9e2d-3d1e651420b3.png).

**Comment by AnthonyMDev** [comment]
TODO: 
- [] Add a comment to the documentation explaining the work around for using the `makefile` to build the CLI.
- [] Have the `makefile` command automatically move the built CLI to the project root directory.

**Comment by calvincestari** [comment]
I've confirmed that [Xcode 14.3.1 RC](https://developer.apple.com/documentation/xcode-release-notes/xcode-14_3_1-release-notes#Swift-Packages) resolves this issue. I'm going to change the title of this issue to reflect the work we still wanted to do.
