### ISSUE TITLE
"embedInTarget" configuration is generating redundant import statements

### ISSUE THREAD

**Issue by BrentMifsud** [apollographql/apollo-ios#2938]
### Summary

When using embedInTarget in my configuration, all of the operation files get generated with an `import MyTargetName` statement.

Since the generated code is to be added to the target, there does not need to be an import statement for the target. 

As a result, I get hundreds of warnings in my code because of redundant import statements:

![image](https://user-images.githubusercontent.com/18543934/230502426-e9b16c4b-dfc5-4b0f-ac16-94a90d6f8baa.png)

### Version

1.1.0

### Steps to reproduce the behavior

See attached config:

```json
{
    "schemaName" : "EnvoySchema",
    "input" : {
      "operationSearchPaths" : [
        "EnvoyMobile/Modules/GraphQL/Fragments/*.graphql",
        "EnvoyMobile/Modules/GraphQL/Mutations/*.graphql",
        "EnvoyMobile/Modules/GraphQL/Queries/*.graphql"
      ],
      "schemaSearchPaths" : [
        "EnvoyMobile/Modules/GraphQL/schema.graphqls"
      ]
    },
    "output" : {
      "testMocks" : {
        "none" : {
        }
      },
      "schemaTypes": {
        "moduleType": {
            "embeddedInTarget": {
              "name": "EnvoyMobile"
            }
        },
        "path": "EnvoyMobile/Modules/GraphQL/Generated/Schema/"
      },
      "operations" : {
        "absolute" : {
          "path": "EnvoyMobile/Modules/GraphQL/Generated/Operations"
        }
      },
      "deprecatedEnumCases": "include",
      "schemaDocumentation": "include",
      "warningsOnDeprecatedUsage": "include",
      "conversionStrategies": {
          "enumCases": "camelCase"
      },
      "pruneGeneratedFiles": true,
      "selectionSetInitializers" : {
        "operations": true,
        "namedFragments": true,
        "localCacheMutations" : true
      }
    }
  }
```

**Comment by AnthonyMDev** [comment]
Oh! This one took me a few minutes to figure out what was going on...

This is because your `operations` are using the `absolute` setting. With this setting, we are assuming that your schema files are in a target called `EnvoyMobile`, but your operations are likely in some _other_ target that needs to import `EnvoyMobile` to have access to the schema types.

To fix this, you can change your `operations` to `inSchemaModule`.

Then I'd change your `path` for your `schemaTypes` to remove the `/Schema` path component. As you will get your operations and your schema generated into `EnvoyMobile/Modules/GraphQL/Generated/Schema` and `EnvoyMobile/Modules/GraphQL/Generated/Operations` automatically! There will also be a `EnvoyMobile/Modules/GraphQL/Generated/Fragments` folder for your generated fragments.

**Comment by BrentMifsud** [comment]
Thanks, ill try that.
