### ISSUE TITLE
Installing the ApolloSDK for packages that support both SPM and cocoapods.

### ISSUE THREAD

**Issue by elviva404** [apollographql/apollo-ios#2993]
### Question

Hello,
I am developing a package/library that depends on the Apollo SDK.
The package has to be accessible via SPM and cocoapods.
I initially setup the Apollo SDK via SPM(my config file) and everything works fine.

However, when I attempted to setup my podspecs for cocoapods, i.e adding Apollo SDK as a dependency, almost all my generated Apollo files had errors indicating the ApolloAPI could not be found. Upon further investigation in the Apollo SDK codebase, I realised ApolloAPI isn’t a module you can import from when installing via cocoapods so I manually created conditional imports in all files that had the ApolloAPI import statement.

The aforementioned fixed resolved the import errors however the podspec build is reporting errors in almost all the generated Apollo files. Can I kindly get some assistance on how to install the SDK on a package that supports both SPM and cocoa pods.

 (Errors attached in screen
<img width="878" alt="Screenshot 2023-05-03 at 5 54 00 AM" src="https://user-images.githubusercontent.com/33577593/235841445-f8233558-707f-40c7-b98e-fad393807851.png">
shot below)
<img width="1724" alt="Screenshot 2023-05-03 at 5 49 19 AM" src="https://user-images.githubusercontent.com/33577593/235841767-6cc62a85-c73f-42db-92db-937a52e547d8.png">
<img width="1728" alt="Screenshot 2023-05-03 at 5 48 53 AM" src="https://user-images.githubusercontent.com/33577593/235841801-1b83f439-d20f-4ecb-9688-a04cb5f887ee.png">
<img width="1728" alt="Screenshot 2023-05-03 at 5 48 31 AM" src="https://user-images.githubusercontent.com/33577593/235841811-afc3e650-3215-40fe-bfce-fc751a3e8c42.png">

**Comment by calvincestari** [comment]
Hi @elviva404 👋🏻 

> However, when I attempted to setup my podspecs for cocoapods, i.e adding Apollo SDK as a dependency, almost all my generated Apollo files had errors indicating the ApolloAPI could not be found. Upon further investigation in the Apollo SDK codebase, I realised ApolloAPI isn’t a module you can import from when installing via cocoapods so I manually created conditional imports in all files that had the ApolloAPI import statement.

This is because CocoaPods smashes the submodules together and makes them available as a single module named the same as the pod. We have a configuration option [`cocoapodscompatibleimportstatements`](https://www.apollographql.com/docs/ios/docc/documentation/apollocodegenlib/apollocodegenconfiguration/outputoptions/cocoapodscompatibleimportstatements) to cater for this in the codegen engine which will generate the correct import statements depending on how Apollo iOS will be made available to the generated code.

> Can I kindly get some assistance on how to install the SDK on a package that supports both SPM and cocoa pods.

You can have both SPM and CocoaPods in a single project each linking to the Apollo iOS dependency in their own way but there is no way to configure the generated code to be able to work with both; our generated code expects to link through either SPM _or_ CocoaPods.

If you want your generated code to work with both then you'll need to add [conditional compilation statements](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/statements/#Compiler-Control-Statements) to link to the correct module, similar to [this](https://github.com/apollographql/apollo-ios/blob/main/Sources/Apollo/ApolloClient.swift#L3):
```
#if !COCOAPODS
import ApolloAPI
#endif
```

Bear in mind though that those changes will all be overwritten the next time code generation is executed, so there really is no reliable way at the moment to do what you want. I also don't think this is something we will be supporting so you may need to fork the repo and modify the code to suit your needs unfortunately.

**Comment by elviva404** [comment]
Thanks @calvincestari
