### ISSUE TITLE
How to remove operationName in request body

### ISSUE THREAD

**Issue by psdevss** [apollographql/apollo-ios#2998]
### Question

Hi and good day.

would like to ask, if how can we modify and remove operationName in request body? Currently having an error about this.

**Comment by calvincestari** [comment]
Hi. No there is no way to remove the operation name from the operation sent to the server. What is the error you're getting back?

**Comment by psdevss** [comment]
Thanks for the response @calvincestari. Error is "request is not valid" status code 400 "reason": "extraneous key [operationName] is not permitted"

**Comment by calvincestari** [comment]
I'm curious what GraphQL server you're using that is returning this error?

Just to be clear - if we take the following as an example, you're wanting to remove the text between the asterisks from the query that gets sent to the server is that correct? That doesn't seem like a 'key'. Have you tried your query in Studio or GraphiQL with your GraphQL server to get it working by stripping out the operation name?
```
query **GetThings** {
  things {
    __typename
    name
    size
    product {
      __typename
      name
      count
    }
    url
  }
}
```

**Comment by steevelynACN** [comment]
Sad to say, they  only provided the endpoint and graphqls, so we can't test. But our android team, modified the request in the Interceptor to remove the operationName in the json request body and it returned a 200. I can't seem to try in iOS

**Comment by psdevss** [comment]
Sad to say, they only provided the endpoint and graphqls, so we can't test. But someone from our android devs found a workaround and modified the request in the inceptor to remove the operationName in the json request body and it returned a 200. Can't seem to try it in iOS

**Comment by calvincestari** [comment]
You might be able to do the same thing by subclassing `RequestChainNetworkTransport` and overriding the `constructRequest` function. The last parameter for that function is `requestBodyCreator`; you could provide your own request body creator that conforms to the `RequestBodyCreator` protocol and do anything you'd like to the body of the request, including stripping out the operation name.

I'm going to close this issue because there isn't any way to do this currently in Apollo iOS and it's not something we'd implement support for. I'm happy to continue guiding you in this issue though.

**Comment by steevelynACN** [comment]
Thanks @calvincestari , will try to do this

**Comment by psdevss** [comment]
Thanks @calvincestari!, will try to do this
