### ISSUE TITLE
Regression: `accessModifier` not honoured for custom scalars

### ISSUE THREAD

**Issue by lhunath** [apollographql/apollo-ios#3066]
### Summary

I am using Apollo codegen in a multi-module project. I am generating the schema into one module and then using the schema from other modules which define the queries that operate on the schema.

For this to succeed, Apollo codegen needs to make its generated types `public` so that the code generated for the other modules will be able to see it. To do this, I've added `"accessModifier": "public"` to my `embeddedInTarget` `moduleType` and `relative` `operation`.

The result is that GraphQL codegen is correctly making some of my types public:
```
public enum HubstaffGraphQL { }
```

But is failing to make my custom scalar public:
```
extension HubstaffGraphQL {
  /// An ISO 8601-encoded date
  typealias ISO8601Date = String

}
```

### Version

1.2.1

### Steps to reproduce the behavior

<details>
<summary>apollo-codegen-config.json</summary>
<pre>
{
  "schemaName" : "HubstaffGraphQL",
  "input" : {
    "operationSearchPaths" : [
      "Hubstaff/**/*.graphql"
    ],
    "schemaSearchPaths" : [
      "Hubstaff/**/*.graphqls"
    ]
  },
  "output" : {
    "testMocks" : {
      "none" : {
      }
    },
    "schemaTypes" : {
      "path" : "Hubstaff/Modules/Services/Server/GraphQL",
      "moduleType" : {
        "embeddedInTarget": {
          "name": "Server",
          "accessModifier": "public"
        }
      }
    },
    "operations" : {
      "relative" : {
          "subpath": "GraphQL",
          "accessModifier": "public"
      }
    }
  }
}
</pre>
</details>

<details>
<summary>Hubstaff.graphqls</summary>
<pre>
"""
An ISO 8601-encoded date
"""
scalar ISO8601Date

type Mutation

type Query {
  activitiesDate(memberId: ID, organizationId: ID!, zone: String! = "UTC"): [ISO8601Date!]!
}
</pre>
</details>

<details>
<summary>Activities.graphql</summary>
<pre>
query DaysWithActivities($organizationId: ID!, $memberId: ID!, $zone: String!) {
  activitiesDate(memberId: $memberId, organizationId: $organizationId, zone: $zone)
}
</pre>
</details>

### Logs

```shell
$ swift run -p <path-to-apollo> apollo-ios-cli generate -p apollo-codegen-config.json
warning: 'apollo-ios': found 1 file(s) which are unhandled; explicitly declare them as resources or exclude from the target
    /Users/hubstaff/Library/Developer/Xcode/DerivedData/hubstaff-gzrfwrxonhprdsgrwcthjbfooayp/SourcePackages/checkouts/apollo-ios/Sources/ApolloCodegenLib/Frontend/auto_rollup.sh
[0/1] Planning build
Building for debugging...
Build complete! (0.25s)
```
```


### Anything else?

_No response_

**Comment by lhunath** [comment]
Note: this is a regression in ``.
Prior to this, Apollo codegen did correctly mark all of my types as `public` (even without `"accessModifier": "public"` in `apollo-codegen-config.json`).

`1.1.3`:
```
extension HubstaffGraphQL {

    /// An ISO 8601-encoded date
    public typealias ISO8601Date = String
}
```
`1.1.2`:
```
public extension HubstaffGraphQL {

    /// An ISO 8601-encoded date
    typealias ISO8601Date = String
}
```

Probably broken by: https://github.com/apollographql/apollo-ios/issues/2630 https://github.com/apollographql/apollo-ios/pull/2917

**Comment by lhunath** [comment]
I should note that it was imprudent to change the default behaviour from `public` types to `internal` types without documenting this in your `1.2.0` [migration guide](https://www.apollographql.com/docs/ios/migrations/1.2/) (or did I miss it?)

**Comment by calvincestari** [comment]
Hi @lhunath

Custom scalar files are not regenerated if they already exist. This is to prevent overwriting of any custom transformation logic for your custom scalars. They all have the following comment at the top of the file:
```
// @generated
// This file was automatically generated and can be edited to
// implement advanced custom scalar functionality.
//
// Any changes to this file will not be overwritten by future
// code generation execution.
```

Have you tried removing the custom scalar file so it can be regenerated? _You'll need to re-add any custom logic you have in the custom scalar files though._

**Comment by lhunath** [comment]
Oh yes, I have indeed. Note that if it had been left unchanged, I would not have seen this issue at all, since my old (`v1.1.3`) scalar files had correct code in them.  The bad code was introduced by the version update (which, I should note, is done automatically by Xcode because this is a MINOR version bump).

It seems to me that we shouldn't do breaking changes in minor versions since they are not announced by default with Xcode's SPM (`upToNextMajorVersion`).

**Comment by calvincestari** [comment]
I cannot replicate a difference in the generated code between versions `1.1.2`, `1.1.3` or `1.2.0`. [This is the sample project](https://github.com/apollographql/apollo-ios/files/11697031/Archive.zip) I am using with the provided schema, operation and configuration. _The configuration was changed for paths/target name but the module type and operation outputs are the same._ All three versions generate a public extension on the enum namespace.

Generated with `1.1.2`
```
public extension HubstaffGraphQL {
  /// An ISO 8601-encoded date
  typealias ISO8601Date = String

}
```

Generated with `1.1.3`
```
public extension HubstaffGraphQL {
  /// An ISO 8601-encoded date
  typealias ISO8601Date = String

}
```

Generated with `1.2.0`
```
public extension HubstaffGraphQL {
  /// An ISO 8601-encoded date
  typealias ISO8601Date = String

}
```

So I cannot replicate the bug you describe. It would help if you can update the sample project to generate the `public` enum namespace but `internal` extension, as described:
> The result is that GraphQL codegen is correctly making some of my types public:
> 
> ```
> public enum HubstaffGraphQL { }
> ```
> But is failing to make my custom scalar public:
> 
> ```
> extension HubstaffGraphQL {
>   /// An ISO 8601-encoded date
>   typealias ISO8601Date = String
> }
> ```

Is the root of the bug you're reporting that the `accessModifier` config default is `internal` rather than `public`? That I can understand and yes in hindsight the default should maybe have been `public` for an easier dependency update. I still believe `internal` is the correct access modifier for module types of `embeddedInTarget` though so the default made sense as what new code should be generated with. Thanks for highlighting the lack of notice in the migration guide, I'll get that updated.

We do our best to follow the principles of [Semantic Versioning](https://semver.org/spec/v2.0.0.html) with the caveat that minor versions will sometimes include minor breaking changes. Our definition of a "minor breaking change" is something that can easily be resolved but does not require substantial refactoring of user code. In this example the easy resolution is through the config option to produce the same code as before, which we should have made more public knowledge in the migration guide and changelog.

**Comment by lhunath** [comment]
Unfortunately I've had no success in reproducing the issues I was observing last night. I'm pretty certain I diligently deleted the generated source after switching Xcode's exact version of Apollo between `1.1.2`, `1.1.3` and `1.2.1`, yielding the outputs as described in the OP (they were copy pasted directly from the generated code, none of which is ever manually modified).

Today however, I can only reproduce the missing `public` in `1.2.x` when `apollo-codegen-config.json` does not have the `"accessModifier": "public"`.

I have no idea how I ended up with the `public` modifier directly on the `typedef` in my `1.1.3` test. Perhaps it's related somehow to the fact that you cannot have public extensions on internal types, so having a left-over `public` on the extension when the base type was re-generated as internal somehow moved it into the typedef for correctness? Perhaps even swift-format was involved somehow? As I said, I was unable to reproduce, but this complication serves to highlight the vast complexities introduced downstream when breaking changes are not handled clearly.

Adding `"accessModifier": "public"` to my config, I am now seeing `public extension` in `1.2.1` as expected.

However, note also that (due to https://github.com/apollographql/apollo-ios/issues/3066#issuecomment-1583460226) every user who is migrating from `1.1.x` to `1.2.x` and gets an error message due to this new setting being missing from their config will may be confused, since adding the setting to the config as directed will:
1. Correctly update some of their files, eg. `public enum HubstaffGraphQL { }`
2. Leave broken some of their other files, eg. `extension HubstaffGraphQL {`

These pitfalls make smooth migration extra challenging.

**Comment by calvincestari** [comment]
> Today however, I can only reproduce the missing public in 1.2.x when apollo-codegen-config.json does not have the "accessModifier": "public".

Which is correct due to the default for the `accessModifier` associated value on `embeddedInTarget` being `.internal`.

> However, note also that (due to https://github.com/apollographql/apollo-ios/issues/3066#issuecomment-1583460226) every user who is migrating from 1.1.x to 1.2.x and gets an error message due to this new setting being missing from their config may be confused, , since adding the setting to the config as directed will:
> 
> Correctly update some of their files, eg. public enum HubstaffGraphQL { }
> Leave broken some of their other files, eg. extension HubstaffGraphQL {

Unfortunately yes, which makes me realize I hadn't added specific direction about files that wouldn't be overwritten to the migration update in #3068. I'll add that in now before the PR gets merged.

**Comment by calvincestari** [comment]
> Could someone clarify also what the difference is between adding "accessModifier": "public" to embeddedInTarget vs. operations.relative?

The output location for operations supports three cases: `inSchemaModule`, `relative` and `absolute`.
* `inSchemaModule` will take on the access modifier value of the `schemaTypes.moduleType` because those files are going to be generated into that package so no point in allowing a conflict of access modifier value.
* `relative` and `absolute` could be in paths that are outside of the generated schema module yet you may still need public access to those files which is why you get the option to specify them.

The design of 1.0 was influenced heavily by the need to support more modular architectures, which I think it does well, but there is certainly a learning curve to understanding the impact of the various configuration options.

**Comment by calvincestari** [comment]
Thank you for the feedback on the lack of clarity for the migration path. It's led to #3068 which is a good outcome for all users.

I don't think there is any further actionable change we can make for this issue though so I'm going to close it; _the default `accessModifier` for `embeddedInTarget` will remain as `internal._

**Comment by lhunath** [comment]
Is it the case that the default for `relative` is still `public`? That's what I seem to observe.

**Comment by calvincestari** [comment]
> Is it the case that the default for relative is still public? That's what I seem to observe. It seems inconsistent.

Correct, default of `public` for both `relative` and `absolute` - see [`OperationsFileOutput`](https://github.com/apollographql/apollo-ios/blob/main/Sources/ApolloCodegenLib/ApolloCodegenConfiguration.swift#L323). [Here](https://github.com/apollographql/apollo-ios/blob/main/Sources/ApolloCodegenLib/ApolloCodegenConfiguration.swift#L264) is the `internal` default value for `embeddedInTarget`.

It seems inconsistent if you look only at the values but when considering the practical application of `relative` and `absolute` and how they are most likely to be generated outside of the schema types target/module then `public` makes sense.
