### ISSUE TITLE
Feat: Use swift macros for code generation when swift 5.9 is adopted.

### ISSUE THREAD

**Issue by erneestoc** [apollographql/apollo-ios#3075]
### Use case

There are some projects that do a lot of code generation outside for mocks, strings, assets, sourcery, and then apollo. Would be nice if everything was integrated in Xcode.

Apple introduced a new macro system on Swift 5.9
https://developer.apple.com/videos/play/wwdc2023/10166/
https://developer.apple.com/videos/play/wwdc2023/10167/

We could potentially stop needing an external tool and external files for the code generation for us and instead let it live in our swift code.

We'd need to investigate how to pass the schema, if we can pre-compute/cache the AST, and research the performance of doing this dynamic code generation in macros for big projects. And of course share code from the current code generator so that this is opt-in.

### Describe the solution you'd like

A freestanding macro declaration that we can use to do something like:
```swift
#generateGraphql(code: """
    query MyAwesomeQuery($string: String!) {
       ...
    }
""")
```

**Comment by AnthonyMDev** [comment]
Thanks for the suggestion @erneestoc! We were already discussing this as a possibility before the WWDC keynote was even finished! ;)

In order to help limit open issues to actionable work items, I've created a [WWDC 23 Megathread](https://github.com/apollographql/apollo-ios/issues/3078) to consolidate exploratory conversations of possible usage of new features like Macros!

I'm not sure if this is the direction we are going to head with this, but it's something we are discussing. And we'd love to have you contribute to that discussion in the megathread!

I'm going to be closing and locking this issue to help facilitate moving conversation to that thread.
