### ISSUE TITLE
Thoughts on introducing a new delegate method to WebSocketTransportDelegate

### ISSUE THREAD

**Issue by tahirmt** [apollographql/apollo-ios#3079]
### Question

We have a use case where we process messages received on the web socket at a global level through the use of a delegate method. A big case for this is that our backend would send an unauthenticated error message on the web socket in the body that we then use to kick the user out if their session expires. 

```swift
  func webSocketTransport(_ webSocketTransport: WebSocketTransport, didReceiveMessage message: (payload: JSONObject?, error: Error?))
```

I wanted to get the thoughts of the maintainers on exposing such method on `WebSocketTransport` or if you have ideas on how to achieve something similar where we process some messages differently from web socket subscriptions on the same web socket.

**Comment by calvincestari** [comment]
Hi @tahirmt. I've got a couple questions to try gain a better understanding:
* Are you using websocket for just subscriptions or all operations?
* If it's just for subscriptions then is the session expiry message just sent inbetween subscription events? In other words are you using the subscription websocket for realtime session communication?

**Comment by tahirmt** [comment]
Hi @calvincestari we are using web sockets for only subscriptions but while the app is in foreground an active web socket connection is required and if the session expires the backend sends a message on the web socket that the session expired. So yes, we can get session expiry message in realtime in-between subscription messages.

**Comment by calvincestari** [comment]
`WebSocketTransport` is the delegate because it encapsulates websocket message processing and provides an API to return a GraphQLResult, matching the other transports. It's a fairly clean API.

I don't think delegate chaining is a good idea, and it's really only wanted in your configuration because you need to be able to process _some_ websocket messages outside the scope of the subscription. Exposing the delegate methods on the transport would leak all of the regular subscription messages too.

Have you considered using another subscription for the session activity? Use the same websocket transport as your other subscription but then you can handle the responses separately and wouldn't need to expose the delegate.

**Comment by tahirmt** [comment]
That makes perfect sense. I’ll see if we can get some sort of subscription for just this purpose instead and clean this up. Thanks for the suggestion!

**Comment by tahirmt** [comment]
I wanted to add an additional thing on this. Something I didn't know was when messages like this are sent on the web socket, they are forwarded to all subscribers by Apollo with code `unprosessedEntity` with the content of the entire message so any additional processing can happen at that stage.
