### ISSUE TITLE
SwiftUI Previews broken after migration

### ISSUE THREAD

**Issue by jostster** [apollographql/apollo-ios#3105]
### Summary

We recently migrated from the pre 1.0 Apollo to 1.3. With that we needed to do several migration changes. Since then our SwiftUI Previews haven't worked and Im now trying to resolve that. I have cleaned up the test targets (for some odd xcode reason those run when building swiftui previews), but now I'm getting an error with `SQLNormalizedCache`. The SwiftUI Preview links to the crash file which shows 
```ApiService.createApolloClient(urlString:cacheFilename:) + 3352 (ApiService.swift:412)```. 
Line 412 is a `fatalError` in our code when the apollo client fails.
<img width="886" alt="image" src="https://github.com/apollographql/apollo-ios/assets/278510/6999f8b7-de20-4df6-80b4-01e9ddf6ca44">

This issue seems to only happen for Previews as it runs fine in simulator. The error message shown in Console.app is ```Fatal error: Error creating SQLite Cache: unable to open database file (code: 14)``` which appears to be caused by the `let cache = try SQLiteNormalizedCache(fileURL: cacheURL, shouldVacuumOnClear: true)`

### Version

1.3.0

### Steps to reproduce the behavior

I've done the following:
- Deleted Build Cache
- Deleted Derived Data
- Re-installed Apollo with SPM
- Restarted Xcode
- Restarted Mac
- Deleted ~/Library/Developer/Xcode/UserData/Previews

**Comment by BobaFetters** [comment]
@jostster Thanks for reporting this, we will take a look at it as soon as we can. My initial hunch is that it may have something to do with file pathing differences between simulator and previews since they would have different locations in the file system where they store data, but will have to dig in some to confirm.

**Comment by jostster** [comment]
I think xcode gets confused as there is a `Previews/Simulator Devices` and a `Previews/Simulator%20Devices`. I created a fresh application and reproduced this error, but I fixed both projects by changing the FileManager to use the documentsDirectory temporarily then changing it back to application support directory after it ran successfully. I am not able to see the sqlite3 file in the `Previews/SImulator Devices` directory even though when I print out the cacheFile URL it shows `Previews/Simulator%20Devices`.

I think we can close this as an xcode issue?

**Comment by BobaFetters** [comment]
Did a quick investigation and like you said it appears the `.documentsDirectory` works fine while the `.applicationSupportDirectory`. However, if you replace this code:
`let path = FileManager.defaults.urls(for: .applicationSupportDirectory, in: .userDomainMask).last`

with:
`let path = try FileManager.default.url(for: .applicationSupportDirectory, in: .userDomainMask, appropriateFor: nil, create: true)`

Everything appeared to work correctly in my quick testing, note that you will need to move that code inside the `do/catch`. Definitely seems to be a quirk of how the `.applicationSupportDirectory` works.

Closing this since no action is needed.
