### ISSUE TITLE
Mocking responses with raw JSON

### ISSUE THREAD

**Issue by guillianbalisi** [apollographql/apollo-ios#3179]
### Question

I am trying to convert raw JSON to the generated response type, is there an example of how to do this? I tried looking at the code example in https://www.apollographql.com/docs/ios/testing/test-mocks/#mocking-graphql-responses-with-json but the `data` variable does not compile due to error
```
Cannot convert value of type '[String : Any]' to expected dictionary value type 'String'
```
which I'm getting as well with my mock JSON.

**Comment by AnthonyMDev** [comment]
Hi @guillianbalisi. I'm sorry we didn't see this question earlier! In order to understand what's going wrong, I'd need to see an example of your code here.

If nothing in the docs helps with what you're seeing, please consider posting in our [Discord server](https://discord.gg/graphos) or our [Community Forum](https://community.apollographql.com/). The maintainers and other Apollo users are active on those platforms, they're great places to ask for help using Apollo iOS. In an effort to keep our Issues actionable, we're closing this Issue for now but please do feel free to re-open if there's a bug, documentation update, or feature idea that we should consider!
