### ISSUE TITLE
Apollo.JSONDecodingError.missingValue error

### ISSUE THREAD

**Issue by jesdvlpr** [apollographql/apollo-ios#3216]
### Question

Hi, I’m using Apollo Client on iOS. I have a query where I don’t receive an attribute declared inside of it, and then I get an error: _Apollo.JSONDecodingError.missingValue_. Sometimes, this attribute is received in the response, but sometimes not. Can this attribute return an empty string by default without generating an error when it is not received in the response?

**Comment by calvincestari** [comment]
Hi @jesdvlpr 👋🏻 

> I have a query where I don’t receive an attribute declared inside of it, and then I get an error: Apollo.JSONDecodingError.missingValue. Sometimes, this attribute is received in the response, but sometimes not.
> Can this attribute return an empty string by default without generating an error when it is not received in the response?

What is the field type declared as in your schema? If the field type is specified as non-null, with the bang (`!`), then the field must be included in the response otherwise it is an invalid GraphQL response. Apollo iOS strictly conforms to what the specified schema field type is because that is what the generated models will require.

If the field is non-null and your server is excluding it from the response sometimes then there is nothing Apollo iOS can do about that; it is a valid error and you'll need to speak with your backend team about why it's not included with every response.

**Comment by jesdvlpr** [comment]
hi! thanks @calvincestari 

In .graphql.swift, I don’t have a field as non-null with the code that was automatically generated

```
public struct ContactInformation: MySchema.SelectionSet {
        public let __data: DataDict
        public init(_dataDict: DataDict) { __data = _dataDict }

        public static var __parentType: Apollo.ParentType { MySchema.Objects.ContactInformation }
        public static var __selections: [Apollo.Selection] { [
          .field("__typename", String.self),
          .field("countryCode", String?.self),
          .field("countryName", String?.self)
        ] }

        public var countryCode: String? { __data["countryCode"] }
        public var countryName: String? { __data["countryName"] }
      }

```
In my SDL file (.graphqls), my type is 

```
type ContactInformation {
  countryCode: String
  countryName: String
}
```

I'm getting Apollo.JSONDecodingError.missingValue with the field without the bang (!)

**Comment by jesdvlpr** [comment]
Thanks @calvincestari 

Why Apollo Client on Android is this response processed without errors?

**Comment by calvincestari** [comment]
> Why Apollo Client on Android is this response processed without errors?

I'm not sure why Apollo Kotlin allows the missing value but [here is the section of the GraphQL spec](https://spec.graphql.org/draft/#sec-Value-Completion) that states how values should be completed during field execution. Apollo iOS conforms to the spec and expects GraphQL servers to do the same.

There is nothing in there that allows for missing fields. The only time a field should be allowed missing is if it's part of an `@include`/`@skip` directive.

**Comment by jtwigg** [comment]
@calvincestari While you are surely correct about the reference to the specification, what teams are finding in practice is
a) There is an asymmetry between Apollo Kotlin on Android's support and fault tolerance. So changes that are breaking on iOS are not on Android.

b) It makes serialization of JSON to disk almost impossible since and addition of an optional field means the JSON will fail to deserialize. _**If you have an alternative fault tolerant method of deserialization I'm all ears**_

**Comment by calvincestari** [comment]
> a) There is an asymmetry between Apollo Kotlin on Android's support and fault tolerance. So changes that are breaking on iOS are not on Android.

@jtwigg you'll need to take it up with the Apollo Kotlin team why the Kotlin SDK is allowing missing fields; I can ask them but I suggest you reach out too. It remains that a response with missing fields is an invalid GraphQL response and Apollo iOS expects a spec-valid response from any GraphQL server it connects to. What GraphQL server are you using?

**Comment by calvincestari** [comment]
I disagree that his is "fault tolerance". A missing field may seem innocuous enough but what other parts of the spec has the server implementation deviated from and how is a client meant to detect that? The spec exists to ensure interoperability between different implementations.

**Comment by jtwigg** [comment]
@calvincestari 
> What GraphQL server are you using?

The problem is not with a response coming from a GraphQL Server, which reliably returns the `field: null` when appropriate but rather

a) **static JSON files used for Unit Tests:** This is at worst annoying but fixable by search/replaces.
b) **Caching GraphQL server responses to disk**: This is almost entirely impossible using the iOS SDK. The cache data becomes useless after every app update where a query field has been added, even if optional.

A deserialization from JSON flag that can tolerate missing `null` fields would be very valuable for those two scenarios.

**Comment by calvincestari** [comment]
> The problem is not with a response coming from a GraphQL Server, which reliably returns the `field: null` when appropriate but rather

OK, this makes more sense now.

> a) **static JSON files used for Unit Tests**: This is at worst annoying but fixable by search/replaces.
> b) **Caching GraphQL server responses to disk**: This is almost entirely impossible using the iOS SDK. The cache data becomes useless after every app update where a query field has been added, even if optional.

If the unit tests are using JSON to be parsed and turned into generated models then the JSON must match what would be a response to match the updated generated code. This is because we parse and execute on the JSON passed in so it's treating it the same as if it came from a server, i.e.: expecting it to be in the same shape as a valid response.

If you have a standard network interceptor pipeline and aren't doing any of your own processing in there for which you want to test, you might have better luck using the selection set initializers for your unit tests.

**Comment by ediazest** [comment]
Hi @calvincestari 
>b) Caching GraphQL server responses to disk: This is almost entirely impossible using the iOS SDK. The cache data becomes useless after every app update where a query field has been added, even if optional.

I was wondering if you have any good recommendations for this part and how to overcome this limitation.

We are also experiencing this issue, and in our use case, it is very important that users are still able to use their apps offline, as it is not guaranteed that they will be online when they first open the app.

**Comment by calvincestari** [comment]
> I was wondering if you have any good recommendations for this part and how to overcome this limitation.

@ediazest - if the query changed then unfortunately the cache data won't pass execution so it's going to be regarded as stale and no longer accurate. If the cache data can't be refreshed through a server response then currently the only alternative is a manual update to the cache data adding the new field.

> We are also experiencing this issue, and in our use case, it is very important that users are still able to use their apps offline, as it is not guaranteed that they will be online when they first open the app after an update.

What would be the solution here for a non-null field that was added to an existing query?

**Comment by rr-alvin-lee** [comment]
@calvincestari  Sorry to bother you over this closed topic but,

In the [GraphQL spec](https://spec.graphql.org/draft/#sec-Non-Null) specification it says:

> [Nullable vs. Optional](https://spec.graphql.org/draft/#sec-Non-Null.Nullable-vs-Optional)
> Fields are always optional within the context of a [selection set](https://spec.graphql.org/draft/#selection-set), a field may be omitted and the selection set is still valid (so long as the selection set does not become empty). However fields that return Non-Null types will never return the value null if queried.

Shouldn't we only throw a missingValue error if the field is marked as non-null?

**Comment by calvincestari** [comment]
Hi @rr-alvin-lee, it's been a while since I looked at this issue but I think you're confusing _selection set_ vs. _response_.
* A _selection set_ is what your operations are built from. _Optional_ in this context means that you do not need to query every field on a type, you can fetch only what you need.
* In a _response_ however every field from the selection set must have an entry in the response map - [GraphQL spec](https://spec.graphql.org/draft/#sec-Executing-Fields). Therefore any field not present in the response should throw a `missingValue` error.

**Comment by rr-alvin-lee** [comment]
@calvincestari I see, thanks for educating me.

**Comment by gggsingh** [comment]
@calvincestari is there any way to use the generated mocks to create a response json that will include the null values?

Additional context: We are trying to use [this](https://medium.com/@dilsreccse/ios-xcuitest-swift-automation-mock-server-setup-for-graphql-queries-3188f9526501) approach for testing with a modification to the response json file. Instead of storing the hardcoded response in a json file we are trying to create that response object using the generated mocks:

```
var something = Mock<UpdateSomethingResponse>(
    updated: "Something"
)
    
GraphQLResult(
    data: UpdateSomethingMutation.Data.UpdateSomethingResponse.from(something),
    extensions: nil,
    errors: nil,
    source: .server,
    dependentKeys: nil
).asJSONDictionary())
```
            
But this fails because some of the mock objects have optional values that are dropped in the resulting json. Ultimately leading to the `Apollo.JSONDecodingError.missingValue` error

**Comment by calvincestari** [comment]
> is there any way to use the generated mocks to create a response json that will include the null values?

No, the mock objects were not designed to be used that way. While response data can be used to build a model object the reverse is not possible; you cannot use a model object to generate a response. Admittedly we do not have a good, easy to use network test API.

If your goal is to be able to pass responses back into your network layer for testing then I'm afraid you're stuck with JSON for now. This is something we'll improve on in the 2.x release.

**Comment by jtwigg** [comment]
@calvincestari 
> What would be the solution here for a non-null field that was added to an existing query?

I very much agree that this is an unrecoverable situation that warrants a throw. 
The GraphQL server will throw until the nearest optional value in a _fault tolerant_ fashion.

Fault tolerant here means the whole query doesn't fail because a part it does. I feel GQL is sympathetic to this philosophy, given you can query a large data graph of disparate items that are evolving in different ways.

**Comment by calvincestari** [comment]
> The GraphQL server will throw until the nearest optional value in a _fault tolerant_ fashion.
> 
> Fault tolerant here means the whole query doesn't fail because a part it does. I feel GQL is sympathetic to this philosophy, given you can query a large data graph of disparate items that are evolving in different ways.

I agree with you regarding fault tolerance and how nulls bubble up the parent selection set.

This issue is about a missing field in a response though, and there is nothing in the spec that says a missing response field should be treated as null.

**Comment by jtwigg** [comment]
@gggsingh 
> is there any way to use the generated mocks to create a response json that will include the null values?

In the past we've setup a mock GraphQL server/CLI in `< 50` lines of code which will very simply:

a) Given a Schema
b) Given a mock.json payload

you can query it and it'll just return the mock data with the desired alterations

i) It'll fill in the missing `null` values
ii) It'll support field [aliasing](https://www.apollographql.com/docs/kotlin/advanced/using-aliases/#using-aliases-to-avoid-name-clashes). 

The reason it doesn't work for my situation is its difficult to get this Node Service/CLI to work properly integrated with Unit Tests. And it doesn't help at all for caching data to disk.
