### ISSUE TITLE
how pass array of objects in mutation

### ISSUE THREAD

**Issue by mitesh53** [apollographql/apollo-ios#322]
how I can send array of objects in mutation in swift 4 please provide solution ASAP??

**Comment by designatednerd** [comment]
Hey @mitesh53, I'm sorry we didn't get to this question until now. Usually you have to have a GraphQL statement that accepts an array of objects in order to have code generate in Swift that allows you to pass an array of objects. 

I'm going to close this out and ask you to post any follow-ups in our [Spectrum Chat](https://spectrum.chat/apollo/apollo-ios?tab=posts) if you're still having issues. Usually that'll get you a much faster response since other members of the community can help there as well.
