### ISSUE TITLE
Color me surprised

### ISSUE THREAD

**Issue by frangrolemund** [apollographql/apollo-ios#3229]
### Question

To give you some background, I've been working with the Apollo Client for iOS and Apollo server for about 3 years now and generally had no complaints.  It was reliable and fairly easy to integrate.    

Like many iOS devs I prepare for the new versions of the core platform from June until September of each year, where I also do upgrades of all my third-party libraries, including Apollo.

This year I noticed two things as I started my upgrade from Apollo Client `v0.53.0`:

- The versions after v0.53.0 (eg. 1.0.0, 1.1.0, etc) are completely incompatible with it.
- There are **breaking** changes reported routinely in each of the subsequent point releases.

Both of these facts are very alarming considering that (1) the official `1.0.0` [release](https://github.com/apollographql/apollo-ios/releases/tag/1.0.0) came out in October, well after any migration  for iOS16 would have happened, (2) somehow version 1.0 is incompatible with the point releases leading up to it and (3) unlike every software product I've ever known, individual point releases can break API contract.

....

My question is simply this, should I expect this type of rapid change and uncertainty from the Apollo software infrastructure moving forward?   I can certainly respect aggressive development, but the significant and poorly managed architectural shifts over 2023 have put my work into a very difficult position and make me question continued investment in your platform.

**Comment by calvincestari** [comment]
Hi @frangrolemund

> The versions after v0.53.0 (eg. 1.0.0, 1.1.0, etc) are completely incompatible with it.

Version 1.0 was a significant investment in rethinking the generated models based on feedback from users and what we believe is a better API design with improved performance. We wrote a [1.0 migration guide](https://www.apollographql.com/docs/ios/migrations/1.0) that describes the significant changes for this major version of Apollo iOS and a walk-through of migrating an existing project from Apollo iOS 0.x to 1.0. It's not unreasonable that major version releases are not backwards compatible and 1.0 will not be the last major release that is incompatible with the previous major version.

> There are breaking changes reported routinely in each of the subsequent point releases.

This is a deviation from traditional semver but yes, there have been breaking changes in some minor releases. Our goal is to not have to do this often despite what the 1.x track record of that is. Sometimes it's unavoidable and we don't want to jump to another major version for the release.

Our threshold for breaking minor releases is that it should not require any significant refactoring of your own code, as 1.0 would require. Instead, and as demonstrated in the migration guides for [1.2](https://www.apollographql.com/docs/ios/migrations/1.2) and [1.3](https://www.apollographql.com/docs/ios/migrations/1.3), the changes required are minimal.

> Both of these facts are very alarming considering that (1) the official 1.0.0 [release](https://github.com/apollographql/apollo-ios/releases/tag/1.0.0) came out in October, well after any migration for iOS16 would have happened

Our release cycle is not bound to any iOS release and I don't believe you are required to update to Apollo iOS 1.0 in order to build for the latest iOS SDK; it is always your choice which version of Apollo iOS you want to use. Version 1.0 is the base from which we will be doing all future development though.

> Like many iOS devs I prepare for the new versions of the core platform from June until September of each year, where I also do upgrades of all my third-party libraries, including Apollo.

There is a lot of work through the rest of the year that you're missing out on and if you're going to do annual updates simply moving to the latest released version would make any minor version breaking changes irrelevant. Between now and June/Sept next year you can expect another major version release with more backwards incompatible changes.
