### ISSUE TITLE
React way of pagination?

### ISSUE THREAD

**Issue by BobaFetters** [apollographql/apollo-ios#3255]
Moving this issue over from the `apollo-ios-pagination` repo:

From: @teodorpenkov

I've seen several comments in the apollo-ios repo about an Initial query and merging subsequent queries' data into the first one (similar to the react way of pagination) in order to perform pagination.

Is this an option in Apollo iOS? If not - why not?

**Comment by AnthonyMDev** [comment]
The `apollo-ios-pagination` project, that this issue originated from is working on providing this functionality. That project is still under construction, but you are welcome to try it out and give feedback while the work continues.

We are going to be keeping all discussion of features for the entire `apollo-ios` family of packages and repositories here in the issues for the `apollo-ios` core repo. Which is why @BobaFetters copied this question here from the other repo.

I think this is a complete answer to your question, so I'm going to close this issue now. But please follow along with the development of this feature in the `apollo-ios-pagination` repo!
