### ISSUE TITLE
Test mock output will add import "TargetName" even the schemaType is defined as embeddedInTarget

### ISSUE THREAD

**Issue by Cookiezby** [apollographql/apollo-ios#3262]
### Summary

I am trying to use apollo-cli to generate the mock file in a single swift package, but I found when I define the test output in the config json using absolute, in the generated mock object file, there will be `"import MyAPI"` which should not appear, since the MyAPI is only a namespace when I use `embeddedInTarget` in a single target 

I locate the source code in code gen module
https://github.com/apollographql/apollo-ios-codegen/blob/f2bbc9aaa5c128291caf57f8687fa91ae3fe8277/Sources/ApolloCodegenLib/Templates/TemplateRenderer.swift#L298

### Version

1.5.2

### Steps to reproduce the behavior

1. Create a Swift Package MyAPI
2. In the MyAPI, add apollo ios as dependency and update the code gen configure file use `embeddedInTarget` for the `schemeType` and use `absolute` for the `testMock` 
```
 "schemaName": "MyAPI"
 "output" : {
        "testMocks" : {
            "absolute": {
                "path": "./generated",
                "accessModifier": "public"
            }
        },
        "schemaTypes" : {
            "path" : "./generated/mock/",
            "moduleType" : {
                "embeddedInTarget": {
                    "name": "MyAPI",
                    "accessModifier": "public"
                }
            }
        },
        "operations" : {
            "inSchemaModule" : {
            }
        }
    }

```

**Comment by calvincestari** [comment]
Hi @Cookiezby - test mocks are **always** treated as an individual separate module. Even when using the `absolute` configuration option it is expected that you have created a module that will contain only the generated test mocks.

Your issue is based on the assumption that by using the `absolute` configuration the test mocks module can be the same module that is being created for the schema types. It was not designed to work this way which is why your seeing the build error because importing the schema module is required since they're intended to be separate modules.

I think we definitely need to make that clearer in the documentation for `absolute` but I'm not sure we'll want to allow the kind of configuration you're proposing here.

**Comment by Cookiezby** [comment]
@calvincestari Thanks for the explanation, and adding document for the absolute configuration, I will try to use the mock file in different module!
