### ISSUE TITLE
Apollo in an Objective-C project

### ISSUE THREAD

**Issue by jeromeDms** [apollographql/apollo-ios#327]
Dear all
I'm using an objective-C project, and was wondering what would be the best way to use this library ?
I read different posts here but I did not find a clear answer to integrate this Apollo in a full objective-C project.
Anybody here successfully used the SWIFT Apollo in a full Obj-C environment ?
Any help would be greatly appreciated.
Thanks

**Comment by Ewg777** [comment]
Hi @jeromeDms,

Did you find any solution?

**Comment by jeromeDms** [comment]
@Ewg777 no, I gave up

**Comment by Ewg777** [comment]
Russians never give up

**Comment by jeromeDms** [comment]
@Ewg777 I'm French, so I gave up :-)

**Comment by designatednerd** [comment]
Hey all, just as a heads up, we've officially decided not to do official Obj-C support at this time since Swift is (finally!) ABI stable and is about to be module stable. 

There's probably some ways to work around this by creating an `@objc` wrapper that exposes some method to the Obj-C runtime, but unfortunately that won't be something we're supporting directly at the moment. 

I'm gonna close this out, please feel free to stop by our [Spectrum Chat](https://spectrum.chat/apollo/apollo-ios?tab=posts) if you have any further questions!
