### ISSUE TITLE
Please remove warnings in code

### ISSUE THREAD

**Issue by PatrickDanino** [apollographql/apollo-ios#3301]
Is it possible to clarify why the Apollo SDK code includes warnings in the codebase?

For those of us that treat warnings as errors, this is rather distracting and not something we (customers) should have to worry about, particularly if it's a "TODO".

https://github.com/apollographql/apollo-ios/blame/0c0a9903a55710fa1708068ef91a017236467ff8/Sources/ApolloAPI/DataDict.swift#L51

**Comment by calvincestari** [comment]
Hi @PatrickDanino - there's no clarification, they shouldn't be there because of exactly the reason you stated.

We have a test suite that builds against the `main` branch and _should_ be failing on any warnings being emitted. When I run that test script locally I can see the warnings emitted but it's not failing as it should be. I'll look into this and get it fixed up. Thanks for reporting the issue and apologies for the inconvenience.

**Comment by PatrickDanino** [comment]
Appreciate the quick response!

**Comment by calvincestari** [comment]
@PatrickDanino the warning should now be gone from `main` and we've got our tests working again that will alert us to this again in the future.
