### ISSUE TITLE
Is Swift 5.9 required for Apollo 1.8.0?

### ISSUE THREAD

**Issue by bddq** [apollographql/apollo-ios#3315]
### Question

Hi,

I noticed you updated the required version of Swift to use Apollo on 1.8.0 version.
Is Swift 5.9 really needed or can it be changed back to Swift 5.7 version to allow old versions of Xcode to use the package?

Regards,
Benoit

**Comment by calvincestari** [comment]
Hi @bddq - yes it is required because the SPM plugin now [declares](https://github.com/apollographql/apollo-ios/blob/main/Package.swift#L67) the permission `allowNetworkConnections(scope:reason:)`. It is that permission [which requires SwiftPM 5.9+](https://developer.apple.com/documentation/packagedescription/pluginpermission/allownetworkconnections(scope:reason:)).

Is there any particular reason you need to use an older version of Xcode?

**Comment by calvincestari** [comment]
I just realized that the change to the plugin and the new requirement isn't included in the release notes - I'll update that now.

**Comment by bddq** [comment]
We are still using Xcode 14.2 to build some apps at work and we are blocked with Swift 5.7. 
I understand your answer. 

Thanks!
