### ISSUE TITLE
There can be only one directive named "@defer".-GraphQLSchemaValidationError@

### ISSUE THREAD

**Issue by xLuciferSx** [apollographql/apollo-ios#3316]
### Summary

Unable to generate new swift files due to this issue - There can be only one directive named "@defer".-GraphQLSchemaValidationError@

After updating to Apollo CLI 1.8.0, it continues to fail to generate the code.

<img width="929" alt="Screenshot 2024-01-14 at 16 36 57" src="https://github.com/apollographql/apollo-ios/assets/10944243/3b33921e-1346-4cf8-9b1c-8bb3e89d498f">

### Version

1.8.0

### Steps to reproduce the behavior

run apollo-ios-cli generate command

**Comment by calvincestari** [comment]
Hi @xLuciferSx - I cannot reproduce this error when targeting the `1.8.0` release, see this [sample project](https://github.com/apollographql/apollo-ios/files/13933289/issue3316.zip). If you're able to consistently reproduce the error please provide a sample application we can use.

From the [last commit to the `apollo-ios-codegen` repo](https://github.com/apollographql/apollo-ios-codegen/commit/c7b03c2ba5bd70974189ee8d7e699cbe10eefdc7) this error should not be possible since the code we had to add the `@defer` directive has been removed. The only way it _could_ still be produced is if the schema declared two of the same directive but I believe that would have been an error in previous versions too.

**Comment by calvincestari** [comment]
That would be great, thank you. Send it to calvin.cestari@apollographql.com.

**Comment by xLuciferSx** [comment]
> calvin.cestari@apollographql.com

Email sent.

**Comment by calvincestari** [comment]
I've received it. I'll take a look and get back to you.

**Comment by calvincestari** [comment]
Your schema declares two `@defer` directives; one on line 6 and the other on line 27. Remove one of them and `generate` works as expected.
