### ISSUE TITLE
The operation couldn’t be completed. (OSStatus error -9847.)

### ISSUE THREAD

**Issue by BraveEvidence** [apollographql/apollo-ios#3339]
### Summary

I am trying to use Subscription on iOS simulator and I get error saying The operation couldn’t be completed. (OSStatus error -9847.)

### Version

1.9.0

### Steps to reproduce the behavior

https://github.com/BraveEvidence/iossubscription

### Logs

```shell
The operation couldn’t be completed. (OSStatus error -9847.)
```

### Anything else?

Is this a simulator issue? I don't have a real device to test on. I tried checking on https://www.osstatus.com and the error name is errSSLRecordOverflow

**Comment by calvincestari** [comment]
Hi @BraveEvidence - try using the `ws` protocol instead of `wss` for the [websocket server address](https://github.com/BraveEvidence/iossubscription/blob/main/myfourthapp/Network.swift#L19). It's unlikely your local host is serving WebSocket Secure which would be like using `https` locally.

**Comment by BraveEvidence** [comment]
Thank you @calvincestari for your reply. I tried changing the protocol to `ws` and now I get error saying `"The operation couldn’t be completed. (ApolloWebSocket.WebSocket.WSError error 1.)"`

Any suggestions

**Comment by BraveEvidence** [comment]
@calvincestari  I am using [graphql-ws](https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md) protocol. The subscriptions works fine on Android with Apollo Kotlin

**Comment by calvincestari** [comment]
You still need to make sure you're selecting the correct protocol [when initializing the websocket](https://www.apollographql.com/docs/ios/docc/documentation/apollowebsocket/websocket/init(request:protocol:)). If you're already doing that then you'll need to do some more debugging on your side to determine what else could be wrong; is there anything else in the logs besides the `WSError`?

**Comment by BraveEvidence** [comment]
No other logs

**Comment by calvincestari** [comment]
If you can replicate this in a sample client then I can try with a websocket service locally to see if anything else if incorrect in the client. It's difficult to debug from that single error response.

**Comment by BraveEvidence** [comment]
Can you check  my [sample](https://github.com/BraveEvidence/iossubscription) repo over here

**Comment by calvincestari** [comment]
I just took a look at the project now and I think you are using the wrong websocket subprotocol. In the `Network.swift` file you're [using the `.graphql_ws` protocol](https://github.com/BraveEvidence/iossubscription/blob/main/myfourthapp/Network.swift#L20). Note that the initializer requires you to specify the name of the subprotocol and **not** the name of the library.

> I am using [graphql-ws](https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md) protocol. The subscriptions works fine on Android with Apollo Kotlin

graphql-ws is the name of the library but the protocol that it uses is `graphql-transport-ws`. You can see this in the first line of the [Communication](https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md#communication) heading in that protocol document you linked to.
> The WebSocket sub-protocol for this specification is: `graphql-transport-ws`.

This is confusing because the two packages have terrible library names that are too similar to the subprotocol names. [The `WSProtocol` enum in the Apollo iOS documentation](https://www.apollographql.com/docs/ios/api/ApolloWebSocket/enums/WebSocket.WSProtocol/) has details about which is supported by which library.

Change the subprotocol in the `Network.swift` file to `.graphql_transport_ws` and I think it should work for you.

**Comment by BraveEvidence** [comment]
@calvincestari Thank you for all the help
