### ISSUE TITLE
Response value getting nil

### ISSUE THREAD

**Issue by Rushabh5** [apollographql/apollo-ios#3385]
### Question

I am adding a Token in the TokenAddingInterceptor file but that response value is nil so how can I get the response value?

```
class NetworkInterceptorProvider: DefaultInterceptorProvider {
    override func interceptors<Operation: GraphQLOperation>(for operation: Operation) -> [ApolloInterceptor] {
        var interceptors = super.interceptors(for: operation)
        interceptors.insert(TokenAddingInterceptor(), at: 0)
        return interceptors
    }


    override func additionalErrorInterceptor<Operation: GraphQLOperation>(for: Operation) -> ApolloErrorInterceptor? {
        return nil
    }

}
```

**Comment by calvincestari** [comment]
HI @Rushabh5 - I assume the token is required to be able to execute the query which means it should be added to the request, not the response.

If you are really needing to modify the response then you will need to add your interceptor after the `NetworkFetchInterceptor` because [that is where the request actually gets sent](https://github.com/apollographql/apollo-ios/blob/main/Sources/Apollo/NetworkFetchInterceptor.swift#L39), so there will only be a valid `response` object _after_ that interceptor.
