### ISSUE TITLE
Xcode 15 Beta "Expression" name collision

### ISSUE THREAD

**Issue by WolframPRO** [apollographql/apollo-ios#3393]
### Summary

<img width="1104" alt="Screenshot 2024-06-11 at 16 11 51" src="https://github.com/apollographql/apollo-ios/assets/27895476/2cc55053-a7a7-4447-8398-c22a5b7905c2">
<img width="886" alt="Screenshot 2024-06-11 at 16 12 22" src="https://github.com/apollographql/apollo-ios/assets/27895476/9934643e-b948-4fb8-919c-cad76c6929ed">

Starts iOS 18 foundation has Expression too, it seems that there is name collision here

### Version

1.12.2

### Steps to reproduce the behavior

Install Xcode 15 Beta, build

**Comment by WolframPRO** [comment]
Looks like fixed here: https://github.com/apollographql/apollo-ios/pull/3391

**Comment by WolframPRO** [comment]
https://github.com/apollographql/apollo-ios/pull/3391

**Comment by calvincestari** [comment]
@WolframPRO - #3391 was auto-closed by a GitHub Action because we don't accept PRs into [apollo-ios](https://github.com/apollographql/apollo-ios) any more, they need to go through [apollo-ios-dev](https://github.com/apollographql/apollo-ios-dev) instead. So the correct PR for the fix is https://github.com/apollographql/apollo-ios-dev/pull/386.
