### ISSUE TITLE
Crash Thread 1: Fatal error: No data found for task 1, cannot append received data

### ISSUE THREAD

**Issue by KhaledElsherbeny** [apollographql/apollo-ios#3409]
### Summary

crash occurred randomly while starting calling query

<img width="1436" alt="Screenshot 2024-07-11 at 4 16 18 PM" src="https://github.com/apollographql/apollo-ios/assets/55990909/f35e45b1-7da2-4f05-b7b8-1fdbeaaea2b3">

### Version

1.13.0

### Steps to reproduce the behavior

crash occurred randomly while starting calling query

<img width="1436" alt="Screenshot 2024-07-11 at 4 16 18 PM" src="https://github.com/apollographql/apollo-ios/assets/55990909/ca1b6230-b725-4abb-9d3d-9343bd27ed16">

**Comment by AnthonyMDev** [comment]
Interesting! I don't think we've ever had anyone hit this assertion failure before! It's possible there is a race condition going on here, but I would need more information in order to determine what's going on here. 

Are you using a custom `InterceptorProvider`? I might need some more example code or a reproduction case to dig into this.

**Comment by calvincestari** [comment]
@KhaledElsherbeny is this a consistent crash? Is it reproducible?

**Comment by calvincestari** [comment]
The cause of the assertion is that the [internal task (`TaskData`)](https://github.com/apollographql/apollo-ios-dev/blob/main/apollo-ios/Sources/Apollo/TaskData.swift) related to the `URLSessionDataTask` cannot be found. We use the `TaskData` instance to store the response, data and completion handlers for the request; I thought we should maybe send a request failure result instead of asserting but without `TaskData` we don't have a completion block so an assertion might be the only thing we can do here otherwise it would just fail silently.

There are a number of ways the internal task data can be removed:
1. A call to `invalidate` which essentially kills the session client so this is a pretty severe action. The only place we call this method is when the `DefaultInterceptorProvider` is released (`deinit`) and that is further controllable through the `shouldInvalidateClientOnDeinit` property.
2. A call to `clear(task:)` which is called when a task is cancelled or completes. I don't believe we ever make the call to cancel a task.
3. A call to `clearAllTasks` which is called by `invalidate` or when #4 occurs.
4. `URLSession` being invalidated through the [delegate call `urlSession(_:didBecomeInvalidWithError:)`](https://developer.apple.com/documentation/foundation/urlsessiondelegate/1407776-urlsession)

I recommend checking whether you call any of those methods in your own code. Also trying to nail down the circumstances of, and how reproducible, the error is would be helpful in tracking down the root cause.

**Comment by AnthonyMDev** [comment]
@KhaledElsherbeny were you ever able to resolve this one? We're going to need some more information on this in order to determine if there is a bug in our code and how to resolve it.

We're closing this for now due to inactivity, but we will be happy to re-open if you respond with additional information.
