### ISSUE TITLE
CacheKeyInfo with a numeric jsonValue of `1` returns nil

### ISSUE THREAD

**Issue by davbeck** [apollographql/apollo-ios#3414]
### Summary

If an object has an id of `1` and that is used to create `CacheKeyInfo`, it will return `nil`. The issue seems to be that it gets cast to a `Bool` in `ObjectData.swift:30`. Swift casting will convert any number with a value of 0 or 1 to a Bool when asked (`(1 as AnyHashable) as? Bool` will resolve to `true`).

### Version

v1.13.0

### Steps to reproduce the behavior

I modified `test__schemaConfiguration__givenData_whenUnknownType_withCacheKeyInfoForUnknownType_shouldReturnInfoWithTypeName` and was able to reproduce the issue with the following:

```swift
let object: JSONObject = [
  "__typename": "Omega",
  "id": 1
]

let objectDict = NetworkResponseExecutionSource().opaqueObjectDataWrapper(for: object)
let actual = MockSchemaMetadata.cacheKey(for: objectDict)

expect(actual).to(equal("Omega:1"))
```

**Comment by calvincestari** [comment]
Hi @davbeck - I don't think that test is failing in the way that you think it is. If you substitute `ω` for `1` the test fails because the resulting cache key is `Omega:1` instead of the expected `Omega:ω`. That does not mean that `CacheKeyInfo` is returning `nil` because otherwise the whole cache key would be `nil`.

Are you able to replicate this in a standalone sample project that we can use to debug?

**Comment by AnthonyMDev** [comment]
We've talked through this and verified this is a bug. We'll look into a fix for the next patch release. Thanks for the report!

**Comment by calvincestari** [comment]
This is fixed and will be included with the next release.
