### ISSUE TITLE
1.14.0 using introspection creates duplicate defer directive 

### ISSUE THREAD

**Issue by loganblevins** [apollographql/apollo-ios#3417]
### Summary

See https://github.com/apollographql/apollo-ios/issues/2395#issuecomment-2246074517

### Version

1.14.0

### Steps to reproduce the behavior

I cannot share our private schema, but our schema line 1 contains directive defer.

Then I run introspection on 1.14.0 and it makes yet another defer directive and the json schema validation fails.

**Comment by calvincestari** [comment]
@loganblevins, I'm not able to replicate the error you describe when the schema only has a single defer directive definition. [Here is a sample project](https://github.com/user-attachments/files/16354475/test-duplicate-defer-directive.zip) I put together that contains three schemas:
* the first (`single-directive-schema.graphqls`) has a single defer directive definition and codegen completes as expected without error.
* the second (`multiple-directive-schema.graphqls`) has multiple defer directive definitions and fails codegen as expected with the error you describe. The second definition in that file is the one you shared in [your comment on #2395](https://github.com/apollographql/apollo-ios/issues/2395#issuecomment-2246074517).
* the third (`no-directive-schema.graphqls`) has no defer directive definition and codegen completes as expected without error.

We also have [a test on our `GraphQLCompiler` module](https://github.com/apollographql/apollo-ios-dev/blob/main/apollo-ios-codegen/Sources/GraphQLCompiler/JavaScript/src/__tests__/deferDirectiveTests.ts#L170) to detect this scenario and fail CI if our logic for this behaviour is changed. [All tests passed](https://github.com/apollographql/apollo-ios-dev/actions/runs/10014410662) on the release PR for `1.14.0`.

If you're able to change the sample project to fail in the same way as you're seeing it would help in debugging this further. Otherwise if your schema is large it may be worth doing another search for `directive @defer` to ensure it's not buried somewhere deeper in the schema.

> Then I run code gen on 1.14.0 and it makes yet another defer directive and the json schema validation fails.

What leads to you to believe that codegen is adding another directive definition? I don't think we output the schema, or store it locally for inspection, at any stage of code generation.

**Comment by calvincestari** [comment]
> @calvincestari Thanks for quick reply! Is there a way I can disable this experimental feature in meantime? I couldn't find that key for my config json

No, there is no way to disable defer support. If there are no operations that use the defer directive then codegen outputs models as previous versions.

**Comment by loganblevins** [comment]
@calvincestari Here is my json config for context:

```
{
  "schemaNamespace" : "Federation",
  "input" : {
    "operationSearchPaths" : [
      "./Schema/**/*.graphql"
    ],
    "schemaSearchPaths" : [
      "./Schema/**/*.graphqls"
    ]
  },
  "output" : {
    "testMocks" : {
      "none" : {
      }
    },
    "schemaTypes" : {
    "path" : "./Sources/FederationAPI/Generated/Federation",
      "moduleType" : {
        "embeddedInTarget" : {
          "name" : "FederationAPI"
        }
      }
    },
    "operations" : {
      "inSchemaModule" : {
      }
    }
  },
  "schemaDownloadConfiguration": {
      "downloadMethod": {
          "introspection": {
              "endpointURL": "https://api.angelstudios.io/graphql",
              "httpMethod": {
                  "POST": {}
              },
              "includeDeprecatedInputValues": false,
              "outputFormat": "SDL"
          }
      },
      "downloadTimeout": 60,
      "headers": [],
      "outputPath": "./Schema/schema.graphqls"
  }
}
```

**Comment by loganblevins** [comment]
@calvincestari Here is my script I run to introspect and run code gen.

This command on 1.14.0 is creating the duplicate defer directive in my schema file.

```
if ! [ -x "$(command -v ./apollo-ios-cli)" ]; then
  echo 'apollo-ios-cli is not installed..installing now.'
  swift package --allow-writing-to-package-directory apollo-cli-install
fi

./apollo-ios-cli generate --verbose --path .././apollo-codegen-config.json --fetch-schema
```

**Comment by loganblevins** [comment]
> If you're able to change the sample project to fail in the same way as you're seeing it would help in debugging this further. Otherwise if your schema is large it may be worth doing another search for `directive @defer` to ensure it's not buried somewhere deeper in the schema.


I mentioned in the other GH thread that our schema file already contains a defer directive prior to updating to 1.14.0 and the above command I run is adding another one.

**Comment by loganblevins** [comment]
Sorry if I said code gen... I run the plugin CLI tool with introspect and code gen at once so it may just be the introspect step that is the issue

**Comment by calvincestari** [comment]
OK, so is it the schema file that's output from the `--fetch-schema` stage that contains two defer directive definitions?

That schema file is simply the result of introspection and output. There is no defer-related manipulation done to the schema before output.

**Comment by loganblevins** [comment]
@calvincestari that is correct but only on 1.14.0

If I revert back to my prior tag 1.12.0 and introspect the diff is unchanged.
If I introspect on 1.14.0 my diff shows 
<img width="855" alt="Screenshot 2024-07-23 at 16 56 49" src="https://github.com/user-attachments/assets/3c27cea8-7f80-404b-bb07-74c5f6ee87a9">

**Comment by loganblevins** [comment]
<img width="761" alt="Screenshot 2024-07-23 at 16 57 47" src="https://github.com/user-attachments/assets/6efbf12c-a8a2-48b8-a3ab-db96ed90d358">


This directive is already in my schema file prior to introspecting on 1.14.0....but 1.14.0 adds on a duplicate

**Comment by calvincestari** [comment]
This is certainly weird. I'm confused how `fetch-schema` would be adding the directive.

Are you able to validate this with a separate tool like Apollo Studio or GraphiQL that will let you view the schema off your server too? Either of those should let you view, and download, the schema.

**Comment by loganblevins** [comment]
@calvincestari I don't know how to use the sample project you sent to replicate if it's the `--fetch-schema` that is the problem.

It definitely is a blocker bug because I am unable to update the package on my end and am blocked. I've bene using this Apollo tool for a long time and never had this issue.

I just introspected now on 1.12.0 and have no issues.

**Comment by loganblevins** [comment]
@calvincestari While it is possible I could use Apollo Studio that is a very manual process and leaves the CLI in a broken state and usable

**Comment by calvincestari** [comment]
> @calvincestari I don't know how to use the sample project you sent to replicate if it's the --fetch-schema that is the problem.

No, if `--fetch-schema` is the issue that sample project won't help. It demonstrates that the code generation build phase does not add a duplicate directive - but to an already existing schema file with only a single defer directive definition.

> While it is possible I could use Apollo Studio that is a very manual process and leaves the CLI in a broken state and unusable

The CLI will get fixed if there is an issue there. I'm still trying to figure out the root cause.

**Comment by calvincestari** [comment]
OK, I've gotten to a state where I can replicate the diff via introspection. Give me some time to try figure out how this is happening.

**Comment by loganblevins** [comment]
@calvincestari Awesome thanks

**Comment by calvincestari** [comment]
I think the problem is in [graphql-js](https://github.com/graphql/graphql-js) which [we use](https://github.com/apollographql/apollo-ios-dev/blob/main/apollo-ios-codegen/Sources/GraphQLCompiler/JavaScript/package.json#L16) for validating a schema, compiling a schema, and converting introspection JSON into GraphQL SDL. The downloaded introspection JSON only contains a single defer directive definition but after [the call to `printSchemaToSDL`](https://github.com/apollographql/apollo-ios-dev/blob/main/apollo-ios-codegen/Sources/GraphQLCompiler/JavaScript/src/index.ts#L82) the output then contains two instances of the defer directive definition.

**Comment by calvincestari** [comment]
I've got a draft PR up at https://github.com/apollographql/apollo-ios-dev/pull/440 with one outstanding JS test to get working then I think we'll be good to go.

**Comment by loganblevins** [comment]
@calvincestari Cool thanks!

**Comment by calvincestari** [comment]
The PR to resolve this has been merged and the fix will go out in the next release, we're aiming to publish that this week still.

**Comment by loganblevins** [comment]
@calvincestari super grateful - thank you!

**Comment by loganblevins** [comment]
Working!! Thank you!
