### ISSUE TITLE
can we get @inlinable on properties when generating code into SPM package?

### ISSUE THREAD

**Issue by ZeeWanderer** [apollographql/apollo-ios#3431]
### Question
Is there an option to add inlining to spm package?

When generating files into an SPM package its a separate compile module so unless properties/functions are marked with `@inlinable` to my understanding no inlining will occur.
In particular wrapper properties like
```
public var results: [Result] { __data["results"] }
``` 
Will benefit from it.

**Comment by calvincestari** [comment]
Hi @ZeeWanderer 👋🏻 - no, there is not any configuration option at the moment to generate `@inlinable` property accessors.

I'll take this feature request to our next team planning meeting and gather opinion from the rest of the team; _could be a week or so before I get back to you though_.

**Comment by calvincestari** [comment]
Apologies for taking so long to get back to you on this issue - we finally got together to discuss this a bit more.

> When generating files into an SPM package its a separate compile module so unless properties/functions are marked with `@inlinable` to my understanding no inlining will occur.

I believe this used to be the case before Swift 5.8 where a [conservative implementation of Cross Module Optimization was introduced as a default](https://forums.swift.org/t/brave-new-world-best-practices-for-cross-module-optimization/66869/3) compiler optimization. The impact of this should be that if you are compiling the source for all modules at build time then `@inlinable` has no effect because _everything_ is by default inlinable.

I'm going to close this issue as there does not seem to be any benefit to a adding `@inlinable` to generated packages. If you were distributing a package containing your generated models as a prebuilt binary then I could see where `@inlinable`  becomes useful. Are there other use cases where you think this is still beneficial?
