### ISSUE TITLE
Apollo takes a long time to resolve via SPM

### ISSUE THREAD

**Issue by waitbutY** [apollographql/apollo-ios#3442]
## Issue

In our app, we have 40-50 SPM dependencies, and Apollo is in the top 3 slowest packages to resolve.

## Potential Solution

This is a known SPM issue, as SPM by default pulls not just the code but all the branches and commit history, etc.
https://github.com/swiftlang/swift-package-manager/issues/6062

Some larger repositories have solved this by creating a separate repo that just points to the precompiled XCFramework, resulting in much, much smaller and faster package resolution.

Example, Lottie: https://github.com/airbnb/lottie-spm

Can AppsFlyer SDK be offered in this way for iOS app consumption?

### Version

1.7.1

### Steps to reproduce the behavior

List Apollo as a dependency of an Xcode project via SM

**Comment by AnthonyMDev** [comment]
Thanks for bringing up a discussion on this. The repo is pretty old and has a long history, so it makes sense that it takes a bit of time to clone.

@BobaFetters, would it make sense to add this to the existing Apollo Frameworks repo we have for Carthage support? Maybe we could just add a Package file [like the one here](https://github.com/airbnb/lottie-spm/blob/main/Package.swift) from the repo referenced in this issue.

I'm not a fan of having yet another repo to maintain, but if we could accomplish this without too much additional work, it's worth considering.

---

The other side of this is, maybe we could do some work to reduce the size of the history of the repo. Running tools like `git gc` might help a little bit, but they don't really re-write the history. Would doing a squash of all commits over 3 years old (or some other appropriate time span) make sense? I don't think it's necessary that we keep all of that history around forever. I can't imagine we want to reference it very often.

I'm not clear on how that would affect consumers of the package. Developers who contribute to Apollo iOS would need to re-clone if we did something like this, but maybe we should explore what implications it would it have for users who are just depending on the package.

[This single commit](https://github.com/apollographql/apollo-ios-dev/commit/c3ece8b4a1df66d09173dbea633864b1f23155b4#diff-f65920ca3a0c6c340156cf4962cfe89f2bfed6c4140867a3d15bf21198e7fd93) from 6 years ago is 40MB of node binary that we have since removed and no one should need this anymore.

**Comment by BobaFetters** [comment]
@AnthonyMDev I can look into what that would entail and if it would make sense to have in that repo or if it would need its own.

**Comment by waitbutY** [comment]
Thank you all, I really appreciate you looking into it.

Hanging on to commits from 3 years ago doesn't make sense to me (or doesn't sound like it adds much value), but all contributors needing to re-clone sounds fairly disruptive :(

**Comment by emersonhsieh** [comment]
@waitbutY I was running into this issue with Xcode 15.2, with the installing hanging and then timing out. The issue was resolved by upgrading to Xcode 15.4.

**Comment by AnthonyMDev** [comment]
After further discussion, the team feels that there isn't really an actionable solution to this we are comfortable with. With the introduction of registry support in Swift 5.7.1, users who have concerns here could feasibly set up their own artifact repository. You can also create your own repo that contains the bundled artifact as suggested the OP here. We don't believe there is a way to decrease the size of the existing repo without causing downstream effects. We're going to close this issue for now. If there is significant community feedback, we may consider reopening and trying to find a better solution.
