### ISSUE TITLE
Access to URLSessionDelegate, URLSessionDataDelegate & URLSessionTaskDelegate for Pulse logger usage

### ISSUE THREAD

**Issue by TripwireNL** [apollographql/apollo-ios#3471]
### Question

Hi,

I would like to know if it's possible to access the URLSessionDelegate, URLSessionDataDelegate & URLSessionTaskDelegate so we can respond to these delegate methods when needed. We're building an MVP on our current app using GraphQL instead of Rest. In our current setup we use the Pulse logger [https://github.com/kean/Pulse](url) for logging network requests in our app and we would like to re-use it for GraphQL calls too.

Thx!

**Comment by calvincestari** [comment]
Hi @TripwireNL - it's tricky because `URLSessionClient` needs to handle those delegate calls. Some of them have no implementation but many are important for `NetworkFetchInterceptor` to function correctly.

However, since [`URLSessionClient` is an `open class`](https://github.com/apollographql/apollo-ios-dev/blob/main/apollo-ios/Sources/Apollo/URLSessionClient.swift#L11) you could subclass it and override those delegate methods. You'll need to ensure you're calling the `super` implementation so that any expected work gets done in response to the delegate call though.

To make this work:
1. [Initialize](https://github.com/apollographql/apollo-ios-dev/blob/main/apollo-ios/Sources/Apollo/DefaultInterceptorProvider.swift#L18) an instance of `DefaultInterceptorProvider` using your `URLSessionClient` subclass.
2. Use that instance of `DefaultInterceptorProvider` when you [initialize](https://github.com/apollographql/apollo-ios-dev/blob/main/apollo-ios/Sources/Apollo/RequestChainNetworkTransport.swift#L55) the `RequestChainTransportNetwork`.

I think with that you should be able to do what you need but let me know if you get stuck.

**Comment by calvincestari** [comment]
@AnthonyMDev - when you're back let's discuss whether this request/behaviour something we should revisit in the work for 2.0.

**Comment by mwasniewski-bright** [comment]
That could be beneficial 🙌 Without this, Pulse can't be integrated with Apollo
