### ISSUE TITLE
Crash in `GraphQLQueryWatcher.cancel()` and `GraphQLQueryWatcher.refetch()`

### ISSUE THREAD

**Issue by damian0815** [apollographql/apollo-ios#3476]
### Summary

When I attempt to call `refetch()` or `cancel()` on a GraphQLQueryWatcher i get an `EXC_BAD_ACCESS`.
* with `refetch()` it's in `GraphQLQueryWatcher.fetch()` on the first line (`$fetching.mutate {`).
    <img width="647" alt="image" src="https://github.com/user-attachments/assets/ff17900c-1b7e-487b-b6f1-700855ed4cf4">
* with `cancel()` it's on the first line of the `cancel()` func `fetching.cancellable?.cancel()`

### Version

1.15.1

### Steps to reproduce the behavior

`refetch()` is being called from the main thread of my app. I have verified that I'm also creating the `GraphQLQueryWatcher` on the main thread. I've also tried using `refetch()` in a detached Task (`Task.detached`), which doesn't help either. 

### Logs

```shell
Backtrace:

Thread 1 Queue : com.apple.main-thread (serial)
#0	0x0000000000000000 in 0x00000000 ()
#1	0x0000000104971580 in GraphQLQueryWatcher.fetch(cachePolicy:) at /Users/damian/Library/Developer/Xcode/DerivedData/XXXX-boiyzzgkimuasqfevhtzbuipxoth/SourcePackages/checkouts/apollo-ios/Sources/Apollo/GraphQLQueryWatcher.swift:72
#2	0x00000001049714dc in GraphQLQueryWatcher.refetch(cachePolicy:) at /Users/damian/Library/Developer/Xcode/DerivedData/XXXX-boiyzzgkimuasqfevhtzbuipxoth/SourcePackages/checkouts/apollo-ios/Sources/Apollo/GraphQLQueryWatcher.swift:68
```

**Comment by damian0815** [comment]
Updated - also hitting on `.cancel()`

**Comment by calvincestari** [comment]
I was going to ask if you're able to reproduce this in a standalone project that we can debug because we have tests that use both those methods without error.
* refetch test [here](https://github.com/apollographql/apollo-ios-dev/blob/a836ccf065c9812f5a29eec65df3e8f60a950be2/Tests/ApolloTests/Cache/WatchQueryTests.swift#L88)
* multiple tests in that same file have a [teardown block that all call `cancel()`](https://github.com/apollographql/apollo-ios-dev/blob/a836ccf065c9812f5a29eec65df3e8f60a950be2/Tests/ApolloTests/Cache/WatchQueryTests.swift#L60)

But..based on [your other comment](https://github.com/apollographql/apollo-ios/issues/3472#issuecomment-2489502136) I wonder if this crash is because of how you're manipulating the cache by deleting the object but not updating the lists that reference that object. So the subsequent fetch is looking for a cache object that isn't there.

Why it's crashing on cancel though I'm not sure. 🤔

**Comment by damian0815** [comment]
> But..based on https://github.com/apollographql/apollo-ios/issues/3472#issuecomment-2489502136 I wonder if this crash is because of how you're manipulating the cache by deleting the object

ahh, that's a good thought but it was crashing before I added that.
