### ISSUE TITLE
After updating to Apollo 0.9.4, CircleCI can't find ApolloCLI

### ISSUE THREAD

**Issue by adamirowe** [apollographql/apollo-ios#423]
I recently updated to Apollo 0.9.4 via Cocoa Pods, which works great locally, but when building project via fastlane on CircleCI I'm getting output that Apollo iOS can't find 1.9.x of Apollo CLI.

<img width="1065" alt="screen shot 2018-12-13 at 11 40 59 am" src="https://user-images.githubusercontent.com/43765296/49953368-fe1e1280-fecb-11e8-9e6d-d9eb2d999a6e.png">

**Comment by paulmelnikow** [comment]
I'm running into this warning locally as well.

**Comment by stNamco** [comment]
Did you set an output file path? if you set that, generating script is executed before compile source.
https://developer.apple.com/library/archive/documentation/DeveloperTools/Conceptual/XcodeBuildSystem/200-Build_Phases/bs_build_phases.html#//apple_ref/doc/uid/TP40002690-BBCCFEDJ

**Comment by paulmelnikow** [comment]
> I'm running into this warning locally as well.

I should clarify that I see this warning all the time though my build works fine.

**Comment by structAnkit** [comment]
I just updated from Apollo 0.8.x to 0.9.5 yesterday and started running into this issue.

When I run `fastlane` and don't have Apollo CLI installed (when I run my build phases on a fresh environment such as Bitrise CI), the `npm install` step doesn't run synchronously so the build phase is basically skipped. Since the Apollo CLI is not being installed, the codegen isn't running and the generated file doesn't exist.

**Comment by designatednerd** [comment]
Hey @adamirowe - were you ever able to resolve this issue? I know some folks had success running a pre-build step that used `npm install - g` with our CLI client on Circle.

**Comment by adamirowe** [comment]
> Hey @adamirowe - were you ever able to resolve this issue? I know some folks had success running a pre-build step that used `npm install - g` with our CLI client on Circle.

Yes but I do not remember how honestly. Let me know if you need anything else from me.
