### ISSUE TITLE
Use probot/stale to close inactive issues

### ISSUE THREAD

**Issue by stNamco** [apollographql/apollo-ios#433]
Would anyone mind if I set up [probot/stale](https://github.com/probot/stale) to automatically close issues that are labeled as "Question" after 3 weeks of inactivity? it helps keep things current. [Here is an example of it being used at Moya](https://github.com/Moya/Moya/issues/1658#issuecomment-389533220)

**Comment by designatednerd** [comment]
This might be something to do in the future but for now I'd like to hammer through everything manually since due to some staffing issues on our end, there's quite a few things that are "stale" but still legit issues. 

I'll close this request out for now, but once our issues are more under control I make consider using something like this.
