### ISSUE TITLE
Security vulnerabilities in package-lock.json

### ISSUE THREAD

**Issue by gridNA** [apollographql/apollo-ios#439]
Zalando team is using the Apollo client for the iOS app, and lately we started to receive vulnerabilities warning from GitHub located in package-lock.json:
Suggesting to update:
cryptiles ~> 4.1.2
hoek ~> 4.2.1
lodash ~> 4.17.5
randomatic ~> 3.0.0
sshpk ~> 1.13.2

Please take a look as we can not have issues according to our GDPR policies.

Thanks,
Kate

**Comment by mltbnz** [comment]
At what point do you get these errors?

**Comment by designatednerd** [comment]
These issues were tied to the JS code which generates our documentation website rather than to anything actively used in this particular repo. We've now got @renovate-bot going through and updating these things on a regular basis, though, so the issues should be gone now.

If you're still seeing errors on that, please let us know by opening a new issue. Thank you!
