### ISSUE TITLE
Add support for Date Type

### ISSUE THREAD

**Issue by LucasLiao** [apollographql/apollo-ios#450]
Although it's not mandatory, it' better to support ISO8061DateTime, since handling date is annoying thing with JSON.

**Comment by RolandasRazma** [comment]
all you need to do is:

```swift
public typealias DateTime = Date

extension DateTime: JSONDecodable, JSONEncodable {
    
    public init(jsonValue value: JSONValue) throws {
        guard let string = value as? String else {
            throw JSONDecodingError.couldNotConvert(value: value, to: String.self)
        }
        
        guard let date = ISO8601DateFormatter().date(from: string) else {
            throw JSONDecodingError.couldNotConvert(value: value, to: Date.self)
        }
        
        self = date
    }
    
    public var jsonValue: JSONValue {
        return ISO8601DateFormatter().string(from: self)
    }
    
}
```

where `DateTime` is your date scalar

**Comment by michaelnisi** [comment]
👍 I like your approach, @RolandasRazma. Be aware though that creating date formatters is not cheap. 

Converting many objects, this can become relevant. Sharing the formatter is 85% better, according to Xcode, in a quick test I just ran.

```swift
public typealias DateTime = Date

private let iso8601DateFormatter = ISO8601DateFormatter()

extension DateTime: JSONDecodable, JSONEncodable {
    
    public init(jsonValue value: JSONValue) throws {
        guard let string = value as? String else {
            throw JSONDecodingError.couldNotConvert(value: value, to: String.self)
        }
        
        guard let date = iso8601DateFormatter.date(from: string) else {
            throw JSONDecodingError.couldNotConvert(value: value, to: Date.self)
        }
        
        self = date
    }
    
    public var jsonValue: JSONValue {
        return iso8601DateFormatter.string(from: self)
    }
    
}
```

Here, that’s 2.074 seconds vs 0.631 seconds for passing a test with 1000 conversions.

**Comment by RolandasRazma** [comment]
I’m not doing that, this was just simplified example

**Comment by designatednerd** [comment]
The problem with making a standardized formatter is that there isn't really a standardized `Date` representation in the GraphQL spec (I recall @jbaxleyiii talking about a VERY long meeting around this issue recently with the GQL working group). Unfortunately, this means you never know quite what format you're getting back from a server -- is it an ISO8601 string? An integer with seconds since Y2k? A float with milliseconds since 1970?

I'm going to close this out with @RolandasRazma's [example here](https://github.com/apollographql/apollo-ios/issues/450#issuecomment-486171239) with @michaelnisi's [clarification here](https://github.com/apollographql/apollo-ios/issues/450#issuecomment-487125981) as the presently recommended workaround. 

If you have follow-up questions, please stop by our [Spectrum Chat](https://spectrum.chat/apollo/apollo-ios?tab=posts) - thank you!
