### ISSUE TITLE
Support for native Decodable Swift structs

### ISSUE THREAD

**Issue by ndizazzo** [apollographql/apollo-ios#467]
I'm not sure if this repository or the [tooling repository](https://github.com/apollographql/apollo-tooling) would be more appropriate for a discussion about this, but I've had a look in both for mentions of [Swift 4's `Codable` protocols](https://developer.apple.com/documentation/swift/codable), and was surprised to not see any discussions in either repository about it.

I was wondering if it would make sense to have code generated that yields `Decodable` Swift `struct`s. Even better, fully `Codable` ones.

This would greatly clean up the generated template code for objects, and would potentially save some space by not needing to insert values into a `resultMap` dictionary, and then force-cast those back to the right type. 

I'm fairly new to using Apollo and GraphQL and maybe that means I'm missing something obvious that would prevents this, but at the very least, discussing here will also help developers searching for this issue.

**Comment by GiantBlue76** [comment]
Basically, swift 4 supporting codable and coding keys completely removed the value of graphql imo.

**Comment by ndizazzo** [comment]
@GiantBlue76 interested to hear your thoughts as to why? GraphQL still condenses API requests into one endpoint + a schema which is why I find it useful, but ymmv of course. `Codable` support would clean up a fairly hairy part of Apollo (in Swift) from what I can tell.

**Comment by sirghi** [comment]
Indeed would be very useful. Would relieve us from converting into custom Decodable types to store these objects in a cache, for instance.

**Comment by designatednerd** [comment]
Yes I would *way* prefer to do things this way as it would eliminate huge swaths of errors, but it's going to require some significant refactoring. No ETA but definitely looking into getting it done sooner rather than later.

**Comment by jjatie** [comment]
Any update on this?

**Comment by aroraenterprise** [comment]
Hey speaking of Codable. I wanted to ask if there was an easy way to get a scalar of type json array to work. I have used --passthroughCustomScalars but when I got to typealias, nothing works!

**Comment by designatednerd** [comment]
@aroraenterprise I believe if you typealias to `[String: Any?]` that should work.

**Comment by aroraenterprise** [comment]
First off, thank you for such a quick response! @designatednerd 
If I do the [String: Any?]

```
Failure! Error: GraphQLResultError(path: slide_deck.0.slides, underlying: Apollo.JSONDecodingError.couldNotConvert(value: <__NSArrayI 0x600001763c40>(
{
    "background_image_key" = "slides/c5f16f40-70c1-4cfe-a76b-60692fe2b0c7/9410efbc-900a-424d-949b-e37035f71f11/Screen Shot 2019-07-19 at 12.55.00 AM.png";
},
{
    "background_image_key" = "slides/c5f16f40-70c1-4cfe-a76b-60692fe2b0c7/3a4ed336-ae87-411d-9321-28e9e4a0afa0/Screen Shot 2020-04-26 at 5.50.41 PM.png";
},...
)
, to: Swift.Dictionary<Swift.String, Swift.Optional<Any>>))
```

**Comment by designatednerd** [comment]
Looks like maybe your outer layer is an array? You might need to do `[[String: Any?]]`.

If that doesn't work, please email me your generated swift code and the JSON you're getting from your server to ellen at apollographql dot com, I'll see what i can figure out.

**Comment by ferologics** [comment]
Is there a plan of implementation? I'd be happy to take a stab at this @designatednerd 🙂

**Comment by designatednerd** [comment]
Yes, it's already in progress it's just hit a couple roadblocks, hoping to get back to it next week!

**Comment by ferologics** [comment]
Is there a PR/branch that I can take a look at? I'm interested in seeing it under the hood. Also lmk if there's any way I could help 👐

**Comment by designatednerd** [comment]
At the moment, no PRs - if you take a look in the `ApolloCodegenLib` and the corresponding tests, there's stuff already merged for input objects and enums. Going to be taking a crack at fragments next, which is going to be the vast majority of the work.

**Comment by din** [comment]
Are there any estimates on how long this might take to be implemented?

**Comment by designatednerd** [comment]
I mean, there _are_ estimates, it's just that every single one I've had has been comically wrong. 🙃

That said, while new codegen has been been stop and go for some time, we're hoping to get rolling in a more permanent fashion shortly. I will update this when there's an alpha to try out.

**Comment by Dara-To** [comment]
I have decided to go with Apollo to pair with Contentful as you can fetch nested data in a single query. However, I have hit a couple of roadblocks because of the missing decodable protocol conformity. The workaround I applied was to create another data model on top of the generated one in API.swift which defeats the purpose I must say. But on the plus side, I was able to unwrap optional them. 

Now, I am trying to create preview data based on json files instead of typing a field at a time and load from those files. This is what I am getting as error. No workaround found yet. 

`Global function 'load' requires that 'ContentQuery.Data' conform to 'Decodable' `

Please make them decodable out of the box. Thanks Ellen for your hard work!

**Comment by designatednerd** [comment]
Yes, these are still not decodable out of the box - we're still working on new codegen (and will be for a bit). In theory you should be able to deal with nested data using our code generation, though.

**Comment by Dara-To** [comment]
I wasn't able to use a collection in a List or ForEach, I don't know why. It says that it doesn't conform to random access collection, something like that.

**Comment by designatednerd** [comment]
I think that's likely to do more with the lack of conformance for either `Hashable`, `Equatable`, or both. That is definitely something we're planning on addressing.

**Comment by AnthonyMDev** [comment]
We have given this issue a lot of consideration in the lead up to the official 1.0 release of Apollo iOS. We have decided _not_ to implement `Codable/Decodable` conformance in our generated models. While this may be disappointing to some users, I'd like to explain our reasoning.

### Our Reasoning:

`Codable` is used primarily for reading and writing objects from a file structure. Supporting it would allow you to write your generated Apollo objects, after being fetched, to an arbitrary data storage solution. **But Apollo provides support for this via the `NormalizedCache` already, and in a "GraphQL first" methodology.**

The normalized caching functionality is a core component of the Apollo client, and it addresses many of the GraphQL specific issues that storing `Codable` objects otherwise creates. Cache normalization allows you to ensure that objects are cached in a way that they are kept up-to-date across multiple queries/mutations. It handles transitive references between objects and integrates with the `GraphQLExecutor` to allow for your cached data to be read by other query operations in the future.

By using `Codable` to store your objects outside of the normalized cache, your persisted objects are not updated when changes occur and references to the same object from multiple places are not resolved (causing out-of-date and duplicated data problems).

### Our Recommendation:

You can write and specific cache implementation you would like, writing your data to any location in any format you choose by creating your own class that conforms to the `NormalizedCache` protocol. When working at the `NormalizedCache` level  you are exposed to the raw data prior to it being mapped onto the generated objects. This provides the ability to implement anything you would do with `Codable`, while asking to you provide the additional merging methods for normalizing objects so that they still work with `Apollo`. 

We have -- thus far -- been unable to come up with a use case in which any implementation or with another library that you want to do could not be more aptly handled via a custom `NormalizedCache` than with `Codable` support. (ORM integration, such as for use with `CoreData` or `Realm` is much more complicated a problem, but that also would not be solved by `Codable`.)

---

Additionally, in the 1.0 release, the entire code generation engine has been rewritten in Swift. This enables iOS developers to more easily contribute to or create their own code generation templates. Any custom code generation you would like to do can be written. But we aren't willing to make a commitment to officially supporting `Codable` for the long-term when we strongly believe it is against the best practices for working with GraphQL data, which should be normalized.
