### ISSUE TITLE
Scaling of Cache on clients

### ISSUE THREAD

**Issue by Abhijith-net** [apollographql/apollo-ios#470]
Hello,
     We currently have disk cache as a key-value store in SQLite. All the operations we do will be in one single table. This raises few concerns, wrt to query time performance + running out of storage. 

In our case, we are planning to use aws-app sync which uses Apollo client, as a chat engine. With the chat engine, the growth of the number of conversations and messages will be extremely high. We need to either have 

1. Data segregated into the separate designated tables (This will go only so far... even this will run out of cache)
2. Have a TTL for the cache entries. This way all older messages are cleared based on TTL.
3. Go the hybrid way of (1)+(2)

Any other suggestions to handle this?

Please let us know!

Thanks in advance!

**Comment by designatednerd** [comment]
Oof yeah that's going to be a gargantuan table if it's one table. Unfortunately, my expertise in the underlying features of SQL is not super strong.

This is likely a better question for the developer behind [SQLite.swift](https://github.com/stephencelis/SQLite.swift), which we use for the `Apollo/SQL` subspec. Stephen's probably got a much better idea of what needs to happen here in terms of setup for the underlying SQL stuff.

I'm going to close this one out since I'm trying to keep the issues on the repo mainly for bugs and enhancements rather than question. If you have follow-up questions that you might like help from the community with, please drop by our [Spectrum Chat](https://spectrum.chat/apollo/apollo-ios?tab=posts)!
