### ISSUE TITLE
Multiple Schema - Production and Development Issue

### ISSUE THREAD

**Issue by sam961** [apollographql/apollo-ios#540]
Iam trying to create multiple schema for my project; one for development and one for production
I followed this url :
https://thoughtbot.com/blog/let-s-setup-your-ios-environments
All working fine but when I compile iam stuck on this : 
**Couldn't find Apollo.framework in FRAMEWORK_SEARCH_PATHS; make sure to add the framework to your project.**
Any idea ?

**Comment by designatednerd** [comment]
Can you try replacing your build script with the one in the docs that went out with 0.11.0 (caveat: I did miss a space in the iOS not-Cocoapods build script fixed in #618)? Please let me know whether this works or not.

**Comment by designatednerd** [comment]
Hey there - haven't heard back in a bit so I'm going to close this issue out. 

Please keep an eye out for some of the changes that are about to ship with 0.13.0, that should help things a bit since it'll have the updated instructions and a more modern version of the CLI.

Please open a new issue if you're still having problems. Thank you!
