### ISSUE TITLE
How to use refresh token with apollo?

### ISSUE THREAD

**Issue by DmitriyTerekhin** [apollographql/apollo-ios#564]
Is it possible to use refresh token? How? I can't find any solutions...

**Comment by designatednerd** [comment]
You should be able to set this up with the `HTTPNetworkTransportPreflightDelegate` and/or the `HTTPNetworkTransportRetryDelegate` added in 0.11.0. Please see the docs in [`HTTPNetworkTransport.swift`](https://github.com/apollographql/apollo-ios/blob/master/Sources/Apollo/HTTPNetworkTransport.swift) for details.

**Comment by kimdv** [comment]
@DmitriyTerekhin did you find any solution?

Out system have a `exchangeRefreshToken` mutation so we cannot place a 401 in front of the GraphQL endpoint. 

We always get a 200 in return, but if our token is invalid, then we get error in the list. 

@designatednerd is there a way to trigger the retry based on errors in the responses errors list? 
Like a delegate we can implement, `func shouldRetry(_ networkTransport: HTTPNetworkTransportgraphQlError: [GraphQLError]) -> Bool` ?

**Comment by designatednerd** [comment]
At the moment the retry delegate is only fired off if there's an error at the network level (basically, from middleware), since you can get a partial success/partial error response from a GraphQL server, and having that check every single call could add a significant amount of overhead. I'm looking at ways to make this better in the long term, but I don't have anything ready quite yet.

One thing I would suggest in the meantime is checking your current `refreshToken`'s expiration in the `PreflightDelegate` and then exchanging it proactively if it's too close to expiring.

**Comment by piemonte** [comment]
for anyone that may come across this discussion, see `UserManagementInterceptor` here:

📎 https://www.apollographql.com/docs/ios/initialization/#example-advanced-client-setup

**Comment by designatednerd** [comment]
Yep that's the current recommendation - this issue is from well before the current interceptor setup was created.

**Comment by bitops** [comment]
Currently the `UserManagementInterceptor` is documented here:

https://www.apollographql.com/docs/ios/networking/request-pipeline/#usermanagementinterceptor
