### ISSUE TITLE
Code generation is broken due to missing scripts

### ISSUE THREAD

**Issue by stevenp** [apollographql/apollo-ios#615]
This change to the podspec breaks code generation, as the scripts are no longer included in the framework. In order to work around this, I had to fork the repo and revert this change. I'd suggest reverting this commit.

https://github.com/apollographql/apollo-ios/commit/46eff59f63fe5b931911e2d5a04921e28e43017c#diff-658ca52a7048d1269f543238db0bfc9e 

cc @cltnschlosser

**Comment by cltnschlosser** [comment]
@stevenp Why are you using the scripts from within the framework? Instead of just using the ones in the scripts directory?

I don't use the default scripts, so maybe there is some documentation that mentions using the scripts from within the framework. I don't think the scripts should be included in the framework. It doesn't make sense to ship build scripts in every app that uses this pod.

**Comment by stevenp** [comment]
The recommended way to generate code on iOS, according to the documentation, is to execute the script inside the framework as a build step.

https://www.apollographql.com/docs/ios/installation/#adding-build-step 

I'm happy to do this in a different way, but the docs should be updated if this is no longer the recommended approach. If this change were deployed in a release, most projects that are using Apollo would no longer successfully perform code generation.

**Comment by cltnschlosser** [comment]
For cocoapods I would use this path `${PODS_ROOT}/Apollo/scripts/check-and-run-apollo-cli.sh` I believe that should work.

Weird to me that the scripts were ever included in the framework. I really don't like shipping the script in production apps, so I'd be sad to see this reverted.

The script in the documentation could be updated to check if PODS_ROOT environment variable is defined, so that they don't need different scripts for Carthage, etc.

**Comment by cltnschlosser** [comment]
Looks like https://github.com/apollographql/apollo-ios/pull/610 is already updating the documentation to use PODS_ROOT.

**Comment by designatednerd** [comment]
This is addressed in version 0.11.0, which is tagged and I'm presently in the process of pushing to trunk.
