### ISSUE TITLE
Release schedule & the future of Apollo iOS

### ISSUE THREAD

**Issue by stevenp** [apollographql/apollo-ios#617]
@designatednerd I'm confused about the maintenance and release schedule of this project. There hasn't be a release since April, so we've been needing to build against master and there have been a massive number of changes, including breaking changes like the one I mentioned in https://github.com/apollographql/apollo-ios/issues/615. It turns out that https://github.com/apollographql/apollo-ios/pull/575 was merged without an update to the documentation, and it broke our build process, resulting in me having to go back and comb through commits to try to figure out what caused things to stop working.

The company I'm working for is moving to a new GraphQL backend and Apollo is really currently the only viable open source client for iOS, so I'm trying to determine if it's production ready, and how to work using it into our development process. I'm hoping you might be able to provide an update about what will be happening with the project moving forward so that I can set expectations for my team. Thank you!

**Comment by designatednerd** [comment]
Hi Steven - in general it's better to ask more general questions like this on our [Spectrum chat](https://spectrum.chat/apollo) but I know the repo's been in a bit of a state for a while so I wanted to address this here before closing out this issue.

I started working at Apollo at the end of June. I was hoping to get the 0.11.0 release out before the July 4th holiday and a conference I was at the last two days, but that didn't happen, and I didn't think it was a great idea to push an official release with some fairly significant changes when I wasn't going to be around to help deal with any issues that arise from that release. 

The 0.11.0 release is now tagged and I'm in the process of getting it pushed out to CocoaPods. Right now I don't have an official schedule of when we'll be releasing new stuff. I've got some plans for the longer term which I'll be outlining in a few weeks, but right now I'm working my way through the (as you've seen, not small) backlog of existing issues. 

Apollo is committed to this project - that's why they've hired me. I'll be bug bashing for a while, but I plan to put a roadmap together once things are a bit more under control. 

I'm gonna close this issue out, and ask that if you'd like to discuss further, you start a thread on Spectrum and tag me (same handle as here) - I want to try and keep the Issues tab for bugs rather than longer threads. Thank you!
