### ISSUE TITLE
Watching specific objects in the cache

### ISSUE THREAD

**Issue by skanev** [apollographql/apollo-ios#630]
Hey. Maybe I'm missing something, but I can't figure out how to solve this problem neatly, and I decided to ask. So here it goes.

I'd like to subscribe to changes to specific records in Apollo's normalized cache. I can't figure out how to do it. `ApolloStoreSubscriber` and friends are not public and I cannot figure out why.

Here's the full context of what I'm trying to accomplish:

I'd like to implement infinite scrolling on a graph connection where the results get accumulated in a table view. I'd like to watch all the fetched records, so the view cells can get updates once the records are changed. I'd like to fetch the first page as a part of a much larger query that will have other changeable things. And finally, I'd like to wrap this whole thing in `RxSwift` observables.

Out of the box, this proves tricky. I might be missing something obvious, but:

1. To watch the collection of the individual pages, I have to maintain an array of `GraphQLQueryWatcher`s. That is cumbersome.
2. It's tricky to know whether the query succeeded or failed. I'd like to be able to determine that I've obtained a page successfully before I wrap it in an Observable
3. Since the first page is a fragment in a much larger query, I'm uninterested in changes in the rest of the query. Ultimately they won't hurt, but still, it would be good to be precise.

Fundamentally, I just want to `fetch` the page, accumulate the nodes I've retrieved in an array and tell Apollo "call me back if anything here changes". I think I could figure a way to do it, if most of the needed methods weren't internal.

Am I missing something? Is there a way to subscribe to changes in the store?

**Comment by designatednerd** [comment]
You are not missing anything in terms of watching individual records - right now the only thing we really support watching is Queries, not individual objects. Right now our support for fetching more on an existing query is an open issue (#565), so unfortunately that's not terribly helpful for pagination. 

The store is designed for framework-internal use, which is why `ApolloStoreSubscriber` is not a public protocol. There's a lot of cans of worms making that protocol public opens up, especially the `context` which is an `UnsafeMutableRawPointer?`. 

I am planning to take a longer look at this as I hack my way through the cache, but youo're definitely not missing anything. 

I'm going to close this question out - in the future I'm trying to keep github reserved for problems and/or feature requests rather than questions - if you've got any follow ups, please head over to our [Spectrum Chat](https://spectrum.chat/apollo/apollo-ios?tab=posts)!
