### ISSUE TITLE
I got the same error when I update graphql to 0.13.0.. do you know why ?

### ISSUE THREAD

**Issue by emanShedeed** [apollographql/apollo-ios#668]
I got the same error.. do you know why ?

<img width="1215" alt="capture d ecran 2018-10-17 a 13 15 26" src="https://user-images.githubusercontent.com/5727223/47104324-24e30400-d20f-11e8-827c-36b399f9cf5d.png">
<img width="709" alt="capture d ecran 2018-10-17 a 13 18 47" src="https://user-images.githubusercontent.com/5727223/47104356-37f5d400-d20f-11e8-984e-843cce2eb3a1.png">

_Originally posted by @JulienLevallois in https://github.com/apollographql/apollo-ios/issues/199#issuecomment-430713975_

**Comment by emanShedeed** [comment]
![Screen Shot 2019-07-25 at 7 53 27 AM](https://user-images.githubusercontent.com/42905983/61850637-17049280-aeb5-11e9-93b8-4a3db6cf1088.png)

**Comment by designatednerd** [comment]
Hi Eman, this is covered in the [0.13.0 release notes](https://github.com/apollographql/apollo-ios/releases/tag/0.13.0) - it's because we've switched from a tuple of nullable parameters to a `Result`.  The error is a bit crap but unfortunately that's from Swift, not us. 

I'm going to close this out since it's covered in the release notes, but thanks for at least bringing it up here so people take a look at those!
