### ISSUE TITLE
Node LTS Version Out of Date

### ISSUE THREAD

**Issue by giladronat** [apollographql/apollo-ios#671]
Currently, the CLI script installs the exact Node version specified using nvm (#434) and switches to it, then installs Apollo locally (which is not ideal in my opinion #401). That Node version should be LTS but appears to be out of date (currently 8.15.0, [LTS](https://nodejs.org/) is at 10.16.0). I'm not sure if simply updating `REQUIRED_NODE_VERSION` is the best solution hence the issue instead of a PR. 

https://github.com/apollographql/apollo-ios/blob/4c5afcff3fa9a09210aa550c3cf61dad213749c2/scripts/check-and-run-apollo-cli.sh#L4

**Comment by designatednerd** [comment]
@giladronat OMG hi!

Yeah - it'd be nice to have that be a minimum rather than an exact version. You're welcome to tackle that in a PR if you want, otherwise I'll try to deal with that when I'm less [melted](https://www.nytimes.com/2019/07/25/world/europe/heatwave-record-temperatures.html) next week.

**Comment by giladronat** [comment]
@designatednerd Hi hi! It's so cool to see you working on the framework; you're doing a fantastic job thus far.

I don't know that I fully understand the [reason](https://github.com/apollographql/apollo-ios/pull/434#issue-244629165) an exact version was instated in the first place. Would making it a minimum version break anything for anyone?

If you think changing it to a minimum version requirement is the way to go and that doesn't interfere with anything you [were planning](https://github.com/apollographql/apollo-ios/issues/401#issuecomment-511387874) I'll work on it! 😃

**Comment by designatednerd** [comment]
Reading that PR, the reasoning is somewhat similar to what I've had to do in terms of pinning our dependencies: Making sure everyone is running the same version of Node so that when something breaks, we've got a cleaner path to debugging. 

Maybe let's start by updating to the current LTS version, and I'll add a note to your earlier thing about looking at whether we should go back to specifying just the major version of node
