### ISSUE TITLE
Swift package manager xcode 11 couldn't find Apollo

### ISSUE THREAD

**Issue by tyrong** [apollographql/apollo-ios#676]
I see that this issue has been raised a couple of times. I'm not sure if they managed to resolve the issue or not, but i am still get this error. (Other issues are closed)

Intended outcome:
Build project after following install guide

Actual outcome:
`error: Couldn't find Apollo.framework in FRAMEWORK_SEARCH_PATHS; make sure to add the framework to your project.`

`FRAMEWORK_SEARCH_PATHS` is empty in the build settings

How to reproduce the issue:
Add Apollo-ios to project via xcode inbuilt swift package manger, add script to build phases and build the project.

**Comment by halonsoluis** [comment]
It happens also when added via CocoaPods

**Comment by designatednerd** [comment]
@halonsoluis If the [updated Cocoapods installation instructions](https://www.apollographql.com/docs/ios/installation/#if-you-are-integrating-apollo-using-cocoapods) don't help, can you open that as a separate issue please? I want to try and keep SPM vs CP issues on their own threads since there can be such wildly different underlying problems. Thank you!

**Comment by designatednerd** [comment]
@tyrong Please check out the updated script in #679

**Comment by designatednerd** [comment]
Updated script is now merged and [up on our documentation site](https://www.apollographql.com/docs/ios/installation/#if-you-are-integrating-apollo-using-spm--xcode-11-beta) - going to close this out, please reopen or open a new issue if you're having problems. Thank you!
