### ISSUE TITLE
File upload v0.13 - Missing documentation

### ISSUE THREAD

**Issue by Drusy** [apollographql/apollo-ios#681]
Could you provide a concret example how to use file upload for Apollo v0.13 ?
An official documentation is required for such a "complex" feature.

For example: 
- How the `.graphql` file should look ?
- Where GraphQLFile instances should be passed ?

In addition, why the `upload` function of `HTTPNetworkTransport` is not part of the `NetworkTransport` protocol ? This would be nice for people using a custom transport layer, such as Alamofire for example.

**Comment by designatednerd** [comment]
@Drusy It's not on the protocol mostly because if it were, it'd need to be implemented in the Web Socket transport, where it doesn't really make a lot of sense. You should still be able to add it to your custom transport though!

Thanks for filing, will try to get a better example of this together soon.

**Comment by designatednerd** [comment]
This is now up with #707 - I also made some changes to simplify the upload system while trying to document it, so thank you for encouraging me to do that!

**Comment by designatednerd** [comment]
Significant changes to this along with way better documentation of this functionality have shipped with `0.15.0`.

**Comment by Cleversou1983** [comment]
@designatednerd Ellen, finally got it working! I really appreciate your help and support! Thanks so much!!!!!!!!!

**Comment by designatednerd** [comment]
Yay! Glad it's working now!
