### ISSUE TITLE
Parsing response in latest apollo V 0.13.0 

### ISSUE THREAD

**Issue by yousafiqbal1994** [apollographql/apollo-ios#686]
Hello community. I was using older version 0.11.0 of apollo. In the latest version there are modification to closures. I was able to parse the response in older version like this:

            let doctorsListQuery = DoctorListingQuery(name: item)
            
            apolloAuthClient.fetch(query: doctorsListQuery, cachePolicy: .returnCacheDataElseFetch, queue: DispatchQueue.main) {
                (result, error) in
                
                if error != nil { // System level, network errors
                    
                    print(error!)
                    self.callback?.onRequestCompleted("SNError", error!.localizedDescription as AnyObject)
                    
                }else{ // User errors
                    
                    if let error = result?.errors{
                        self.callback?.onRequestCompleted("UserError", error[0].errorDescription! as AnyObject)
                    }else{ // Valid response
                        self.callback?.onRequestCompleted("Success", (result?.data?.jsonObject)! as AnyObject)
                    }
                }
            }
 
which was working fine and we had (result, error) in closure. 

Now in the latest version we have (Result<GraphQLResult<GraphQLSelectionSet>, Error>) in the closure. I really do not know how to parse errors if any in this closure and how to parse the correct data returned from server. I need a code snippet that demonstrate how to detect different error type like "Network or System errors" or "User defined errors" returned from graphql API. 

Code I am using is:

        apolloAuthClient.perform(mutation: mutation, queue: DispatchQueue.main) { (result) in
            print("Result is: \(result)")
        }

**Comment by yousafiqbal1994** [comment]
@designatednerd can you please look into it. Thanks

**Comment by designatednerd** [comment]
Hey Yousaf, this is now using the [Swift Result](https://developer.apple.com/documentation/swift/result) enum in order to return things. [Here's a good overall primer from Paul Hudson](https://www.hackingwithswift.com/articles/161/how-to-use-result-in-swift), but In the example you've shared here's a rough outline how of that would change: 

```swift        
apolloAuthClient.fetch(query: doctorsListQuery, cachePolicy: .returnCacheDataElseFetch, queue: DispatchQueue.main) { result in 
    switch result {
    case .success(let graphQLResult): // <-- This is what came in as an optional "result" before
        // graphQLResult.errors contains any errors which occurred at the GraphQL level
        // graphQLResult.data contains any data which was returned. 
    case .failure(let error): // <-- This is what came in as an optional "error" before
        // System level, network errors
    }
}
```

One thing to be aware of is that `graphQLResult` can contain both errors AND data in certain cases, which is part of why that hasn't been transitioned to a `Result` type - `Result` is more stuff that's a more binary success/failure, which is why it's been used to replace instances where a tuple of `(GraphQLResult?, Error?)` was previously being used.

**Comment by designatednerd** [comment]
@yousafiqbal1994 If you've got more questions please feel free to stop by our [Spectrum Chat](https://spectrum.chat/apollo/apollo-ios?tab=posts) and ask away! I'm going to close this out since it's more of a question than a problem, and I want to try and keep the Issues for things that are actually not working. Thanks!

**Comment by yousafiqbal1994** [comment]
Ok. Thank you so much. @designatednerd
