### ISSUE TITLE
Apollo 0.14.0 Apollo CLI mismatch

### ISSUE THREAD

**Issue by Nomad-Go** [apollographql/apollo-ios#700]
After upgrading to Apollo 0.14.0 and building my project the code generation build phase seems to have trouble upgrading the latest Apollo CLI on my behalf.

![Screen Shot 2019-08-08 at 9 41 56 AM](https://user-images.githubusercontent.com/42352379/62721609-712b4a80-b9c1-11e9-824d-11b418ac8d81.png)

**Comment by Nomad-Go** [comment]
A simple `sudo npm install -g apollo` fixes the issue. Mostly wanted to put this here for reference.

**Comment by designatednerd** [comment]
Ah, good to know - another good trick is to delete the `node_modules` folder that gets put into the root of your repo. That'll cause node to reinstall the latest version of the Apollo CLI. 

I'm not sure what's going on there with your permissions, though - that seems like it might be a bigger knot to untangle 😛 

Gonna close this issue since it's got a workaround - if someone else runs into this and is not able to address it with either @Nomad-Go's suggestion or mine, please open a new issue with as many details about your setup as possible. Thank you!
