### ISSUE TITLE
Compiler error - Instance member 'resultMap' cannot be used

### ISSUE THREAD

**Issue by tomasholicky** [apollographql/apollo-ios#706]
Compiler error:
 
<img width="1139" alt="Screenshot 2019-08-11 at 22 00 09" src="https://user-images.githubusercontent.com/8051677/62846263-8df6a500-bc83-11e9-853a-d7587d957bd7.png">

I tried generate code with SDK versions from 0.10.1 to 0.14.0, but I still get error above.

Could anybody try to generate code with schema and query, which I attached to this issue.

Thank you!

[schema_query.zip](https://github.com/apollographql/apollo-ios/files/3491078/schema_query.zip)

**Comment by designatednerd** [comment]
Oof, yeah this is a weird edge case. The problem is that a `Type` type is getting generated because of this section of your query: 

```graphql
type {
  id,
  aplCode,
  name,
  direction
},
```

That `Type` is conflicting with swift's existing `Type`, which is the metatype of the type it's being called on. This would require some significant workarounds to fix at the code-gen level, since we'd have to add backtick-escaping for this but check that it doesn't break other cases. 

Fortunately, it looks like there's a way simpler workaround. If you update that section of your code to look like this:

```graphql
itemType: type {
  id,
  aplCode,
  name,
  direction
},
```

You should still be querying the `type` under the hood, but codegen will generate a class called `ItemType` instead of `Type`, and then the conflict between your definition of `Type` and Swift's definition of `Type` will disappear. 

Give that a shot, and please let me know if it works!

**Comment by tomasholicky** [comment]
It works! 

Thanks a lot for quick support.

**Comment by designatednerd** [comment]
Woot, thanks for letting me know it worked 😃
