### ISSUE TITLE
Mutations always publish result to store

### ISSUE THREAD

**Issue by thonydam** [apollographql/apollo-ios#777]
When performing a mutation, the result always gets published to the store. 

```
  public func perform<Mutation: GraphQLMutation>(mutation: Mutation,
                                                 context: UnsafeMutableRawPointer? = nil,
                                                 queue: DispatchQueue = DispatchQueue.main,
                                                 resultHandler: GraphQLResultHandler<Mutation.Data>? = nil) -> Cancellable {
    return self.send(operation: mutation,
                     shouldPublishResultToStore: true,
                     context: context,
                     resultHandler: wrapResultHandler(resultHandler, queue: queue))
  }
```

I see why we might want to publish the result if the changes affect any watch query. Does it make sense to also be able to specify the cache policy for mutations as we do for queries?

Versions
Apollo-iOS 0.15.3

**Comment by designatednerd** [comment]
Makes sense to me - I'll talk to the person who originally wrote the code to see what the thought was on always publishing on a mutation though.

**Comment by designatednerd** [comment]
So I talked to @martijnwalraven and he made several good points:

- Mutation results always come from the server (never the cache, because the mutation needs to be executed on the server). Therefore, it doesn’t really make sense to expose the same cache policies as we do for queries. 
- Publishing mutation results to the store is important not only for watch queries, but also for future queries that read from the cache. Without publishing mutation results to the store, the cache would return out of date results.
- `shouldPublishResultToStore` was recently introduced to support fast path parsing behavior for queries, specifically queries with large result sets. Since mutation results are seldom all that large, it  wouldn't really be terribly beneficial from a processing perspective to skip them. 

I agree with all of these, though I think there's one case where not publishing to the store would make sense: When you're ignoring the cache completely. 

I don't know that with the current setup there's a great way to do that, though, since that option can be set per-query, and there may be some queries which ignore the cache completely and some which don't, and it's *real* hard to know from an SDK level whether someone's just ignoring the cache entirely.

**Comment by designatednerd** [comment]
@thonydam Does this answer your question as to why this is set up this way?

**Comment by thonydam** [comment]
@designatednerd Thank for your answer.
I do agree with your first 2 bullets points. For the 3rd one, I would say it depends of the mutation and the data coming back in that request.

I think the SDK should expose `shouldPublishResultToStore` parameter in the mutation, maybe default to true. This will give more control to the client in what happens under the hood.

**Comment by designatednerd** [comment]
I'm gonna tag this as an enhancement - heads up that dealing with caching stuff is a bit lower on my priority list at the moment, but we'd certainly welcome a PR.
