### ISSUE TITLE
Syntax highlighting not working in xCode 11?

### ISSUE THREAD

**Issue by adamirowe** [apollographql/apollo-ios#785]
Tried to active syntax highlighting after updating to xCode 11, and none of my .graphql files are getting updated. Does this script need to be updated? 

https://www.apollographql.com/docs/ios/installation/#optional-installing-the-xcode-add-ons-to-get-syntax-highlighting

Any way to get it added as an official xCode extension?

**Comment by designatednerd** [comment]
Because of changes to the Xcode extension system since Xcode 8, it can't be added as an official extension. 

You need to download a new version of the plugin that has the updated UUID for this version of Xcode from the [Xcode-GraphQL Repo](https://github.com/apollographql/xcode-graphql) and reinstall. 

If that doesn't work, let me know.

**Comment by adamirowe** [comment]
Yeah it's odd. I'm getting the indentations and code completion but not the coloring that I did in xCode 10 (I'm in dark mode, btw).

**Comment by designatednerd** [comment]
Yerp, broken, looks like Apple changed a couple things. Please follow [this issue on the plugin repo](https://github.com/apollographql/xcode-graphql/issues/23) for further updates.

**Comment by designatednerd** [comment]
I'm gonna close this out - please follow the issue on the plugin repo to get updates on what's going on with this. Thanks!
