### ISSUE TITLE
Problem at Xcode 8.3

### ISSUE THREAD

**Issue by IvanovDeveloper** [apollographql/apollo-ios#81]
When I've updated to Xcode 8.3 at  API (auto generated file) occurred crashes.

![screen shot 2017-04-13 at 12 15 47 pm](https://cloud.githubusercontent.com/assets/14201895/24998596/56d03b9c-2043-11e7-8711-819d90c35991.png)

This problem not at all requests

**Comment by martijnwalraven** [comment]
Is there any way you can create a minimal project that reproduces this issue? I've tried to reproduce it, but all the tests for version 0.5.6 still run on Xcode 8.3.

**Comment by IvanovDeveloper** [comment]
Ok, I will create project at Monday

**Comment by victorrr** [comment]
@martijnwalraven I am getting the same error from `GraphQLResultReader` `optionalValue`. 
Strangely I get only on device but not in simulator. 
It seems like you removed `GraphQLResultReader` now. Is a new version on the horizon?

**Comment by martijnwalraven** [comment]
@victorrr: Yes, I hope to release a new version soon, after https://github.com/apollographql/apollo-ios/pull/89 has been merged.

**Comment by monowerker** [comment]
I'm working with @victorrr and I can see that this is a stack overflow on a Thread used for an`ApolloClient` concurrent queue.

I haven't done much more debugging but our JSON models have some fields at around of 1500-2500 characters so if the data for a couple of those are stack allocated it will probably blow up, `Thread.stackSize` says 512KB.

If you think this is still an issue I'd be happy to provide any more information or help you may need in resolving it.

The stack overflows I've seen inside Apollo instead of our generated `API.swift` have all been in:
```
private func parse<T: GraphQLMappable>(object: JSONObject, intoType type: T.Type = T.self) throws -> T {
    objectStack.append(object)
    
    delegate?.willParse(object: object)
    let mappedObject = try T.init(reader: self)
    delegate?.didParse(object: object)
    
    objectStack.removeLast()
    
    return mappedObject
  }
```

**Comment by IvanovDeveloper** [comment]
I have the same problem. When I am upload a coupe of big string data, it is create allocation of memory

**Comment by martijnwalraven** [comment]
@monowerker @IvanovDeveloper: Hmmm, that's interesting. I don't think string length should itself ever lead to stack overflows, because strings are not stack allocated in Swift. Could it have to do with levels of nesting in the JSON? Do you have an example of the kind of response that leads to these crashes?

The parsing code has changed quite a bit on `master`, so this code is no longer in there. I suggest we test again after the new version lands. I'm not saying it will be bug free, but maybe they will be different bugs :)

**Comment by monowerker** [comment]
@martijnwalraven Alright, thanks. We'll test again when there is a new release. I sent you an example payload in an email to your commit address.

**Comment by martijnwalraven** [comment]
We just released Apollo iOS 0.6.0-beta.1, with major changes to the generated code and execution model. I hope that solves your issues. Make sure to use `npm install -g apollo-codegen@next` until it is out of beta.

Going to close this issue for now, but feel free to open a new issue if you encounter problems with the new version.

**Comment by victorrr** [comment]
@martijnwalraven thank you!

**Comment by IvanovDeveloper** [comment]
How to update pod to last beta vesion?

**Comment by martijnwalraven** [comment]
@IvanovDeveloper: You can change the reference in your `Podfile` to `pod 'Apollo', '~> 0.6.0-beta'`.

**Comment by IvanovDeveloper** [comment]
thank you
