### ISSUE TITLE
Is dynamic reconfiguration of the WebSocket connection payload supported?

### ISSUE THREAD

**Issue by Nickersoft** [apollographql/apollo-ios#824]
I've been updating my Apollo client recently to more accurately reflect [the example Singleton](https://www.apollographql.com/docs/ios/initialization/) that exists in the latest Apollo iOS documentation. I realized that with this new approach you can rely on the `HTTPNetworkTransportPreflightDelegate` to attach a dynamic auth header to outgoing HTTP requests, which is super helpful seeing I was previously just rebuilding the client on every user login/logout. I was curious if there is any way to achieve something similar with the WebSocket transport... I noticed it only accepts a hard-coded map of connection header values in its constructor that can't be changed. 

I'd be happy to help with implementing a solution if one doesn't currently exist... I'm just not exactly sure of the ideal approach seeing the transport would basically have to forcibly reconnect whenever its connection payload changes. It's a much-needed feature of my app, so I'd love to start a discussion about this.

**Comment by designatednerd** [comment]
Yeah the example singleton is using the `HTTPNetworkTransport` rather than the `WebSocketTransport`. You can always use the `SplitNetworkTransport` to get different headers for non-subscriptions (ie, queries and mutations). 

I think I'm a bit confused as to why you'd need to change the connection payload, though - once the WebSocket is open, wouldn't you want it to reconnect with the same payload? Or is on re-connect where you'd need to change the header?

**Comment by Nickersoft** [comment]
@designatednerd Hey, thanks for the quick response! I am in fact relying on `SplitNetworkTransport`, though I think the use case I'm thinking of is being able to update the websocket's header when the user logs in or out. I'm using JWT authentication for all HTTP and websocket endpoints on my server in order to get the current user's information and restrict their subscription access (e.g. in a chat app, one user shouldn't be able to subscribe to another user's incoming messages, only their own). I need to be able to swap the header's auth token for all outgoing requests, including websockets, when the currently logged-in user changes without necessarily rebuilding the client every time. Hopefully that makes sense.

**Comment by designatednerd** [comment]
Ah - to me "The user logged out" seems like a reasonable point at which to reconstruct the client, both because it doesn't really happen that often (outside of testing, anyway) and also because it seems like a reasonable place to terminate all existing connections and re-authenticate with new ones. 

Are users frequently logging in and out of your app?

**Comment by designatednerd** [comment]
@Nickersoft What's your thought on this suggestion?

**Comment by designatednerd** [comment]
In changes I made as part of #858, I exposed the `request` used for connection/reconnection. Would that work for what you're trying to do @Nickersoft?

**Comment by designatednerd** [comment]
I'm going to close this out since as of `0.19.0`, `request` is now exposed and you should be able to modify it as needed. If you're still looking for additional support, please open a new issue. Thank you!
