### ISSUE TITLE
Apollo build script causing Xcode 11 Canvas preview problems.

### ISSUE THREAD

**Issue by tyrong** [apollographql/apollo-ios#826]
It seems that the Apollo generate script causes issues with the  new canvas preview feature in Xcode 11.

To replicate just install the Apollo swift library add the build script and then try modify a screen with the preview enabled.
Removing the script resolves the issue.

Is there a way to run the script separately?

**Comment by designatednerd** [comment]
There isn't but [there's a workaround you can use to set up the inputs and outputs so it doesn't constantly regenerate](https://github.com/apollographql/apollo-tooling/issues/1573#issuecomment-539754801)

**Comment by designatednerd** [comment]
@tyrong Did this fix your issue? Is there anything else I can help with?

**Comment by designatednerd** [comment]
I've added information about [setting up input and output files to prevent rebuilds to our documentation](https://www.apollographql.com/docs/ios/installation/#advanced-codegen-tips-and-tricks). I'm gonna close this out since this is now officially documented, but if you're still having problems after applying that suggestion, please open a new issue. Thank you!
