### ISSUE TITLE
Swift error with rx

### ISSUE THREAD

**Issue by rad182** [apollographql/apollo-ios#832]
Hello I'm using Scott Hoyt's rxApollo
after I upgraded my swift and apollo version I get this error

`Generic parameter 'Query' could not be inferred`

<img width="973" alt="image" src="https://user-images.githubusercontent.com/71201/66801426-97ceaa00-ef4b-11e9-9198-b4fa0b9231bb.png">

Could anyone help me with this? TIA

**Comment by rad182** [comment]
closing this there was api changes for the theresultHandler. had to update it and it works now thanks

**Comment by designatednerd** [comment]
Yep - for anyone else who runs into this a reminder that we switched to `Result<T, Error>` from the Swift Standard library, rather than a tuple of `(T?, Error?)` around version `0.13.0`. If you see this kind of error from the compiler, double check you've got the correct type for the expected closure parameter (and correct number of things - 1 instead of 2).

**Comment by uyphanha** [comment]
@rad182 how do you fix this issue? I still can't find a way to solve this. Thanks before hand.

**Comment by uyphanha** [comment]
That's okay, I sorted this out.... 😄

**Comment by rad182** [comment]
@uyphanha good to hear you figure it out 👍
