### ISSUE TITLE
Plans to pull ApolloCodegen into separate project?

### ISSUE THREAD

**Issue by daviskoh** [apollographql/apollo-ios#848]
I was curious if there were plans to move the Swift codegen files & dirs to its own standalone package / repo.

**Comment by designatednerd** [comment]
Not at the moment - current plans are to [try to get a better way of providing the bundled codegen](https://github.com/apollographql/apollo-ios/issues/791) so we don't have to actually have the zip file be part of the repo. Then the longer term plan is to [move the generation part to Swift](https://github.com/apollographql/apollo-ios/projects/2). 

However, since codegen and the SDK are pretty tightly coupled (particularly in terms of testing once we move to swift), I don't think it makes a ton of sense to move the codegen stuff to another repo.

**Comment by designatednerd** [comment]
@daviskoh Does that answer your question or is there anything else I can help with here?

**Comment by designatednerd** [comment]
Since I've answered this question, I'm gonna go ahead and close this out, but if you have future questions, please feel free to ask them over at our [Spectrum Chat](https://spectrum.chat/apollo/apollo-ios), or if you have issues open 'em up here. Thank you!
