### ISSUE TITLE
Feature request: Download schema if it changed

### ISSUE THREAD

**Issue by gmoraleda** [apollographql/apollo-ios#849]
Hi,
our current setup with Apollo downloads the schema and generates the code on every build.
This is very robust, because we are sure that the moment the schema has a breaking change, our project won't compile anymore.
The problem with this approach is the compiling time. Downloading the schema takes 4\~5 seconds and generating the API takes an extra 1\~2s.
Is there a way to check the [etag](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.19) on the schema:download call?

Ideally we would only want to download and generate code if there are changes.

Thanks a lot in advance!

Our current build phases run script:
```
SCRIPT_PATH="${PODS_ROOT}/Apollo/scripts"
cd "${SRCROOT}/${TARGET_NAME}"
"${SCRIPT_PATH}"/run-bundled-codegen.sh schema:download --endpoint=https://ourendpoint.com/graphql schema.json
"${SCRIPT_PATH}"/run-bundled-codegen.sh codegen:generate --target=swift --includes=./**/*.graphql --localSchemaFile="schema.json" API.swift
```

**Comment by designatednerd** [comment]
Interesting - I'm not super familiar with how this is handled since it's done at the tooling repo level. Do any of the [additional options on the CLI](https://github.com/apollographql/apollo-tooling#apollo-clientdownload-schema-output) help you there? 

How frequently is your schema changing that you need to download on every single build?

**Comment by gmoraleda** [comment]
I'm not sure about the extra CLI options, I haven't seen an option that screams to me "this is what you should do if you want to check if your schema is the same than the one your server would output" 🤔 

Perhaps you can give us a hint here.

Regarding how often our schema changes... well, that's the thing. The beauty now is that we get to know that something is wrong (let's say a property went from non-nullable to nullable) because our code won't compile with the new generated API.swift file. So we don't need to care about downloading the schema every x hours/days/months.

Thanks again!

**Comment by designatednerd** [comment]
OK - it looks like the CLI team is [working on a `graph:info` command](https://github.com/apollographql/apollo-tooling/pull/1609) which will allow you to grab the [last updated date](https://github.com/apollographql/apollo-tooling/pull/1609/files#diff-07d5e15907e784797c4c5b580c1aaa67R32) if you're using Graph Manager. 

Checking in with them about the best way to check this if you're not using Graph Manager.

**Comment by designatednerd** [comment]
OK, got an update - there basically is no way to check this if you're not using some kind of schema registry. We are not planning on supporting `etag` checking directly.

Honestly though, even with a registry, I'm not sure doing that check is going to take all that much less time than the 4-5 seconds you're seeing for just redownloading the schema now. You might even be able to use a `git diff` on the schema file to see if anything has changed and if it hasn't, bail out of the codegen part of building. 

If you're still interested in this feature in the longer term, I'd advise opening an issue directly on the [tooling repo](https://github.com/apollographql/apollo-tooling) since that's where the CLI stuff lives, and you can chat with the tooling team in a bit more detail about your use case. 

Do you mind if I close this issue out since it's not a feature of the iOS SDK directly?

**Comment by designatednerd** [comment]
@gmoraleda Any thoughts on this?

**Comment by gmoraleda** [comment]
Sorry, I was away. I think we will go for a different solution, maybe downloading the file in a different place and diffing it against our project schema, as you suggested. That should save us the download and generation time (if the file wasn’t modified). We will keep an eye in the tooling repo though. Thanks for your feedback. You can gladly close the issue. Cheers!

**Comment by designatednerd** [comment]
Great, thank you!
