### ISSUE TITLE
Error: Fields "Field" conflict because they return conflicting types Field and Field!

### ISSUE THREAD

**Issue by TonnyL** [apollographql/apollo-ios#888]
I got this error when I try to compile my project:
**error: Fields "commit" conflict because they return conflicting types Commit and Commit!. Use different aliases on the fields to fetch both if this was intentional.**

Code below is my GraphQL fragments definition: 
```graphql
# Represents a 'merged' event on a given pull request.
# See https://developer.github.com/v4/object/mergedevent/
fragment MergedEventFragment on MergedEvent {
    # Identifies the actor who performed the event.
    actor {
        ... Actor
    }
    # Identifies the commit associated with the merge event.
    commit {
        ... PullRequestTimelineItemCommitFragment
    }
}

# Represents a Git commit.
# See https://developer.github.com/v4/object/commit/
fragment PullRequestTimelineItemCommitFragment on Commit {
    # Authorship details of the commit.
    author {
        ... GitActorFragment
    }
    # Committership details of the commit.
    committer {
        ... GitActorFragment
    }
    # The Git commit message
    message
    # The Git object ID
    oid
    # The HTTP URL for this commit
    url
}
```

`MergedEvent` definition from [schema.json](https://gist.github.com/TonnyL/e44437aa7391d5d3c6cdf03f6373338b): https://gist.github.com/TonnyL/7bedf6f0ac7b0496cdc3a823cef71885 and the doc reference: https://developer.github.com/v4/object/mergedevent/
`Commit` definition from [schema.json](https://gist.github.com/TonnyL/e44437aa7391d5d3c6cdf03f6373338b): https://gist.github.com/TonnyL/98f3a7941bb2d48cdfcafb212bd12ec1 and the doc reference: https://developer.github.com/v4/object/commit/

BTW, these GraphQL fragment definition could compile successfully when I use [apollo-android](https://github.com/apollographql/apollo-android).

**Comment by designatednerd** [comment]
I know @davedelong ran into the same thing recently as well from [this issue on our tooling repo](https://github.com/apollographql/apollo-tooling/issues/1635). I'm gonna futz with it a bit and see if I can figure out what the hell is going on.

On Android are you using the incubating plugin or the main one? I ask mostly because there was a significant rewrite between the two.

**Comment by TonnyL** [comment]
I'm using the main one instead of incubating plugin on Android.

**Comment by designatednerd** [comment]
OK cool - [I think I figured out Dave's issue](https://github.com/apollographql/apollo-tooling/issues/1635#issuecomment-550138284), which was essentially that his query included two different `... on Type` bits that wound up having the same name at the same level, with differing nullability options. This is definitely something to watch out for with nested fragments and/or trying to handle multiple different types in a single response. 

If my answer to him helps out, awesome, otherwise if you can post the query you're having problems with I'll see what I can figure out.

**Comment by TonnyL** [comment]
Cool and thanks. Look forward to see any progress on it.

**Comment by designatednerd** [comment]
@TonnyL Were you able to figure out what was going on, or would you like to share the query you're making?

**Comment by TonnyL** [comment]
@designatednerd  Sure, code below is my query:
```graphql
# Items in a pull request timeline
query PullRequestTimelineItems($owner: String!, $name: String!, $number: Int!, $after: String, $before: String, $perPage: Int!) {
    repository(owner: $owner, name: $name) {
        pullRequest(number: $number) {
            timelineItems(first: $perPage, after: $after, before: $before) {
                nodes {
                    # Represents a 'merged' event on a given pull request.
                    ... MergedEventFragment
                    # ... other fragments
                }
                # Information to aid in pagination.
                pageInfo {
                    ... PageInfo
                }
            }
        }
    }
}
```

**Comment by designatednerd** [comment]
I would double check the fragments included with `# ... other fragments` to see if any of them contain `commit` at the same level `MergedEventFragment` does. It looks like you're having a similar problem, in that you've got two different things both named `commit` at the same level, but one is optional and the other isn't. 

This "works" in terms of raw querying, but at least on the iOS side, it can't have code generated for it in a type safe fashion because of the conflict between optional and non-optional for the same name of a property in the same position.

**Comment by designatednerd** [comment]
Yeah it'd be nullable at the fragment level but it looks like there's some differences in terms of how it's set up between iOS and Android that make it difficult to have that work overall. 

Same advice as  I gave to Dave: Try aliasing the `commit` property on one of your fragments - then the names won't collide anymore.

**Comment by TonnyL** [comment]
Many thanks to you guys, I'll try it later 😉.

**Comment by designatednerd** [comment]
@TonnyL Did it wind up working?

**Comment by TonnyL** [comment]
@designatednerd Yes. After aliased all the conflicting fields, it finally worked. My project can build successfully now.

**Comment by designatednerd** [comment]
Hooray! Mind if we close this issue out then?

**Comment by TonnyL** [comment]
Close it plz. Thanks for your help 😀.
