### ISSUE TITLE
Module compiled with Swift 5.1 cannot be imported by the Swift 5.1.2 compiler

### ISSUE THREAD

**Issue by bdeemerInq** [apollographql/apollo-ios#891]
After updating to the latest Xcode version this morning, I can no longer build my project including Apollo. 

Any chance we're going to get a new version ASAP?

**Comment by designatednerd** [comment]
Hey @bdeemerInq - are you using Carthage for integration? If so you will need to rerun your Carthage build command, which will rebuild everything with the updated compiler. 

If you are not using Carthage, let me know!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sebastianbachmann** [comment]
Hi @bdeemerInq - does it help, if you set `BUILD_LIBRARY_FOR_DISTRIBUTION = YES;` in your projects Build Settings ...?!

**Comment by designatednerd** [comment]
@sebastianbachmann I'm curious, what's your thought with that suggestion? Are you using Carthage or a different dependency manager?

**Comment by sebastianbachmann** [comment]
Hey @designatednerd i am using CocoaPods. After rereading the question, i understand that my suggestion was a bit fast and not really helpful regarding the topic, sorry.

**Comment by bdeemerInq** [comment]
We are using CocoaPods

**Comment by designatednerd** [comment]
@bdeemerInq Have you tried cleaning the build folder and/or nuking derived data? Forcing a complete recompile should *theoretically* fix this issue.

**Comment by bdeemerInq** [comment]
@designatednerd I've tried deleting all derived data, cleaning everything. Restarting Xcode. Everything. I still get the same error.

**Comment by designatednerd** [comment]
That's...very weird. Would it be possible for you to send me your project (ellen at apollographql dot com)? 

A couple suggestions if you can't: 
- Check the project back out from version control in a new folder and try building there and seeing if you get the same error
- Make sure you delete *everything* from derived data, not just the current project's derived data. The error about a module being compiled with the wrong compiler generally indicates that hasn't been recompiled
- run `pod deintegrate` and `pod install` (basically, try turning cocoapods off and on again)
- (I only suggest this because I have seen it work for me in the past with bizarro Xcode build issues) Restart your computer.

**Comment by designatednerd** [comment]
@bdeemerInq any luck?

**Comment by bdeemerInq** [comment]
It seems to be working now. I can't say for sure which step solved the problem, but I threw everything at the wall and eventually it worked.

**Comment by designatednerd** [comment]
Oof, sorry it was such a pain. Do you mind if we close out this issue?

**Comment by designatednerd** [comment]
Going to close this out since the issue was eventually resolved and I haven't heard back in three weeks.
