### ISSUE TITLE
Support for SequelizeJSON?

### ISSUE THREAD

**Issue by roymckenzie** [apollographql/apollo-ios#90]
Hello,

Our developer is utilizing SequelizeJSON to allow custom queries on types. For example, this query:

```
offices(
  limit: Int
  order: String
  where: SequelizeJSON
  offset: Int
): [Office!]
```

When I try to recreate this query in Apollo for iOS

```
query GetOfficesByBuilding($id: Int! ) {
    offices(where: { buildingId: $id })
    {
        ...OfficeDetails
    }
}
```

the GraphQL server outputs

`Executing (default): SELECT "id", "name", "description", "buildingId" FROM "offices" AS "office" WHERE "office"."buildingId" IS NULL ORDER BY "office"."id" ASC;`

So, `"office"."buildingId"` should not be `NULL`.

When I try doing this query in the browser GraphiQL tool, the way I get it to work is:

```
query GetOfficesByBuilding( $query: SequelizeJSON ) {
  offices( where: $query )
  {
    id
    name
    description
  }
}
```

and under `Query variables` inputing:
`{"query": { "buildingId": 1 } }`

In IOS I have tried passing a string: `"{ \"buildingId\": 1 } }"` instead of the `buildingId` as I do in the GraphiQL interface example, but that doesn't seem to work either.

Apollo is typing `SequelizeJSON` as type `String`.

Any insight or help would be appreciated.

**Comment by designatednerd** [comment]
Couple things. 

Looks like on your iOS string, you're passing in an extra closing bracket. Try `{ \"buildingId\": 1 }` as your query. The extra bracket might be causing your server to just throw everything out since it doesn't decode as valid JSON.

The other thing is that I'm not quite sure what's on your fragment. Do you get the correct response when you put something like this into GraphiQL: 

```
fragment OfficeDetails on Office {
   [whatever your actual fragment is, not included above]
}

query GetOfficesByBuilding($id: Int! ) {
    offices(where: { buildingId: $id })
    {
        ...OfficeDetails
    }
}
```

I'm wondering if maybe something weird might be happening with the fragment too

**Comment by designatednerd** [comment]
@roymckenzie I'm going to close this out - if you've got follow-ups please start a thread on our [Spectrum Chat](https://spectrum.chat/apollo/apollo-ios?tab=posts), which is where we're trying to direct questions from here out so we can keep the issues tab more for problems. Thank you!
