### ISSUE TITLE
Why are `clientName` and `clientVersion` on `NetworkTransport` `set` properties? 

### ISSUE THREAD

**Issue by bwhiteley** [apollographql/apollo-ios#917]
Wouldn't `{ get }` be sufficient for these protocol properties? 
The `{ set }` complicates some implementations because I want them to be computed properties. I'm currently doing ` set { fatalError() }`, which works, but...

**Comment by bwhiteley** [comment]
Also, couldn't you then provide default implementations?

**Comment by designatednerd** [comment]
Hey @bwhiteley - we've already had [one extensive discussion around this in #877](https://github.com/apollographql/apollo-ios/issues/877). Take a look through that discussion, and me know if you have further questions after reading that. 

In terms of providing a default value, there is a default provided through the `defaultClientName` and `defaultClientVersion` computed properties defined in the `NetworkTransport` protocol, but you can't provide a default getter and setter for a computed property in a protocol. Basically this is a limitation of protocol-oriented programming when it comes to settable properties.

**Comment by designatednerd** [comment]
@bwhiteley Does this answer your question?

**Comment by bwhiteley** [comment]
I read the discussion in #877 but it still seems like the wrong decision. Apollo itself doesn't need the `clientName` and `clientVersion` to be mutable, and IMO that's what should drive the protocol requirements. If they are defined as `get`-only on the protocol, that doesn't prevent an implementation from changing them at runtime. 

Prior to this change it was easy to conform an existing REST client to `NetworkTransport` in an extension (which is what we do). The REST client in question is an API gateway client that handles things like authentication and token refresh. It comes from different framework from where we have Apollo code, so it is nice to add `NetworkTransport` conformance in an extension next to our Apollo code. Now we can't provide `NetworkTransport` conformance in an extension without doing something weird like having setters that do nothing or call `fatalError()` (since we have no need to modify the properties at runtime). 

Anyway, the workaround is easy enough so it's not the end of the world, but now you know our use case.

**Comment by designatednerd** [comment]
It's definitely helpful to understand the use case - the use case that I've been looking at has been focused on the people who do need to change this on a regular basis and use our batteries-included classes, so it's helpful to hear where the hard edges come together who don't. 

Unsurprisingly given my decision to do it the way we're doing it, I disagree with this assessment (which is fairly foundational to your argument):

> Apollo itself doesn't need the `clientName` and `clientVersion` to be mutable

Right now, since both `HTTPNetworkTransport` and `WebSocketTransport` are `public` rather than `open`, to make these properties get-only would require developers to create their own version of `HTTPNetworkTransport` anytime they wanted to have the client name and version be able to be updated at runtime. This is a feature request we have had to enable people to track what A/B tests are running without having to destroy and reconstruct the network transport when something changes.

An alternate solution could be to make only a few selected methods on `HTTPNetworkTransport` open, including these overridable getters, but I'm extremely reluctant to make that class subclassable. I will look into that though, because I do see your point about it being annoying to have to have the setter just return a fatal error if you don't want something to be settable.

**Comment by designatednerd** [comment]
This has shipped with 0.21.0 (may take a bit for it to show up on CocoaPods but it should be good to go with Carthage and SPM)
