### ISSUE TITLE
Naming error when generating mutation in Apollo Swift Codegen 

### ISSUE THREAD

**Issue by andre-felipe** [apollographql/apollo-ios#955]
This is the mutation I'm generating:
```
mutation ReportDriverTaskRelativeETA(
    $taskId: ID!
) {
    reportDriverTaskRelativeETA(input:{
        taskId: $taskId
    }) {
        ... on NoData {
            __typename
            description
        }
    }
}
```

Codegen seems to be renaming the "ETA" part in the mutation name to "ETum" for no apparent reason:
 ```
public struct ReportDriverTaskRelativeETum: GraphQLSelectionSet {
      public static let possibleTypes = ["NoData"]

      public static let selections: [GraphQLSelection] = [
        GraphQLField("__typename", type: .nonNull(.scalar(String.self))),
        GraphQLField("description", type: .nonNull(.scalar(String.self))),
      ]
(...)
}
```

That glitch alone would be "fine" (i.e. usable), but then the `get` accessor for the struct var renames the "ETum" part of the name yet again to "Etum":
```
public var reportDriverTaskRelativeEta: ReportDriverTaskRelativeETum {
      get {
        return ReportDriverTaskRelativeEtum(unsafeResultMap: resultMap["reportDriverTaskRelativeETA"]! as! ResultMap)
      }
      set {
        resultMap.updateValue(newValue.resultMap, forKey: "reportDriverTaskRelativeETA")
      }
    }
(...)
```

This "renaming mismatch" causes a build error:
![Screenshot 2019-12-17 at 16 06 22](https://user-images.githubusercontent.com/11345047/71087175-d6771f80-219b-11ea-8836-ba58cfdddbc2.png)

This only happens to this particular mutation, and if I rename it to something else (say "ReportDriverTaskRelativeEstimatedTimeOfArrival"), it's generated properly and works normally.

Anyone ever ran into something like this? Any ideas why this would happen?

**Comment by designatednerd** [comment]
Urgh. This is our singularization lib in the Typescript codegen thinking "ETA" is something like "Data" and trying to singularize it to something like "Datum".  

This behavior will be removed in the Swift Codegen. I'll have to look at our tooling stuff to see if there's a reasonable way to get rid of it in the TS stuff (I'm not sure there is without borking a bunch of other stuff though). 

In the meantime, the recommendation would be to use a different name for that mutation.

**Comment by designatednerd** [comment]
So I did try just straight up ripping out singularization rules, and that...went poorly. I think that's going to need to wait for later. I do want to try to figure out what's going on with the mismatched capitalization though.

I've traced that down to coming somewhere in the [very long `propertyDeclarationForField ` method in TS](https://github.com/apollographql/apollo-tooling/blob/master/packages/apollo-codegen-swift/src/codeGeneration.ts#L747), prooooobably when it calls into the [`mapExpressionForType` function](https://github.com/apollographql/apollo-tooling/blob/master/packages/apollo-codegen-swift/src/helpers.ts#L310), but for the life of me I can't figure out why the mismatch is happening. The `structName` seems to always be coming from the same variable, so I'm somewhat mystified as to how that would be happening.

@lilyball, I know you've worked a lot in the Typescript codegen in this area, do you have any thoughts on what the hell might be happening to cause the capitalization mismatch here?

**Comment by lilyball** [comment]
It's the [`structNameForPropertyName` function](https://github.com/apollographql/apollo-tooling/blob/3873bb33296bbb648941209d1bf75a985a293cb1/packages/apollo-codegen-swift/src/helpers.ts#L124) which is implemented as

```typescript
return pascalCase(Inflector.singularize(propertyName));
```

For some reason we're synthesizing the struct name from the property name instead of just using the `typeName` property we already have, which was used to produce the property type signature. I'm not quite sure how `typeName` is calculated.

**Comment by designatednerd** [comment]
Right - `structNameForPropertyName` is [being used to create the `structName` variable](https://github.com/apollographql/apollo-tooling/blob/master/packages/apollo-codegen-swift/src/codeGeneration.ts#L767) which as far as I can tell, is being passed directly into everything else it's calling. That's at least where the singularization is coming from. 

What I can't put my finger on is where the hell the difference in the capitalization of the result of that is coming from, which is causing the compile error. Does that help?

**Comment by lilyball** [comment]
As near as I can tell the `typeName` comes from [`propertyFromField`](https://github.com/apollographql/apollo-tooling/blob/3873bb33296bbb648941209d1bf75a985a293cb1/packages/apollo-codegen-swift/src/helpers.ts#L158) where it says

```typescript
    const unmodifiedTypeName = isCompositeType(unmodifiedType)
      ? structName
      : unmodifiedType.name;

    const typeName = this.typeNameFromGraphQLType(type, unmodifiedTypeName);
```

and [`typeNameFromGraphQLType`](https://github.com/apollographql/apollo-tooling/blob/3873bb33296bbb648941209d1bf75a985a293cb1/packages/apollo-codegen-swift/src/helpers.ts#L55) falls back to

```typescript
typeName = unmodifiedTypeName || type.name;
```

I don't know what `isCompositeType` actually means, but if this is not considered a composite type, then it will be passing `unmodifiedType.name` in (where `unmodifiedType` is just `getNamedType(field.type)`). In this case, I don't see where singularization comes in. If it is a composite type then it's passing `structName` which is the same `structNameForPropertyName` function but this type run on the `responseKey` instead of the `propertyName`.

FWIW the output of `Inflector.singularize` appears to be precisely the mis-capitalization, so the type name must somehow be coming from singularization without any pascalCasing going on. I just can't figure out where that could possibly be.

**Comment by lilyball** [comment]
Ultimately I have 2 questions:

1. Where the heck is singularization coming from without pascal-casing?
2. Why is the type name being used here not the result of `structNameForPropertyName` everywhere?

**Comment by designatednerd** [comment]
1. The singularization is a library from...somewhere in Javascript land
2. That's an *excellent* question that I have no damned clue about the answer to. 🙃

**Comment by lilyball** [comment]
1. Right, but the only call to singularization I could find was the same place where it was being pascal-cased. Unless the `graphql` library is also doing singularization itself, which would be kind of odd.

**Comment by designatednerd** [comment]
As far as I can tell, that's the only place it's getting singularized. I think the problem is that at some case the singularized version is getting capitalized differently, and I haven't had a chance to figure out where and/or why.
