### ISSUE TITLE
How access to last version Apollo CLI in bash script?

### ISSUE THREAD

**Issue by ImanX** [apollographql/apollo-ios#988]
I use [run-bundled-codegen.sh](https://github.com/apollographql/apollo-ios/blob/master/scripts/run-bundled-codegen.sh) on my project and I need to use last version `v2.21.0` and I changed link to `https://34622-65563448-gh.circle-artifacts.com/0/oclif-pack/apollo-v2.22.0/apollo-v2.22.0-darwin-x64.tar.gz` but not found `tar.gz` package.
How I access to `v2.21.0` package?

**Comment by designatednerd** [comment]
@ImanX You wouldn't be able to access either version with an altered link for the other one since they're going to be tied to totally different builds (and thus have a different link prefix). 

I'm a little confused, though - do you need to use v2.21.0 or v2.22.0? 2.21.0 is the one tied to the current release of the iOS SDK.

**Comment by ImanX** [comment]
@designatednerd Thanks for answer, I need to v2.22.0

**Comment by designatednerd** [comment]
You'd need to manually check out a different version using NPM at the moment rather than using the version included with `run-bundled-codegen` at the moment. 

Can you explain why you need this newer version? In theory you're going to want the version that's validated to work with the current version of the library, which is 2.21.0.

**Comment by designatednerd** [comment]
`0.22.0` contains CLI version `2.22.1`, which contains the changes you're looking for. Already tagged for Carthage or SPM, should be available via CocoaPods in the next ~hour.
